package EnergyDSL.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class Transaction_Constraints extends BaseConstraintsDescriptor {
  public Transaction_Constraints() {
    super(CONCEPTS.Transaction$Z0);
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept Transaction$Z0 = MetaAdapterFactory.getConcept(0xbde2436d1f60406fL, 0xa6ddb2e955d43687L, 0x77666e8443841ec8L, "EnergyDSL.structure.Transaction");
  }
}
