package StateMachineEnergyDSL.runtime;

/*Generated by MPS */

import org.hyperledger.fabric.shim.ChaincodeBase;
import org.hyperledger.fabric.shim.Chaincode;
import org.hyperledger.fabric.shim.ChaincodeStub;

@org.hyperledger.fabric.contract.annotation.Contract
public class Contract extends ChaincodeBase {
  @Override
  public Chaincode.Response init(ChaincodeStub stub) {
    return null;
  }
  @Override
  public Chaincode.Response invoke(ChaincodeStub stub) {
    return null;
  }
}
