package EnergyDSLExamples.a_model;

/*Generated by MPS */

import java.math.BigInteger;
import org.pcollections.PVector;
import jetbrains.mps.baseLanguage.closures.runtime._FunctionTypes;
import org.pcollections.TreePVector;
import org.pcollections.PMap;
import org.pcollections.HashTreePMap;
import java.util.Map;
import java.util.HashMap;
import java.math.BigDecimal;
import java.math.RoundingMode;

public class CData {




  public static Core.State statusC = Core.State.initial;
  public static Number txAddrC = ((Number) new BigInteger("0"));
  public static Number amountC = ((Number) new BigInteger("0"));
  public static Number balancesC = ((Number) new BigInteger("0"));
  public static PVector<EnergyOwnership> Ocj_ownership_structure = new _FunctionTypes._return_P0_E0<TreePVector<EnergyOwnership>>() {
    public TreePVector<EnergyOwnership> invoke() {
      TreePVector<EnergyOwnership> tpv = TreePVector.empty();
      tpv = tpv.plus(new EnergyOwnership(((Number) new BigInteger("0")), ((Number) new BigInteger("0")), ((Number) new BigInteger("1")), "initial"));
      return tpv;
    }
  }.invoke();
  public static PMap<Number, Number> D_demand_to_buy_t = HashTreePMap.from(new _FunctionTypes._return_P0_E0<Map>() {
    public Map invoke() {
      Map result = new HashMap();
      result.put(((Number) new BigInteger("0")), ((Number) new BigInteger("0")));
      return result;
    }
  }.invoke());
  public static Number Dmj_matched_amount = ((Number) new BigInteger("0"));
  public static Number timestampC = ((Number) new BigInteger("0"));
  public static Number i_c = ((Number) new BigInteger("0"));
  public static Number startDateC = ((Number) new BigInteger("0"));
  public static Number endDateC = ((Number) new BigInteger("0"));
  public static Core.State statusP = Core.State.initial;
  public static Number txAddrP = ((Number) new BigInteger("0"));
  public static Number E_injected = ((Number) new BigInteger("0"));
  public static PVector<EnergyOwnership> Opi_ownership_structure = new _FunctionTypes._return_P0_E0<TreePVector<EnergyOwnership>>() {
    public TreePVector<EnergyOwnership> invoke() {
      TreePVector<EnergyOwnership> tpv = TreePVector.empty();
      tpv = tpv.plus(new EnergyOwnership(((Number) new BigInteger("0")), ((Number) new BigInteger("0")), ((Number) new BigInteger("1")), "initial"));
      return tpv;
    }
  }.invoke();
  public static PMap<Number, Number> S_intent_to_sell_t = HashTreePMap.from(new _FunctionTypes._return_P0_E0<Map>() {
    public Map invoke() {
      Map result = new HashMap();
      result.put(((Number) new BigInteger("0")), ((Number) new BigInteger("0")));
      return result;
    }
  }.invoke());
  public static Number Smi_matched_amount = ((Number) new BigInteger("0"));
  public static Number timestampP = ((Number) new BigInteger("0"));
  public static Number i_p = ((Number) new BigInteger("0"));
  public static Number balances = ((Number) new BigInteger("0"));
  public static Number startDateP = ((Number) new BigInteger("0"));
  public static Number endDateP = ((Number) new BigInteger("0"));
  public static Number txAddrD = ((Number) new BigInteger("0"));
  public static Number ES_t = ((Number) new BigInteger("0"));
  public static Number ED_t = ((Number) new BigInteger("0"));
  public static Number R_t = ((Number) new BigInteger("0"));
  public static Number q = ((Number) new BigInteger("0"));
  public static Number D_t = ((Number) new BigInteger("0"));
  public static Number p_con = ((Number) new BigInteger("0"));
  public static Number p_balance = ((Number) new BigInteger("0"));
  public static Number k = ((Number) new BigInteger("0"));
  public static Number Smi = ((Number) new BigInteger("0"));
  public static Number Dmj = ((Number) new BigInteger("0"));
  public static PVector<Number> Si = new _FunctionTypes._return_P0_E0<TreePVector<Number>>() {
    public TreePVector<Number> invoke() {
      TreePVector<Number> tpv = TreePVector.empty();
      tpv = tpv.plus(((Number) new BigInteger("0")));
      return tpv;
    }
  }.invoke();
  public static PVector<Number> Dj = new _FunctionTypes._return_P0_E0<TreePVector<Number>>() {
    public TreePVector<Number> invoke() {
      TreePVector<Number> tpv = TreePVector.empty();
      tpv = tpv.plus(((Number) new BigInteger("0")));
      return tpv;
    }
  }.invoke();
  public static Number p_t = ((Number) new BigDecimal("0.0").setScale(1, RoundingMode.DOWN));
  public static Number timestampD = ((Number) new BigInteger("0"));
  public static Number delta_t = ((Number) new BigInteger("0"));
  public static Number startDateD = ((Number) new BigInteger("0"));
  public static Number endDtaD = ((Number) new BigInteger("0"));
  public static Number change = ((Number) new BigInteger("0"));





}
