package EnergyDSLExamples.a_model;

/*Generated by MPS */

import org.hyperledger.fabric.contract.annotation.Contract;
import org.hyperledger.fabric.contract.ContractInterface;
import org.hyperledger.fabric.shim.ChaincodeStub;
import java.util.ArrayList;
import EnergyDSL.runtime.ProsumerData;
import EnergyDSL.runtime.EnergyOwnershipSerializerDeserializer;
import com.owlike.genson.Genson;
import EnergyDSL.runtime.ConsumerData;
import EnergyDSL.runtime.DSOData;
import org.hyperledger.fabric.contract.annotation.Transaction;
import org.hyperledger.fabric.contract.Context;
import org.hyperledger.fabric.shim.Chaincode;
import jetbrains.mps.baseLanguage.closures.runtime._FunctionTypes;
import org.iets3.core.expr.simpleTypes.runtime.AH;
import java.math.BigInteger;
import java.util.List;
import com.owlike.genson.GenericType;
import java.util.Map;
import java.util.HashMap;

@Contract
public class DSO implements ContractInterface {

  public static String currentState = "initial";

  public static void setAsset(ChaincodeStub stub, String assetType, String assetString, ArrayList<String> argss) {
    String assetSerialized;
    if (assetType.contains("prosumer")) {
      ProsumerData assetObject = EnergyOwnershipSerializerDeserializer.deserializeProsumer(assetString);
      for (int i = 1; i < argss.size() - 1; i = i + 2) {
        String argKey = argss.get(i);
        String setKey = argss.get(i + 1);
        if (setKey.startsWith("set_")) {
          switch (argKey) {
            case "statusP":
              assetObject.setstatusP(setKey);
            case "txAddrP":
              assetObject.settxAddrP(setKey);

            case "amountP":
              assetObject.setamountP(setKey);

            case "balancesP":
              assetObject.setbalancesP(setKey);

            case "E_injected":
              assetObject.setE_injected(setKey);

            case "i_p":
              assetObject.seti_p(setKey);

            case "startDateP":
              assetObject.setstartDateP(setKey);
            case "endDateP":
              assetObject.setendDateP(setKey);

            case "Opi_ownership_structure":
              assetObject.setOpi_ownership_structure(setKey);

            case "Smi_matched_amount":
              assetObject.setSmi_matched_amount(setKey);
          }
        }
      }
      String prosumerName = "prosumer_" + assetObject.geti_p();
      assetSerialized = new Genson().serialize(assetObject);
      stub.putStringState(prosumerName, assetSerialized);
    } else if (assetType.contains("consumer")) {
      ConsumerData consumerObject = EnergyOwnershipSerializerDeserializer.deserializeConsumer(assetString);

      for (int i = 1; i < argss.size() - 1; i = i + 2) {
        String argKey = argss.get(i);
        String setKey = argss.get(i + 1);
        if (setKey.startsWith("set_")) {
          switch (argKey) {
            case "statusC":
              consumerObject.setstatusC(setKey);
            case "txAddrC":
              consumerObject.settxAddrC(setKey);

            case "amountC":
              consumerObject.setamountC(setKey);

            case "balancesC":
              consumerObject.setbalancesC(setKey);

            case "D_demand_to_buy_t":
              consumerObject.setD_demand_to_buy_t(setKey);

            case "i_c":
              consumerObject.seti_c(setKey);

            case "startDateC":
              consumerObject.setstartDateC(setKey);
            case "endDateP":
              consumerObject.setendDateC(setKey);

            case "Ocj_ownership_structure":
              consumerObject.setOcj_ownership_structure(setKey);

            case "Dmj_matched_amount":
              consumerObject.setDmj_matched_amount(setKey);
          }
        }
      }
      String consumerName = "consumer_" + consumerObject.geti_c();
      assetSerialized = new Genson().serialize(consumerObject);
      stub.putStringState(consumerName, assetSerialized);

    } else if (assetType.contains("DSO")) {
      DSOData dsoObject = EnergyOwnershipSerializerDeserializer.deserializeDSO(assetString);
      for (int i = 1; i < argss.size() - 1; i = i + 2) {
        String argKey = argss.get(i);
        String setKey = argss.get(i + 1);
        if (setKey.startsWith("set_")) {
          switch (argKey) {
            case "ES_t":
              dsoObject.setES_t(setKey);
            case "txAddrD":
              dsoObject.settxAddrD(setKey);

            case "ED_t":
              dsoObject.setED_t(setKey);

            case "R_t":
              dsoObject.setR_t(setKey);

            case "D_t":
              dsoObject.setD_t(setKey);

            case "q":
              dsoObject.setq(setKey);

            case "p_con":
              dsoObject.setp_con(setKey);
            case "p_balance":
              dsoObject.setp_balance(setKey);

            case "Dmj":
              dsoObject.setDmj(setKey);

            case "Smi":
              dsoObject.setSmi(setKey);
            case "k":
              dsoObject.setk(setKey);

            case "Si":
              dsoObject.setSi(setKey);

            case "Dj":
              dsoObject.setDj(setKey);

            case "p_t":
              dsoObject.setp_t(setKey);
            case "delta_t ":
              dsoObject.setdelta_t(setKey);

            case "change ":
              dsoObject.setchange(setKey);

            case "timestampD ":
              dsoObject.settimestampD(setKey);

            case "beginDateD":
              dsoObject.setbeginDateD(setKey);

            case "endDateD":
              dsoObject.setendDateD(setKey);
          }

        }
      }
      String dsoName = "DSO";
      assetSerialized = new Genson().serialize(dsoName);
      stub.putStringState(dsoName, assetSerialized);

    }
  }

  private String getProsumerAsset(ProsumerData assetObject, String propName) {
    switch (propName) {
      case "statusP":
        return assetObject.getstatusP();
      case "txAddrP":
        return assetObject.gettxAddrP();

      case "amountP":
        return assetObject.getamountP();

      case "balancesP":
        return assetObject.getbalancesP();

      case "E_injected":
        return assetObject.getE_injected();

      case "i_p":
        return assetObject.geti_p();

      case "startDateP":
        return assetObject.getstartDateP();
      case "endDateP":
        return assetObject.getendDateP();

      case "Opi_ownership_structure":
        return assetObject.getOpi_ownership_structure();

      case "Smi_matched_amount":
        return assetObject.getSmi_matched_amount();
    }
    return "";
  }

  private String getConsumerAsset(ConsumerData consumerObject, String propName) {
    switch (propName) {
      case "statusC":
        return consumerObject.getstatusC();
      case "txAddrC":
        return consumerObject.gettxAddrC();

      case "amountC":
        return consumerObject.getamountC();

      case "balancesC":
        consumerObject.getbalancesC();

      case "D_demand_to_buy_t":
        return consumerObject.getD_demand_to_buy_t();

      case "i_c":
        return consumerObject.geti_c();

      case "startDateC":
        return consumerObject.getstartDateC();
      case "endDateP":
        return consumerObject.getendDateC();

      case "Ocj_ownership_structure":
        return consumerObject.getOcj_ownership_structure();

      case "Dmj_matched_amount":
        return consumerObject.getDmj_matched_amount();
    }
    return "";
  }


  private String getDSOAsset(DSOData dsoObject, String propName) {
    switch (propName) {
      case "ES_t":
        return dsoObject.getES_t();
      case "txAddrD":
        return dsoObject.gettxAddrD();

      case "ED_t":
        return dsoObject.getED_t();

      case "R_t":
        return dsoObject.getR_t();

      case "D_t":
        return dsoObject.getD_t();

      case "q":
        return dsoObject.getq();

      case "p_con":
        return dsoObject.getp_con();
      case "p_balance":
        return dsoObject.getp_balance();

      case "Dmj":
        return dsoObject.getDmj();

      case "Smi":
        return dsoObject.getSmi();
      case "k":
        return dsoObject.getk();

      case "Si":
        return dsoObject.getSi();

      case "Dj":
        return dsoObject.getDj();

      case "p_t":
        return dsoObject.getp_t();
      case "delta_t ":
        return dsoObject.getdelta_t();

      case "change ":
        return dsoObject.getchange();

      case "timestampD ":
        return dsoObject.gettimestampD();

      case "beginDateD":
        return dsoObject.getbeginDateD();

      case "endDateD":
        return dsoObject.getendDateD();
    }
    return "";
  }



  public static String name = DSO.class.toString();





  @Transaction
  public String sendTx(Context ctx, String state, String txAddrP, String txAddrC, String Ei_or_Si, String timetsamp, String i, String startDate, String endDate, String Smi, String Dmj, String p_t) {
    ChaincodeStub stub = ctx.getStub();
    ArrayList<String> argss = new ArrayList<>();
    argss.add(state);
    argss.add(txAddrP);
    argss.add(txAddrC);
    argss.add(Ei_or_Si);
    argss.add(timetsamp);
    argss.add(i);
    argss.add(startDate);
    argss.add(endDate);
    argss.add(Smi);
    argss.add(Dmj);
    argss.add(p_t);
    Chaincode.Response request = null;
    {
      String Smi_s = "0.0";
      String Dmj_s = "0.0";
      String Ei_or_Si_s = "0.0";
      String ij = "0";
      String system_state = "";
      String txAddrPi = "";
      String ts = "";
      String pt = "";
      String start_date = "";
      String end_date = "";

      system_state = state;

      txAddrPi = txAddrP;


      Ei_or_Si_s = Ei_or_Si;



      start_date = startDate;

      end_date = endDate;

      Smi_s = Smi;

      Dmj_s = Dmj;

      pt = p_t;


      Double incr = Double.valueOf(Ei_or_Si_s) - Double.valueOf(Smi_s);
      switch (system_state) {
        case "inject":
          request = stub.invokeChaincodeWithStringArgs("smart_contract", txAddrPi, Ei_or_Si_s, ij, "injected", ts, "prosumer", "require");
          boolean is_dso = Boolean.valueOf(request.getStringPayload());
          if (is_dso) {
            request = stub.invokeChaincodeWithStringArgs("smart_contract", txAddrPi, "10", "injected", ts, ij, "prosumer", "event");

          }
          return "";
        case "roundstart":
          request = stub.invokeChaincodeWithStringArgs("smart_contract", ts, "order_elements");

          return "";
        case "trade":
          request = stub.invokeChaincodeWithStringArgs("smart_contract", pt, start_date, end_date, ts, Smi_s, "calculate_balances");

          return "";

        case "matching":
          request = stub.invokeChaincodeWithStringArgs("DSO", start_date, end_date, ts, ij, "calculate");
          request = stub.invokeChaincodeWithStringArgs("smart_contract", txAddrPi, Smi_s, "match", ts, ij, "prosumer", "event");
          request = stub.invokeChaincodeWithStringArgs("smart_contract", txAddrPi, Smi_s, "match", ts, ij, "consumer", "event");
          request = stub.invokeChaincodeWithStringArgs("smart_contract", txAddrPi, Ei_or_Si_s, "board", ts, ij, "prosumer", "delete");

          request = stub.invokeChaincodeWithStringArgs("smart_contract", txAddrPi, incr.toString(), "injected", ts, ij, "prosumer", "event");




          return "";
        default:
          return "Error";
      }



    }





  }

  public Boolean require_dso(Context ctx, String addrTxDs) {
    ChaincodeStub stub = ctx.getStub();
    boolean bool = false;
    String txAddrD = stub.getStringState("txAddrD");
    if (currentState.equals("initialized") && txAddrD.equals(addrTxDs)) {
      bool = true;
    }

    return bool;
  }
  public static Number pricingByDSO(final Number ED_t, final Number ES_t, final Number k, Number e, final Number p_con, final Number p_balance) {
    Number res = new _FunctionTypes._return_P0_E0<Number>() {
      public Number invoke() {

        Number p_t = (AH.add(AH.mul(AH.mul(AH.div(((Number) new BigInteger("2")), Math.PI), p_con), Math.pow(((Double) ((Number) new BigInteger("-1"))), ((Double) Math.tan(Math.log(Math.pow(((Double) k), ((Double) AH.div(ED_t, ES_t)))))))), p_balance));
        return p_t;
      }
    }.invoke();

    return res;
  }

  public Boolean is_dso(Context ctx, String addrTxDs) {
    ChaincodeStub stub = ctx.getStub();
    boolean bool = false;
    String txAddrD = stub.getStringState("txAddrD");
    if (currentState.equals("initialized") && txAddrD.equals(addrTxDs)) {
      bool = true;
    }
    return bool;
  }
  @Transaction
  public String calculate(Context ctx, String timestamp, String startDate, String endDate, String ij, String Smc) {
    ChaincodeStub stub = ctx.getStub();
    ArrayList<String> argss = new ArrayList<>();
    argss.add(timestamp);
    argss.add(startDate);
    argss.add(endDate);
    argss.add(ij);
    argss.add(Smc);
    Chaincode.Response request = null;

    request = stub.invokeChaincodeWithStringArgs("smart_contract", "get_registered_prosumers_size");
    int n_num_prosumers = Integer.valueOf(request.getStringPayload());

    request = stub.invokeChaincodeWithStringArgs("smart_contract", "get_registered_consumers_size");
    int n_num_consumers = Integer.valueOf(request.getStringPayload());

    request = stub.invokeChaincodeWithStringArgs("smart_contract", "get_registered_prosumers");
    String prosString = request.getStringPayload();
    List<ProsumerData> pros = new Genson().deserialize(prosString, new GenericType<List<ProsumerData>>() {});
    Map<Long, Double> sS = new HashMap<Long, Double>();
    Long ts = 0L;
    Double tnum = 0.0;
    Integer j = 0;
    ts = Long.valueOf(timestamp);



    j = Integer.valueOf(ij);


    List<Double> Si = new Genson().deserialize(stub.getStringState("Si"), new GenericType<List<Double>>() {});
    for (int i = 0; i < pros.size(); i++) {
      Map<Long, Double> s_intent = new Genson().deserialize(pros.get(i).S_intent_to_sell_t, new GenericType<HashMap<Long, Double>>() {});

      sS.putAll(s_intent);
      if (sS.containsKey(ts)) {
        tnum = sS.get(ts);
      } else {
        tnum = 0.0;
        Si.add(tnum);
      }
      sS.clear();
    }
    int jj = Si.size() - 1;
    double sum = 0;
    for (double d : Si) {
      sum += d;
    }
    double ES_t = sum;
    argss.add("DSO");

    argss.add("ES_t");
    argss.add(String.valueOf(sum));


    request = stub.invokeChaincodeWithStringArgs("smart_contract", "get_registered_consumers");
    String consString = request.getStringPayload();
    List<ConsumerData> cons = new Genson().deserialize(consString, new GenericType<List<ConsumerData>>() {});
    List<Double> Dj = new Genson().deserialize(stub.getStringState("Dj"), new GenericType<List<Double>>() {});


    Map<Long, Double> dD = new HashMap<Long, Double>();
    for (int i = 0; i < cons.size(); i++) {
      Map<Long, Double> demand = new Genson().deserialize(cons.get(i).D_demand_to_buy_t, new GenericType<Map<Long, Double>>() {});
      dD.putAll(demand);
      if (dD.containsKey(ts)) {
        tnum = dD.get(ts);
      } else {
        tnum = 0.0;
        Dj.add(tnum);
      }
      dD.clear();
    }

    sum = 0;
    for (double d : Dj) {
      sum += d;
    }
    double ED_t = sum;
    double R_t = ED_t / ES_t;
    double D_t = ED_t - ES_t;
    if (ES_t >= ED_t) {
      Map<Long, Double> intent = new Genson().deserialize(pros.get(j).S_intent_to_sell_t, new GenericType<HashMap<Long, Double>>() {});


      String Smi = String.valueOf(R_t * intent.get(ts));
      argss.add("Smi");
      argss.add(Smi);

      String assetName = argss.get(0);
      String assetObjectString = stub.getStringState(assetName);
      setAsset(stub, assetName, assetObjectString, argss);

      request = stub.invokeChaincodeWithStringArgs("smart_contract", "change_Smi_for_registered_prosumer", Smi, String.valueOf(j));
      request = stub.invokeChaincodeWithStringArgs("smart_contract", "change_registered_prosumers_Smi_find", String.valueOf(ts), String.valueOf(R_t));
      Map<Long, Double> dmj = new Genson().deserialize(cons.get(j).D_demand_to_buy_t, new GenericType<HashMap<Long, Double>>() {});

      String Dmj = String.valueOf(dmj.get(ts));

      request = stub.invokeChaincodeWithStringArgs("smart_contract", "change_Smi_for_registered_consumer", String.valueOf(Dmj), String.valueOf(j));
      request = stub.invokeChaincodeWithStringArgs("smart_contract", "change_registered_consumers_D_demand_find", String.valueOf(ts), String.valueOf(Dmj));
      if (ES_t * R_t != ED_t) {
        return "WRONG CALCULATION";
      }
    } else {
      request = stub.invokeChaincodeWithStringArgs("smart_contract", "changeSmiToS_intentForRegisteredProsumer", String.valueOf(ts), String.valueOf(j));
      request = stub.invokeChaincodeWithStringArgs("smart_contract", "change_Smi_to_S_intent_for_all_registered_prosumer", String.valueOf(ts), String.valueOf(j));
      request = stub.invokeChaincodeWithStringArgs("smart_contract", "change_Dmj_to_D_demand_for_registered_consumer", String.valueOf(ts), String.valueOf(j));
      request = stub.invokeChaincodeWithStringArgs("smart_contract", "change_Dmj_to_D_demand_all_for_registered_consumer", String.valueOf(ts), String.valueOf(j));
      if (ES_t != ED_t / R_t) {
        return "WRONG CALCULATION";
      }



    }

    return "done";
  }


  @Transaction
  public String calculate(Context ctx, String timestamp, String startDate, String endDate, String ij, String Smc) {
    ChaincodeStub stub = ctx.getStub();
    ArrayList<String> argss = new ArrayList<>();
    argss.add(timestamp);
    argss.add(startDate);
    argss.add(endDate);
    argss.add(ij);
    argss.add(Smc);
    Chaincode.Response request = null;

    request = stub.invokeChaincodeWithStringArgs("smart_contract", "get_registered_prosumers_size");
    int n_num_prosumers = Integer.valueOf(request.getStringPayload());

    request = stub.invokeChaincodeWithStringArgs("smart_contract", "get_registered_consumers_size");
    int n_num_consumers = Integer.valueOf(request.getStringPayload());

    request = stub.invokeChaincodeWithStringArgs("smart_contract", "get_registered_prosumers");
    String prosString = request.getStringPayload();
    List<ProsumerData> pros = new Genson().deserialize(prosString, new GenericType<List<ProsumerData>>() {});
    Map<Long, Double> sS = new HashMap<Long, Double>();
    Long ts = 0L;
    Double tnum = 0.0;
    Integer j = 0;
    ts = Long.valueOf(timestamp);



    j = Integer.valueOf(ij);


    List<Double> Si = new Genson().deserialize(stub.getStringState("Si"), new GenericType<List<Double>>() {});
    for (int i = 0; i < pros.size(); i++) {
      Map<Long, Double> s_intent = new Genson().deserialize(pros.get(i).S_intent_to_sell_t, new GenericType<HashMap<Long, Double>>() {});

      sS.putAll(s_intent);
      if (sS.containsKey(ts)) {
        tnum = sS.get(ts);
      } else {
        tnum = 0.0;
        Si.add(tnum);
      }
      sS.clear();
    }
    int jj = Si.size() - 1;
    double sum = 0;
    for (double d : Si) {
      sum += d;
    }
    double ES_t = sum;
    argss.add("DSO");

    argss.add("ES_t");
    argss.add(String.valueOf(sum));


    request = stub.invokeChaincodeWithStringArgs("smart_contract", "get_registered_consumers");
    String consString = request.getStringPayload();
    List<ConsumerData> cons = new Genson().deserialize(consString, new GenericType<List<ConsumerData>>() {});
    List<Double> Dj = new Genson().deserialize(stub.getStringState("Dj"), new GenericType<List<Double>>() {});


    Map<Long, Double> dD = new HashMap<Long, Double>();
    for (int i = 0; i < cons.size(); i++) {
      Map<Long, Double> demand = new Genson().deserialize(cons.get(i).D_demand_to_buy_t, new GenericType<Map<Long, Double>>() {});
      dD.putAll(demand);
      if (dD.containsKey(ts)) {
        tnum = dD.get(ts);
      } else {
        tnum = 0.0;
        Dj.add(tnum);
      }
      dD.clear();
    }

    sum = 0;
    for (double d : Dj) {
      sum += d;
    }
    double ED_t = sum;
    double R_t = ED_t / ES_t;
    double D_t = ED_t - ES_t;
    if (ES_t >= ED_t) {
      Map<Long, Double> intent = new Genson().deserialize(pros.get(j).S_intent_to_sell_t, new GenericType<HashMap<Long, Double>>() {});


      String Smi = String.valueOf(R_t * intent.get(ts));
      argss.add("Smi");
      argss.add(Smi);

      String assetName = argss.get(0);
      String assetObjectString = stub.getStringState(assetName);
      setAsset(stub, assetName, assetObjectString, argss);

      request = stub.invokeChaincodeWithStringArgs("smart_contract", "change_Smi_for_registered_prosumer", Smi, String.valueOf(j));
      request = stub.invokeChaincodeWithStringArgs("smart_contract", "change_registered_prosumers_Smi_find", String.valueOf(ts), String.valueOf(R_t));
      Map<Long, Double> dmj = new Genson().deserialize(cons.get(j).D_demand_to_buy_t, new GenericType<HashMap<Long, Double>>() {});

      String Dmj = String.valueOf(dmj.get(ts));

      request = stub.invokeChaincodeWithStringArgs("smart_contract", "change_Smi_for_registered_consumer", String.valueOf(Dmj), String.valueOf(j));
      request = stub.invokeChaincodeWithStringArgs("smart_contract", "change_registered_consumers_D_demand_find", String.valueOf(ts), String.valueOf(Dmj));
      if (ES_t * R_t != ED_t) {
        return "WRONG CALCULATION";
      }
    } else {
      request = stub.invokeChaincodeWithStringArgs("smart_contract", "changeSmiToS_intentForRegisteredProsumer", String.valueOf(ts), String.valueOf(j));
      request = stub.invokeChaincodeWithStringArgs("smart_contract", "change_Smi_to_S_intent_for_all_registered_prosumer", String.valueOf(ts), String.valueOf(j));
      request = stub.invokeChaincodeWithStringArgs("smart_contract", "change_Dmj_to_D_demand_for_registered_consumer", String.valueOf(ts), String.valueOf(j));
      request = stub.invokeChaincodeWithStringArgs("smart_contract", "change_Dmj_to_D_demand_all_for_registered_consumer", String.valueOf(ts), String.valueOf(j));
      if (ES_t != ED_t / R_t) {
        return "WRONG CALCULATION";
      }



    }

    return "done";
  }








}
