package EnergyDSLExamples.a_model;

/*Generated by MPS */

import org.hyperledger.fabric.contract.annotation.Contract;
import org.hyperledger.fabric.contract.ContractInterface;
import org.hyperledger.fabric.shim.ChaincodeStub;
import java.util.ArrayList;
import EnergyDSL.runtime.ProsumerData;
import EnergyDSL.runtime.EnergyOwnershipSerializerDeserializer;
import com.owlike.genson.Genson;
import EnergyDSL.runtime.ConsumerData;
import EnergyDSL.runtime.DSOData;
import jetbrains.mps.baseLanguage.closures.runtime._FunctionTypes;
import org.iets3.core.expr.simpleTypes.runtime.AH;
import java.math.BigInteger;

@Contract
public class DSO_backup implements ContractInterface {

  public static String currentState = "initial";

  public static void setAsset(ChaincodeStub stub, String assetType, String assetString, ArrayList<String> argss) {
    String assetSerialized;
    if (assetType.contains("prosumer")) {
      ProsumerData assetObject = EnergyOwnershipSerializerDeserializer.deserializeProsumer(assetString);
      for (int i = 1; i < argss.size() - 1; i = i + 2) {
        String argKey = argss.get(i);
        String setKey = argss.get(i + 1);
        if (setKey.startsWith("set_")) {
          switch (argKey) {
            case "statusP":
              assetObject.setstatusP(setKey);
            case "txAddrP":
              assetObject.settxAddrP(setKey);

            case "amountP":
              assetObject.setamountP(setKey);

            case "balancesP":
              assetObject.setbalancesP(setKey);

            case "E_injected":
              assetObject.setE_injected(setKey);

            case "i_p":
              assetObject.seti_p(setKey);

            case "startDateP":
              assetObject.setstartDateP(setKey);
            case "endDateP":
              assetObject.setendDateP(setKey);

            case "Opi_ownership_structure":
              assetObject.setOpi_ownership_structure(setKey);

            case "Smi_matched_amount":
              assetObject.setSmi_matched_amount(setKey);
          }
        }
      }
      String prosumerName = "prosumer_" + assetObject.geti_p();
      assetSerialized = new Genson().serialize(assetObject);
      stub.putStringState(prosumerName, assetSerialized);
    } else if (assetType.contains("consumer")) {
      ConsumerData consumerObject = EnergyOwnershipSerializerDeserializer.deserializeConsumer(assetString);

      for (int i = 1; i < argss.size() - 1; i = i + 2) {
        String argKey = argss.get(i);
        String setKey = argss.get(i + 1);
        if (setKey.startsWith("set_")) {
          switch (argKey) {
            case "statusC":
              consumerObject.setstatusC(setKey);
            case "txAddrC":
              consumerObject.settxAddrC(setKey);

            case "amountC":
              consumerObject.setamountC(setKey);

            case "balancesC":
              consumerObject.setbalancesC(setKey);

            case "D_demand_to_buy_t":
              consumerObject.setD_demand_to_buy_t(setKey);

            case "i_c":
              consumerObject.seti_c(setKey);

            case "startDateC":
              consumerObject.setstartDateC(setKey);
            case "endDateP":
              consumerObject.setendDateC(setKey);

            case "Ocj_ownership_structure":
              consumerObject.setOcj_ownership_structure(setKey);

            case "Dmj_matched_amount":
              consumerObject.setDmj_matched_amount(setKey);
          }
        }
      }
      String consumerName = "consumer_" + consumerObject.geti_c();
      assetSerialized = new Genson().serialize(consumerObject);
      stub.putStringState(consumerName, assetSerialized);

    } else if (assetType.contains("DSO")) {
      DSOData dsoObject = EnergyOwnershipSerializerDeserializer.deserializeDSO(assetString);
      for (int i = 1; i < argss.size() - 1; i = i + 2) {
        String argKey = argss.get(i);
        String setKey = argss.get(i + 1);
        if (setKey.startsWith("set_")) {
          switch (argKey) {
            case "ES_t":
              dsoObject.setES_t(setKey);
            case "txAddrD":
              dsoObject.settxAddrD(setKey);

            case "ED_t":
              dsoObject.setED_t(setKey);

            case "R_t":
              dsoObject.setR_t(setKey);

            case "D_t":
              dsoObject.setD_t(setKey);

            case "q":
              dsoObject.setq(setKey);

            case "p_con":
              dsoObject.setp_con(setKey);
            case "p_balance":
              dsoObject.setp_balance(setKey);

            case "Dmj":
              dsoObject.setDmj(setKey);

            case "Smi":
              dsoObject.setSmi(setKey);
            case "k":
              dsoObject.setk(setKey);

            case "Si":
              dsoObject.setSi(setKey);

            case "Dj":
              dsoObject.setDj(setKey);

            case "p_t":
              dsoObject.setp_t(setKey);
            case "delta_t ":
              dsoObject.setdelta_t(setKey);

            case "change ":
              dsoObject.setchange(setKey);

            case "timestampD ":
              dsoObject.settimestampD(setKey);

            case "beginDateD":
              dsoObject.setbeginDateD(setKey);

            case "endDateD":
              dsoObject.setendDateD(setKey);
          }

        }
      }
      String dsoName = "DSO";
      assetSerialized = new Genson().serialize(dsoName);
      stub.putStringState(dsoName, assetSerialized);

    }
  }

  private String getProsumerAsset(ProsumerData assetObject, String propName) {
    switch (propName) {
      case "statusP":
        return assetObject.getstatusP();
      case "txAddrP":
        return assetObject.gettxAddrP();

      case "amountP":
        return assetObject.getamountP();

      case "balancesP":
        return assetObject.getbalancesP();

      case "E_injected":
        return assetObject.getE_injected();

      case "i_p":
        return assetObject.geti_p();

      case "startDateP":
        return assetObject.getstartDateP();
      case "endDateP":
        return assetObject.getendDateP();

      case "Opi_ownership_structure":
        return assetObject.getOpi_ownership_structure();

      case "Smi_matched_amount":
        return assetObject.getSmi_matched_amount();
    }
    return "";
  }

  private String getConsumerAsset(ConsumerData consumerObject, String propName) {
    switch (propName) {
      case "statusC":
        return consumerObject.getstatusC();
      case "txAddrC":
        return consumerObject.gettxAddrC();

      case "amountC":
        return consumerObject.getamountC();

      case "balancesC":
        consumerObject.getbalancesC();

      case "D_demand_to_buy_t":
        return consumerObject.getD_demand_to_buy_t();

      case "i_c":
        return consumerObject.geti_c();

      case "startDateC":
        return consumerObject.getstartDateC();
      case "endDateP":
        return consumerObject.getendDateC();

      case "Ocj_ownership_structure":
        return consumerObject.getOcj_ownership_structure();

      case "Dmj_matched_amount":
        return consumerObject.getDmj_matched_amount();
    }
    return "";
  }


  private String getDSOAsset(DSOData dsoObject, String propName) {
    switch (propName) {
      case "ES_t":
        return dsoObject.getES_t();
      case "txAddrD":
        return dsoObject.gettxAddrD();

      case "ED_t":
        return dsoObject.getED_t();

      case "R_t":
        return dsoObject.getR_t();

      case "D_t":
        return dsoObject.getD_t();

      case "q":
        return dsoObject.getq();

      case "p_con":
        return dsoObject.getp_con();
      case "p_balance":
        return dsoObject.getp_balance();

      case "Dmj":
        return dsoObject.getDmj();

      case "Smi":
        return dsoObject.getSmi();
      case "k":
        return dsoObject.getk();

      case "Si":
        return dsoObject.getSi();

      case "Dj":
        return dsoObject.getDj();

      case "p_t":
        return dsoObject.getp_t();
      case "delta_t ":
        return dsoObject.getdelta_t();

      case "change ":
        return dsoObject.getchange();

      case "timestampD ":
        return dsoObject.gettimestampD();

      case "beginDateD":
        return dsoObject.getbeginDateD();

      case "endDateD":
        return dsoObject.getendDateD();
    }
    return "";
  }



  public static String name = DSO_backup.class.toString();






  public static Number pricingByDSO(final Number ED_t, final Number ES_t, final Number k, Number e, final Number p_con, final Number p_balance) {
    Number res = new _FunctionTypes._return_P0_E0<Number>() {
      public Number invoke() {

        Number p_t = (AH.add(AH.mul(AH.mul(AH.div(((Number) new BigInteger("2")), Math.PI), p_con), Math.pow(((Double) ((Number) new BigInteger("-1"))), ((Double) Math.tan(Math.log(Math.pow(((Double) k), ((Double) AH.div(ED_t, ES_t)))))))), p_balance));
        return p_t;
      }
    }.invoke();

    return res;
  }











}
