package EnergyDSLExamples.a_model;

/*Generated by MPS */

import EnergyDSL.runtime.Asset;
import java.lang.reflect.Field;
import com.owlike.genson.Genson;
import com.owlike.genson.GenericType;
import java.util.Map;
import java.util.HashMap;
import org.json.JSONObject;

/**
 * 
 */
public class Energy extends Asset {
  public Energy(Object... args) {
    super(((Integer) args[0]));
    try {
      Field[] fields = this.getClass().getDeclaredFields();
      for (int i = 1; i - 1 < args.length; i++) {
        fields[i - 1].set(this, args[i]);
      }
    } catch (IllegalAccessException e) {
      e.printStackTrace();
    }
  }
  protected Number test;
  public Number gettest() {
    return test;
  }
  public void settest(Number test) {
    this.test = test;
  }

  public static Energy deserialize(String jsonObject) {
    Energy asset = new Genson().deserialize(jsonObject, new GenericType<Energy>() {});

    return asset;
  }

  public String serialize() {
    Map<String, Object> map = new HashMap<>();
    map.put("test", test);


    return new JSONObject(map).toString();
  }




}
