package EnergyDSLExamples.a_model;

/*Generated by MPS */

import org.hyperledger.fabric.contract.annotation.Contract;
import org.hyperledger.fabric.contract.annotation.Default;
import org.hyperledger.fabric.contract.ContractInterface;
import org.hyperledger.fabric.shim.ChaincodeStub;
import java.util.ArrayList;
import EnergyDSL.runtime.ProsumerData;
import com.owlike.genson.Genson;
import EnergyDSL.runtime.ConsumerData;
import EnergyDSL.runtime.DSOData;
import org.hyperledger.fabric.contract.annotation.Transaction;
import org.hyperledger.fabric.contract.Context;
import java.util.Date;
import org.hyperledger.fabric.shim.Chaincode;
import java.util.List;
import com.owlike.genson.GenericType;

@Contract(name = "MyContract")
@Default
public class Prosumer implements ContractInterface {


  public static String setAsset(ChaincodeStub stub, String assetType, String assetString, ArrayList<String> argss) {
    String assetSerialized;
    if (assetString == null) {
      return null;
    }
    if (assetType.toLowerCase().contains("prosumer")) {
      ProsumerData assetObject = new Genson().deserialize(assetString, ProsumerData.class);
      String key;
      for (int i = 0; i < argss.size() - 1; i = i + 2) {
        String argKey = argss.get(i);
        String setKey = argss.get(i + 1).toLowerCase();
        if (setKey.startsWith("set_")) {
          key = setKey.substring(4);
          switch (key) {
            case "statusp":
              assetObject.setStatusP(argKey);
              break;
            case "txaddrp":
              assetObject.setTxAddrP(argKey);
              break;
            case "amountp":
              assetObject.setAmountP(argKey);
              break;
            case "balancesp":
              assetObject.setBalancesP(argKey);
              break;
            case "e_injected":
              assetObject.setE_injected(argKey);
              break;
            case "i_p":
              assetObject.setI_p(argKey);
              break;
            case "startdatep":
              assetObject.setStartDateP(argKey);
              break;
            case "enddatep":
              assetObject.setEndDateP(argKey);
              break;
            case "opi_ownership_structure":
              assetObject.setOpi_ownership_structure(argKey);
              break;
            case "smi_matched_amount":
              assetObject.setSmi_matched_amount(argKey);
              break;
          }
        }
      }
      String prosumerName = "prosumer_" + assetObject.getI_p();
      assetSerialized = new Genson().serialize(assetObject);
      stub.putStringState(prosumerName, assetSerialized);
      return assetSerialized;
    } else if (assetType.toLowerCase().contains("consumer")) {
      ConsumerData consumerObject = new Genson().deserialize(assetString, ConsumerData.class);
      String key;
      for (int i = 0; i < argss.size() - 1; i = i + 2) {
        String argKey = argss.get(i);
        String setKey = argss.get(i + 1).toLowerCase();
        if (setKey.startsWith("set_")) {
          key = setKey.substring(4);
          switch (key) {
            case "statusc":
              consumerObject.setStatusC(argKey);
              break;
            case "txaddrc":
              consumerObject.setTxAddrC(argKey);
              break;
            case "amountc":
              consumerObject.setAmountC(argKey);
              break;
            case "balancesc":
              consumerObject.setBalancesC(argKey);
              break;
            case "d_demand_to_buy_t":
              consumerObject.setD_demand_to_buy_t(argKey);
              break;
            case "i_c":
              consumerObject.setI_c(argKey);
              break;
            case "startdatec":
              consumerObject.setStartDateC(argKey);
              break;
            case "enddatec":
              consumerObject.setEndDateC(argKey);
              break;
            case "ocj_ownership_structure":
              consumerObject.setOcj_ownership_structure(argKey);
              break;
            case "dmj_matched_amount":
              consumerObject.setDmj_matched_amount(argKey);
              break;
            case "dmj":
              consumerObject.setDmj(argKey);
              break;
            case "dj_t":
              consumerObject.setDj_t(argKey);
              break;
          }
        }
      }
      String consumerName = "consumer_" + consumerObject.getI_c();
      assetSerialized = new Genson().serialize(consumerObject);
      stub.putStringState(consumerName, assetSerialized);
      return assetSerialized;

    } else if (assetType.contains("dso")) {
      DSOData dsoObject = new Genson().deserialize(assetString, DSOData.class);
      String key;
      for (int i = 0; i < argss.size() - 1; i = i + 2) {
        String argKey = argss.get(i);
        String setKey = argss.get(i + 1).toLowerCase();
        if (setKey.startsWith("set_")) {
          key = setKey.substring(4);
          switch (key) {
            case "es_t":
              dsoObject.setES_t(argKey);
              break;
            case "txaddrd":
              dsoObject.setTxAddrD(argKey);
              break;
            case "ed_t":
              dsoObject.setED_t(argKey);
              break;
            case "r_t":
              dsoObject.setR_t(argKey);
              break;
            case "d_t":
              dsoObject.setD_t(argKey);
              break;
            case "q":
              dsoObject.setQ(argKey);
              break;
            case "p_con":
              dsoObject.setP_con(argKey);
              break;
            case "p_max":
              dsoObject.setP_max(argKey);
              break;
            case "p_balance":
              dsoObject.setP_balance(argKey);
              break;
            case "dmj":
              dsoObject.setDmj(argKey);
              break;
            case "smi":
              dsoObject.setSmi(argKey);
              break;
            case "k":
              dsoObject.setK(argKey);
              break;
            case "si":
              dsoObject.setSi(argKey);
              break;
            case "dj":
              dsoObject.setDj(argKey);
              break;
            case "p_t":
              dsoObject.setP_t(argKey);
              break;
            case "delta_t":
              dsoObject.setDelta_t(argKey);
              break;
            case "change":
              dsoObject.setChange(argKey);
              break;
            case "timestampd":
              dsoObject.setTimestampD(argKey);
              break;
            case "begindated":
              dsoObject.setBeginDateD(argKey);
              break;
            case "enddated":
              dsoObject.setEndDateD(argKey);
              break;
          }
        }
      }
      String dsoName = "dso";
      assetSerialized = new Genson().serialize(dsoObject);
      System.out.println(dsoObject);
      stub.putStringState(dsoName, assetSerialized);
      return dsoObject.toString();
    }
    return null;
  }

  private String getProsumerAsset(ProsumerData assetObject, String propName) {
    if (assetObject == null) {
      return null;
    }
    String prop = propName.toLowerCase();
    switch (prop) {
      case "statusp":
        return assetObject.getStatusP();
      case "txaddrp":
        return assetObject.getTxAddrP();
      case "amountp":
        return assetObject.getAmountP();
      case "balancesp":
        return assetObject.getBalancesP();
      case "e_injected":
        return assetObject.getE_injected();
      case "i_p":
        return assetObject.getI_p();
      case "startdatep":
        return assetObject.getStartDateP();
      case "enddatep":
        return assetObject.getEndDateP();
      case "opi_ownership_structure":
        return assetObject.getOpi_ownership_structure();
      case "smi_matched_amount":
        return assetObject.getSmi_matched_amount();
    }
    return null;
  }

  private String getConsumerAsset(ConsumerData consumerObject, String propName) {
    if (consumerObject == null) {
      return null;
    }
    String prop = propName.toLowerCase();
    switch (prop) {
      case "statusc":
        return consumerObject.getStatusC();
      case "txaddrc":
        return consumerObject.getTxAddrC();
      case "amountc":
        return consumerObject.getAmountC();
      case "balancesc":
        consumerObject.getBalancesC();
      case "d_demand_to_buy_t":
        return consumerObject.getD_demand_to_buy_t();
      case "i_c":
        return consumerObject.getI_c();
      case "startdatec":
        return consumerObject.getStartDateC();
      case "enddatec":
        return consumerObject.getEndDateC();
      case "ocj_ownership_structure":
        return consumerObject.getOcj_ownership_structure();
      case "dmj_matched_amount":
        return consumerObject.getDmj_matched_amount();
    }
    return null;
  }

  private String getDSOAsset(DSOData dsoObject, String propName) {
    if (dsoObject == null) {
      return null;
    }
    String prop = propName.toLowerCase();
    switch (prop) {
      case "es_t":
        return dsoObject.getES_t();
      case "txaddrd":
        return dsoObject.getTxAddrD();
      case "ed_t":
        return dsoObject.getED_t();
      case "r_t":
        return dsoObject.getR_t();
      case "d_t":
        return dsoObject.getD_t();
      case "q":
        return dsoObject.getQ();
      case "p_con":
        return dsoObject.getP_con();
      case "p_balance":
        return dsoObject.getP_balance();
      case "dmj":
        return dsoObject.getDmj();
      case "smi":
        return dsoObject.getSmi();
      case "k":
        return dsoObject.getK();
      case "si":
        return dsoObject.getSi();
      case "dj":
        return dsoObject.getDj();
      case "p_t":
        return dsoObject.getP_t();
      case "delta_t":
        return dsoObject.getDelta_t();
      case "change":
        return dsoObject.getChange();
      case "timestampd":
        return dsoObject.getTimestampD();
      case "begindated":
        return dsoObject.getBeginDateD();
      case "enddated":
        return dsoObject.getEndDateD();
      case "p_max":
        return dsoObject.getP_max();
    }
    return null;
  }

  /**
   * msg,prosumer
   */
  @Transaction
  public String msg(Context ctx, String prosumer, String name, String stateP, String set_stateP, String Ei, String set_Ei, String i_p, String set_i_p, String txAddrP, String set_txAddrP, String Smi, String Dmj, String p_t, String txAddrC, String channelName) {
    ChaincodeStub stub = ctx.getStub();
    String msg = "";
    ArrayList<String> argss = new ArrayList<>();
    argss.add(prosumer);
    argss.add(name);
    argss.add(stateP);
    argss.add(set_stateP);
    argss.add(Ei);
    argss.add(set_Ei);
    argss.add(i_p);
    argss.add(set_i_p);
    argss.add(txAddrP);
    argss.add(set_txAddrP);
    argss.add(Smi);
    argss.add(Dmj);
    argss.add(p_t);
    argss.add(txAddrC);
    String assetName = argss.get(0);
    String assetObjectString = (stub.getStringState(assetName) != null ? stub.getStringState(assetName) : "{}");
    setAsset(stub, assetName, assetObjectString, argss);
    String stat = "";
    String stats = "inject";
    String EiN = "";
    String timestampN = String.valueOf(new Date().getTime());
    String iN = "";
    String txAddrPN = "";
    String txAddrCN = "";
    String SmiN = "";
    String DmjN = "";
    String p_tN = "";
    stats = stateP;
    if (stateP.startsWith("match")) {
      stats = "matching";
    } else if (stateP.startsWith("inject")) {
      stats = "inject";
    }
    EiN = Ei;
    iN = i_p;
    txAddrPN = txAddrP;
    SmiN = Smi;
    DmjN = Dmj;
    p_tN = p_t;
    txAddrCN = txAddrC;
    Chaincode.Response response = stub.invokeChaincodeWithStringArgs("dso", "sendTx", stats, txAddrPN, txAddrCN, EiN, timestampN, iN, String.valueOf(Integer.valueOf(timestampN) + Math.multiplyExact(60, 10 * 1000)), String.valueOf(Integer.valueOf(timestampN) - Math.multiplyExact(60, 10 * 1000)), SmiN, DmjN, p_tN, channelName);
    return response.getStringPayload();
  }


  /**
   * set not _add, no owneship
   */
  @Transaction
  public String setSendTx_Num(Context ctx, String state, String set_state, String timestampP, String set_timestampP, String amountP, String set_amountP, String Opi_ownership_structure, String set_Opi_ownership_structure_add, String Smi, String set_Smi, String channelName) {
    ChaincodeStub stub = ctx.getStub();
    ArrayList<String> argss = new ArrayList<>();
    argss.add(state);
    argss.add(set_state);
    argss.add(timestampP);
    argss.add(set_timestampP);
    argss.add(amountP);
    argss.add(set_amountP);
    argss.add(Opi_ownership_structure);
    argss.add(set_Opi_ownership_structure_add);
    argss.add(Smi);
    argss.add(set_Smi);
    String num = "0.0";
    String ts = "0L";
    String states = "";
    String txAddr = "0";
    int i = 0;
    states = state;
    String msg = "";
    String argName = argss.get(0);
    String setI = argss.get(1);
    String argKey = "";
    Chaincode.Response res;
    Genson genson = new Genson();
    try {
      ArrayList<String> argst = new ArrayList<>(argss.subList(2, argss.size()));
      System.out.println(argst.toString());
      if (argName.toLowerCase().contains("consumer")) {
        msg = setAsset(stub, "consumer", "{}", argst);
        res = stub.invokeChaincodeWithStringArgs("smc", "set_registered_consumer", msg, channelName);
        msg = res.getStringPayload();
      } else if (argName.toLowerCase().contains("prosumer")) {
        msg = setAsset(stub, "prosumer", "{}", argst);
        res = stub.invokeChaincodeWithStringArgs("smc", "set_registered_prosumer", msg, channelName);
        msg = res.getStringPayload();
      } else if (argName.toLowerCase().contains("dso")) {
        msg = setAsset(stub, "dso", "{}", argst);
      }
      return String.valueOf(msg);
    } catch (Exception e) {
      System.out.println("Error");
      System.out.println(e.getMessage());
      e.printStackTrace();
      return e.getMessage();
    }
  }
  /**
   * set _add, no ownership
   */
  @Transaction
  public String setState_add(Context ctx, String assetName, String j, String state, String set_state, String channelName) {
    ChaincodeStub stub = ctx.getStub();
    ArrayList<String> argss = new ArrayList<>();
    argss.add(assetName);
    argss.add(j);
    argss.add(state);
    argss.add(set_state);
    String num = "0.0";
    String ts = "0L";
    String states = "";
    String txAddr = "0";
    int i = 0;
    states = state;
    String msg = "";
    String argName = argss.get(0);
    String setI = argss.get(1);
    String argKey = "";
    Chaincode.Response res;
    Genson genson = new Genson();
    ArrayList<String> argst = new ArrayList<String>(argss.subList(2, argss.size()));
    try {
      if (argName.toLowerCase().contains("consumer")) {
        res = stub.invokeChaincodeWithStringArgs("smc", "get_registered_consumers", channelName);
        String regsString = res.getStringPayload();
        if (regsString == null) {
          return null;
        }
        List<ConsumerData> regC;
        regC = new Genson().deserialize(regsString, new GenericType<List<ConsumerData>>() {});
        if (regC == null) {
          return null;
        }
        msg = setAsset(stub, "consumer", genson.serialize(regC.get(Integer.valueOf(setI))), ((ArrayList<String>) argss.subList(2, argss.size())));
        res = stub.invokeChaincodeWithStringArgs("smc", "set_registered_consumer", msg, channelName);
        msg = res.getStringPayload();
      } else if (argName.toLowerCase().contains("prosumer")) {
        res = stub.invokeChaincodeWithStringArgs("smc", "get_registered_prosumers", channelName);
        String regsString = res.getStringPayload();
        List<ProsumerData> regP;
        if (regsString == null) {
          return null;
        }
        regP = genson.deserialize(regsString, new GenericType<List<ProsumerData>>() {});
        if (regP == null) {
          return null;
        }
        msg = setAsset(stub, "prosumer", genson.serialize(regP.get(Integer.valueOf(setI))), ((ArrayList<String>) argss.subList(2, argss.size())));
        res = stub.invokeChaincodeWithStringArgs("smc", "set_registered_prosumer", msg, channelName);
        msg = res.getStringPayload();
      } else if (argName.toLowerCase().contains("dso")) {
        String dsoString = stub.getStringState("dso");
        String result = null;
        if (dsoString != null) {
          result = dsoString;
        }
        msg = setAsset(stub, "dso", result, argst);
      }

    } catch (Exception e) {
      System.out.println("Error");
      System.out.println(e.getMessage());
      e.printStackTrace();
      return "Error";
    }
    return msg;
  }






  /**
   * sendTx
   */
  @Transaction
  public String sendTx(Context ctx, String stateP, String set_stateP, String timestampP, String set_timestampP, String Si_t, String i_p, String startDate, String endDate, String channelName) {
    ChaincodeStub stub = ctx.getStub();
    ArrayList<String> argss = new ArrayList<>();
    argss.add(stateP);
    argss.add(set_stateP);
    argss.add(timestampP);
    argss.add(set_timestampP);
    argss.add(Si_t);
    argss.add(i_p);
    argss.add(startDate);
    argss.add(endDate);
    Chaincode.Response request = null;
    Genson genson = new Genson();
    String stateN = "";
    String timestampN = "";
    String numN = "";
    String i_n = "";
    String startDateN;
    String endDateN;
    String pmaxN = "";
    stateN = stateP;
    timestampN = timestampP;
    i_n = i_p;
    startDateN = startDate;
    endDateN = endDate;
    if (argss.get(0).equalsIgnoreCase("getState_add")) {
      request = stub.invokeChaincodeWithStringArgs("smc", "getState_add", channelName);
    } else {

      request = stub.invokeChaincodeWithStringArgs("prosumer", "setState_add", "prosumer", i_n, stateN, "set_statusP", channelName);

      if (stateN.equalsIgnoreCase("requestbuy")) {
        request = stub.invokeChaincodeWithStringArgs("smc", "validate_consumer", startDateN, endDateN, timestampN, pmaxN, numN, i_n, channelName);
      } else if (stateN.equalsIgnoreCase("requestsell")) {
        request = stub.invokeChaincodeWithStringArgs("smc", "validate_prosumer", startDateN, endDateN, timestampN, pmaxN, numN, i_n, channelName);
      } else if (stateN.equalsIgnoreCase("register")) {
        request = stub.invokeChaincodeWithStringArgs("smc", "pro_init", timestampN, "set_timestamp", stateN, "set_state", i_n, channelName);
      } else {
        request = stub.invokeChaincodeWithStringArgs("smc", "event", "prosumer", timestampN, stateN, numN, i_n, channelName);
      }
    }
    return request.getStringPayload();

  }

  /**
   * transfer prosumer
   */
  @Transaction
  public String transfer(Context ctx, String ij, String balance, String channelName) {
    ChaincodeStub stub = ctx.getStub();
    String msg = "";
    ArrayList<String> argss = new ArrayList<>();
    argss.add(ij);
    argss.add(balance);
    Integer iN = 0;
    Double value = 0.0;
    Chaincode.Response request;
    Genson genson = new Genson();
    iN = Integer.valueOf(ij);
    value = Double.valueOf(balance);
    request = stub.invokeChaincodeWithStringArgs("smc", "get_registered_prosumers", channelName);
    String regsString = request.getStringPayload();
    List<ProsumerData> regs = genson.deserialize(regsString, new GenericType<List<ProsumerData>>() {});
    if (regs == null) {
      System.out.println("No registered prosumers");
      return null;
    }
    regs.get(iN).setBalancesP(String.valueOf(Double.valueOf(regs.get(iN).getBalancesP()) + value));
    ArrayList<String> arg = new ArrayList<String>();
    arg.add(String.valueOf(Double.valueOf(regs.get(iN).getBalancesP()) + value));
    arg.add("set_balancesp");
    setAsset(stub, "prosumer", genson.serialize(regs.get(iN)), arg);
    request = stub.invokeChaincodeWithStringArgs("smc", "set_registered_prosumers", genson.serialize(regs), channelName);
    return "true";
  }

















}
