package EnergyDSLExamples.a_model;

/*Generated by MPS */

import org.hyperledger.fabric.contract.annotation.Contract;
import org.hyperledger.fabric.contract.annotation.Default;
import org.hyperledger.fabric.contract.ContractInterface;
import org.hyperledger.fabric.shim.ChaincodeStub;
import java.util.ArrayList;
import EnergyDSL.runtime.ProsumerData;
import com.owlike.genson.Genson;
import EnergyDSL.runtime.ConsumerData;
import EnergyDSL.runtime.DSOData;
import org.hyperledger.fabric.contract.annotation.Transaction;
import org.hyperledger.fabric.contract.Context;
import org.hyperledger.fabric.shim.Chaincode;
import java.util.List;
import com.owlike.genson.GenericType;
import java.util.Map;
import java.util.HashMap;
import EnergyDSL.runtime.EnergyOwnership;
import java.util.Date;
import EnergyDSL.runtime.SmartContractData;

@Contract(name = "MyContract")
@Default
public class Smc implements ContractInterface {


  public static String setAsset(ChaincodeStub stub, String assetType, String assetString, ArrayList<String> argss) {
    String assetSerialized;
    if (assetString == null) {
      return null;
    }
    if (assetType.toLowerCase().contains("prosumer")) {
      ProsumerData assetObject = new Genson().deserialize(assetString, ProsumerData.class);
      String key;
      for (int i = 0; i < argss.size() - 1; i = i + 2) {
        String argKey = argss.get(i);
        String setKey = argss.get(i + 1).toLowerCase();
        if (setKey.startsWith("set_")) {
          key = setKey.substring(4);
          switch (key) {
            case "statusp":
              assetObject.setStatusP(argKey);
              break;
            case "txaddrp":
              assetObject.setTxAddrP(argKey);
              break;
            case "amountp":
              assetObject.setAmountP(argKey);
              break;
            case "balancesp":
              assetObject.setBalancesP(argKey);
              break;
            case "e_injected":
              assetObject.setE_injected(argKey);
              break;
            case "i_p":
              assetObject.setI_p(argKey);
              break;
            case "startdatep":
              assetObject.setStartDateP(argKey);
              break;
            case "enddatep":
              assetObject.setEndDateP(argKey);
              break;
            case "opi_ownership_structure":
              assetObject.setOpi_ownership_structure(argKey);
              break;
            case "smi_matched_amount":
              assetObject.setSmi_matched_amount(argKey);
              break;
          }
        }
      }
      String prosumerName = "prosumer_" + assetObject.getI_p();
      assetSerialized = new Genson().serialize(assetObject);
      stub.putStringState(prosumerName, assetSerialized);
      return assetSerialized;
    } else if (assetType.toLowerCase().contains("consumer")) {
      ConsumerData consumerObject = new Genson().deserialize(assetString, ConsumerData.class);
      String key;
      for (int i = 0; i < argss.size() - 1; i = i + 2) {
        String argKey = argss.get(i);
        String setKey = argss.get(i + 1).toLowerCase();
        if (setKey.startsWith("set_")) {
          key = setKey.substring(4);
          switch (key) {
            case "statusc":
              consumerObject.setStatusC(argKey);
              break;
            case "txaddrc":
              consumerObject.setTxAddrC(argKey);
              break;
            case "amountc":
              consumerObject.setAmountC(argKey);
              break;
            case "balancesc":
              consumerObject.setBalancesC(argKey);
              break;
            case "d_demand_to_buy_t":
              consumerObject.setD_demand_to_buy_t(argKey);
              break;
            case "i_c":
              consumerObject.setI_c(argKey);
              break;
            case "startdatec":
              consumerObject.setStartDateC(argKey);
              break;
            case "enddatec":
              consumerObject.setEndDateC(argKey);
              break;
            case "ocj_ownership_structure":
              consumerObject.setOcj_ownership_structure(argKey);
              break;
            case "dmj_matched_amount":
              consumerObject.setDmj_matched_amount(argKey);
              break;
            case "dmj":
              consumerObject.setDmj(argKey);
              break;
            case "dj_t":
              consumerObject.setDj_t(argKey);
              break;
          }
        }
      }
      String consumerName = "consumer_" + consumerObject.getI_c();
      assetSerialized = new Genson().serialize(consumerObject);
      stub.putStringState(consumerName, assetSerialized);
      return assetSerialized;

    } else if (assetType.contains("dso")) {
      DSOData dsoObject = new Genson().deserialize(assetString, DSOData.class);
      String key;
      for (int i = 0; i < argss.size() - 1; i = i + 2) {
        String argKey = argss.get(i);
        String setKey = argss.get(i + 1).toLowerCase();
        if (setKey.startsWith("set_")) {
          key = setKey.substring(4);
          switch (key) {
            case "es_t":
              dsoObject.setES_t(argKey);
              break;
            case "txaddrd":
              dsoObject.setTxAddrD(argKey);
              break;
            case "ed_t":
              dsoObject.setED_t(argKey);
              break;
            case "r_t":
              dsoObject.setR_t(argKey);
              break;
            case "d_t":
              dsoObject.setD_t(argKey);
              break;
            case "q":
              dsoObject.setQ(argKey);
              break;
            case "p_con":
              dsoObject.setP_con(argKey);
              break;
            case "p_max":
              dsoObject.setP_max(argKey);
              break;
            case "p_balance":
              dsoObject.setP_balance(argKey);
              break;
            case "dmj":
              dsoObject.setDmj(argKey);
              break;
            case "smi":
              dsoObject.setSmi(argKey);
              break;
            case "k":
              dsoObject.setK(argKey);
              break;
            case "si":
              dsoObject.setSi(argKey);
              break;
            case "dj":
              dsoObject.setDj(argKey);
              break;
            case "p_t":
              dsoObject.setP_t(argKey);
              break;
            case "delta_t":
              dsoObject.setDelta_t(argKey);
              break;
            case "change":
              dsoObject.setChange(argKey);
              break;
            case "timestampd":
              dsoObject.setTimestampD(argKey);
              break;
            case "begindated":
              dsoObject.setBeginDateD(argKey);
              break;
            case "enddated":
              dsoObject.setEndDateD(argKey);
              break;
          }
        }
      }
      String dsoName = "dso";
      assetSerialized = new Genson().serialize(dsoObject);
      System.out.println(dsoObject);
      stub.putStringState(dsoName, assetSerialized);
      return dsoObject.toString();
    }
    return null;
  }

  private String getProsumerAsset(ProsumerData assetObject, String propName) {
    if (assetObject == null) {
      return null;
    }
    String prop = propName.toLowerCase();
    switch (prop) {
      case "statusp":
        return assetObject.getStatusP();
      case "txaddrp":
        return assetObject.getTxAddrP();
      case "amountp":
        return assetObject.getAmountP();
      case "balancesp":
        return assetObject.getBalancesP();
      case "e_injected":
        return assetObject.getE_injected();
      case "i_p":
        return assetObject.getI_p();
      case "startdatep":
        return assetObject.getStartDateP();
      case "enddatep":
        return assetObject.getEndDateP();
      case "opi_ownership_structure":
        return assetObject.getOpi_ownership_structure();
      case "smi_matched_amount":
        return assetObject.getSmi_matched_amount();
    }
    return null;
  }

  private String getConsumerAsset(ConsumerData consumerObject, String propName) {
    if (consumerObject == null) {
      return null;
    }
    String prop = propName.toLowerCase();
    switch (prop) {
      case "statusc":
        return consumerObject.getStatusC();
      case "txaddrc":
        return consumerObject.getTxAddrC();
      case "amountc":
        return consumerObject.getAmountC();
      case "balancesc":
        consumerObject.getBalancesC();
      case "d_demand_to_buy_t":
        return consumerObject.getD_demand_to_buy_t();
      case "i_c":
        return consumerObject.getI_c();
      case "startdatec":
        return consumerObject.getStartDateC();
      case "enddatec":
        return consumerObject.getEndDateC();
      case "ocj_ownership_structure":
        return consumerObject.getOcj_ownership_structure();
      case "dmj_matched_amount":
        return consumerObject.getDmj_matched_amount();
    }
    return null;
  }

  private String getDSOAsset(DSOData dsoObject, String propName) {
    if (dsoObject == null) {
      return null;
    }
    String prop = propName.toLowerCase();
    switch (prop) {
      case "es_t":
        return dsoObject.getES_t();
      case "txaddrd":
        return dsoObject.getTxAddrD();
      case "ed_t":
        return dsoObject.getED_t();
      case "r_t":
        return dsoObject.getR_t();
      case "d_t":
        return dsoObject.getD_t();
      case "q":
        return dsoObject.getQ();
      case "p_con":
        return dsoObject.getP_con();
      case "p_balance":
        return dsoObject.getP_balance();
      case "dmj":
        return dsoObject.getDmj();
      case "smi":
        return dsoObject.getSmi();
      case "k":
        return dsoObject.getK();
      case "si":
        return dsoObject.getSi();
      case "dj":
        return dsoObject.getDj();
      case "p_t":
        return dsoObject.getP_t();
      case "delta_t":
        return dsoObject.getDelta_t();
      case "change":
        return dsoObject.getChange();
      case "timestampd":
        return dsoObject.getTimestampD();
      case "begindated":
        return dsoObject.getBeginDateD();
      case "enddated":
        return dsoObject.getEndDateD();
      case "p_max":
        return dsoObject.getP_max();
    }
    return null;
  }









  /**
   * sendTx
   */
  @Transaction
  public String sendTx(Context ctx, String consumer, String state, String smcAddr, String Smip_t, String timestamp, String i, String name, String Dj_t, String Dmj, String Pmax, String p_t, String num, String channelName) {
    ChaincodeStub stub = ctx.getStub();
    ArrayList<String> argss = new ArrayList<>();
    argss.add(consumer);
    argss.add(state);
    argss.add(smcAddr);
    argss.add(Smip_t);
    argss.add(timestamp);
    argss.add(i);
    argss.add(name);
    argss.add(Dj_t);
    argss.add(Dmj);
    argss.add(Pmax);
    argss.add(p_t);
    argss.add(num);
    Chaincode.Response request = null;
    Genson genson = new Genson();
    String stateN = "";
    String timestampN = "";
    String numN = "";
    String i_n = "";
    String startDateN;
    String endDateN;
    String pmaxN = "";
    stateN = state;
    timestampN = timestamp;
    i_n = i;
    numN = Dj_t;
    pmaxN = Pmax;

    // timestamp,i,Dj_t, Dmj,Pmax, p_t
    if (argss.get(0).equalsIgnoreCase("consumer")) {
      String value = "";
      String iN = "";
      iN = i;
      value = num;
      request = stub.invokeChaincodeWithStringArgs("consumer", "transfer", value, iN, channelName);
    } else {
      String iN;
      String value;
      value = Smip_t;
      iN = i;
      if (stateN == "transfer") {
        request = stub.invokeChaincodeWithStringArgs("prosumer", "transfer", value, iN, channelName);
      } else if (stateN == "trade") {
        request = stub.invokeChaincodeWithStringArgs("prosumer", "transfer", value, iN, channelName);
      }
    }
    return request.getStringPayload();
  }










  /**
   * calculate_balances
   */
  @Transaction
  public String calculate_balances(Context ctx, String p, String timestamp, String startDate, String endDate, String channelName) {
    ChaincodeStub stub = ctx.getStub();
    ArrayList<String> argss = new ArrayList<>();
    argss.add(p);
    argss.add(timestamp);
    argss.add(startDate);
    argss.add(endDate);
    Chaincode.Response request = null;
    Genson genson = new Genson();
    request = stub.invokeChaincodeWithStringArgs("smc", "get_registered_prosumers", channelName);
    String prosString = request.getStringPayload();
    if (prosString == null) {
      System.out.println("No registered prosumer");
      return null;
    }

    List<ProsumerData> pros = genson.deserialize(prosString, new GenericType<List<ProsumerData>>() {});
    Map<Long, Double> sS = new HashMap<Long, Double>();
    Long ts = 0L;
    Double tnum = 0.0;
    Long startDateN = 0L;
    Long endDateN = 0L;
    Double pN = 0.0;
    pN = Double.valueOf(p);
    ts = Long.valueOf(timestamp);
    startDateN = Long.valueOf(startDate);
    endDateN = Long.valueOf(endDate);
    // 
    String num = "0";
    for (ProsumerData pro : pros) {
      if (startDateN >= Long.valueOf(pro.getTimestampP()) && endDateN <= Long.valueOf(pro.getTimestampP())) {
        pro.setBalancesP(String.valueOf(Double.valueOf(pro.getBalancesP()) + Double.valueOf(pro.getSmi()) * Double.valueOf(pN)));
        pro.setReceived_balance(String.valueOf(Double.valueOf(pro.getSmi()) * Double.valueOf(pN)));
      }
      stub.invokeChaincodeWithStringArgs("prosumer", "transfer", pro.getI_p(), String.valueOf(Double.valueOf(pro.getSmi()) * Double.valueOf(pN)), channelName);
      String OpiString = pro.getOpi_ownership_structure();
      List<EnergyOwnership> Opi = genson.deserialize(OpiString, new GenericType<List<EnergyOwnership>>() {});
      for (EnergyOwnership op : Opi) {
        if (Long.valueOf(op.getTimestamp()) == ts && op.getState().equalsIgnoreCase("match") && Double.valueOf(op.getAmount()) == Double.valueOf(pro.getSmi())) {
          Opi.remove(op);
        }
      }
      String assetSerial = genson.serialize(Opi);
      pro.setOpi_ownership_structure(assetSerial);
    }
    String assetSerialized = genson.serialize(pros);
    stub.invokeChaincodeWithStringArgs("smc", "set_registered_prosumers", assetSerialized, channelName);
    Double pmax = Double.valueOf(stub.getStringState("pmax"));
    request = stub.invokeChaincodeWithStringArgs("smc", "get_registered_consumers", channelName);
    String consString = request.getStringPayload();
    if (consString == null) {
      System.out.println("No registered consumers");
      return null;
    }
    List<ConsumerData> cons = genson.deserialize(consString, new GenericType<List<ConsumerData>>() {});
    for (ConsumerData con : cons) {
      Map<String, String> djt = genson.deserialize(con.getDj_t(), new GenericType<Map<String, String>>() {});
      if (startDateN >= Long.valueOf(con.getTimestampC()) && endDateN <= Long.valueOf(con.getTimestampC())) {
        con.setBalancesC(String.valueOf(Double.valueOf(con.getBalancesC()) + (Double.valueOf(djt.get(ts.toString()))) * Double.valueOf(pmax) - Double.valueOf(con.getDmj()) * Double.valueOf(pN)));
        con.setReceived_balance(String.valueOf((Double.valueOf(djt.get(ts.toString()))) * Double.valueOf(pmax) - Double.valueOf(con.getDmj()) * Double.valueOf(pN)));
      }
      stub.invokeChaincodeWithStringArgs("consumer", "transfer", con.getI_c(), String.valueOf(Double.valueOf(con.getBalancesC()) + (Double.valueOf(djt.get(ts.toString()))) * Double.valueOf(pmax) - Double.valueOf(con.getDmj()) * Double.valueOf(pN)), channelName);
      String OciString = con.getOcj_ownership_structure();
      List<EnergyOwnership> Oci = genson.deserialize(OciString, new GenericType<List<EnergyOwnership>>() {});
      for (EnergyOwnership oc : Oci) {
        if (Long.valueOf(oc.getTimestamp()) == ts && oc.getState().equalsIgnoreCase("match") && Double.valueOf(oc.getAmount()) == Double.valueOf(con.getDmj())) {
          Oci.remove(oc);
        }
      }
      EnergyOwnership ocj = new EnergyOwnership(con.getTxAddrC(), con.getDmj(), "purchased", String.valueOf(ts));
      Oci.add(ocj);
      String assetSerial = genson.serialize(Oci);
      con.setOcj_ownership_structure(assetSerial);
    }
    assetSerialized = genson.serialize(cons);
    stub.invokeChaincodeWithStringArgs("smc", "set_registered_consumers", assetSerialized, channelName);
    return "true";
  }
  /**
   * order_elements smc
   */
  @Transaction
  public String order_elements(Context ctx, String timestamp, String channelName) {
    // order elements
    ChaincodeStub stub = ctx.getStub();
    ArrayList<String> argss = new ArrayList<>();
    argss.add(timestamp);
    Chaincode.Response request = null;
    Genson genson = new Genson();
    request = stub.invokeChaincodeWithStringArgs("smc", "get_registered_prosumers", channelName);
    String prosString = request.getStringPayload();
    if (prosString == null) {
      System.out.println("No registered prosumers");
      return null;
    }
    List<ProsumerData> pros = genson.deserialize(prosString, new GenericType<List<ProsumerData>>() {});
    Long ts = 0L;
    ts = Long.valueOf(timestamp);
    String num = "0";
    for (ProsumerData pro : pros) {
      String OpiString = pro.getOpi_ownership_structure();
      List<EnergyOwnership> Opi = genson.deserialize(OpiString, new GenericType<List<EnergyOwnership>>() {});
      for (int i = Opi.size() - 1; i > 1; i--, i--) {
        if (Opi.get(i).getState().equalsIgnoreCase("injected")) {
          Opi.get(1).setAmount(Opi.get(1).getAmount() + Opi.get(i).getAmount());
          Opi.get(1).setTimestamp(String.valueOf(new Date().getTime()));
          Opi.remove(i);
        }
      }
      pro.setS_intent_to_sell_t(Opi.get(1).getAmount());
      /*
         ExpressionStatement

      */

      String assetSerial = genson.serialize(Opi);
      pro.setOpi_ownership_structure(assetSerial);
    }
    String assetSerialized = genson.serialize(pros);
    stub.invokeChaincodeWithStringArgs("smc", "set_registered_prosumers", assetSerialized, channelName);
    return "true";
  }
  /**
   * delete smc
   */
  @Transaction
  public String delete(Context ctx, String name, String timestamp, String value, String state, String ij, String channelName) {
    ChaincodeStub stub = ctx.getStub();
    ArrayList<String> argss = new ArrayList<>();
    argss.add(name);
    argss.add(timestamp);
    argss.add(value);
    argss.add(state);
    argss.add(ij);
    Chaincode.Response request = null;
    Long tsN = 0L;
    Double valueN = 0.0;
    String nameN = "";
    String stateN = "";
    Integer ijN = 0;
    Genson genson = new Genson();
    nameN = String.valueOf(name);
    tsN = Long.valueOf(timestamp);
    valueN = Double.valueOf(value);
    stateN = String.valueOf(state);
    ijN = Integer.valueOf(ij);

    if (nameN.equalsIgnoreCase("prosumer")) {
      request = stub.invokeChaincodeWithStringArgs("smc", "get_registered_prosumers", channelName);
      String prosString = request.getStringPayload();
      if (prosString == null) {
        System.out.println("No registered prosumers");
        return null;
      }

      List<ProsumerData> pros = genson.deserialize(prosString, new GenericType<List<ProsumerData>>() {});
      String OpiString = pros.get(ijN).getOpi_ownership_structure();
      List<EnergyOwnership> Opi = genson.deserialize(OpiString, new GenericType<List<EnergyOwnership>>() {});
      for (EnergyOwnership op : Opi) {
        if (Long.valueOf(op.getTimestamp()) == tsN && op.getState().equalsIgnoreCase(stateN) && Double.valueOf(op.getAmount()) == valueN) {
          Opi.remove(op);
        }
      }
      String assetSerial = genson.serialize(Opi);
      pros.get(ijN).setOpi_ownership_structure(assetSerial);
      String assetSerialized = genson.serialize(pros);
      stub.invokeChaincodeWithStringArgs("smc", "set_registered_prosumers", assetSerialized, channelName);
    } else if (nameN.equalsIgnoreCase("consumer")) {
      request = stub.invokeChaincodeWithStringArgs("smc", "get_registered_consumers", channelName);
      String consString = request.getStringPayload();
      if (consString == null) {
        System.out.println("No registered consumers");
        return null;
      }
      List<ConsumerData> cons = genson.deserialize(consString, new GenericType<List<ConsumerData>>() {});
      String OciString = cons.get(ijN).getOcj_ownership_structure();
      List<EnergyOwnership> Oci = genson.deserialize(OciString, new GenericType<List<EnergyOwnership>>() {});
      for (EnergyOwnership oc : Oci) {
        if (Long.valueOf(oc.getTimestamp()) == tsN && oc.getState().equalsIgnoreCase(stateN) && Double.valueOf(oc.getAmount()) == valueN) {
          Oci.remove(oc);
        }
      }
      String assetSerial = genson.serialize(Oci);
      cons.get(ijN).setOcj_ownership_structure(assetSerial);
      String assetSerialized = genson.serialize(cons);
      stub.invokeChaincodeWithStringArgs("smc", "set_registered_consumers", assetSerialized, channelName);
    }
    return "done";
  }

  /**
   * event smc
   */
  @Transaction
  public String event(Context ctx, String name, String timestamp, String value, String state, String ij, String channelName) {
    // smc event
    ChaincodeStub stub = ctx.getStub();
    ArrayList<String> argss = new ArrayList<>();
    argss.add(name);
    argss.add(timestamp);
    argss.add(value);
    argss.add(state);
    argss.add(ij);
    Chaincode.Response request = null;
    Map<Long, Double> sS = new HashMap<Long, Double>();
    Long tsN = 0L;
    String valueN = "0.0";
    Integer ijN = 0;
    String stateN = "";
    Double pN = 0.0;
    String nameN = "";
    Genson genson = new Genson();
    nameN = String.valueOf(name);
    tsN = Long.valueOf(timestamp);
    valueN = value;
    stateN = String.valueOf(state);
    ijN = Integer.valueOf(ij);
    if (nameN.equalsIgnoreCase("prosumer")) {
      request = stub.invokeChaincodeWithStringArgs("smc", "get_registered_prosumers", channelName);
      String prosString = request.getStringPayload();
      if (prosString == null) {
        System.out.println("No registered prosumers");
        return null;
      }
      List<ProsumerData> pros = genson.deserialize(prosString, new GenericType<List<ProsumerData>>() {});
      String OpiString = pros.get(ijN).getOpi_ownership_structure();
      List<EnergyOwnership> Opi = genson.deserialize(OpiString, new GenericType<List<EnergyOwnership>>() {});
      EnergyOwnership opi = new EnergyOwnership(pros.get(ijN).getTxAddrP(), valueN, stateN, String.valueOf(tsN));
      Opi.add(opi);
      String assetSerial = genson.serialize(Opi);
      pros.get(ijN).setOpi_ownership_structure(assetSerial);
      String assetSerialized = genson.serialize(pros);
      stub.invokeChaincodeWithStringArgs("smc", "set_registered_prosumers", assetSerialized, channelName);
    } else if (nameN.equalsIgnoreCase("consumer")) {
      request = stub.invokeChaincodeWithStringArgs("smc", "get_registered_consumers", channelName);
      String consString = request.getStringPayload();
      if (consString == null) {
        System.out.println("No registered consumers");
        return null;
      }
      List<ConsumerData> cons = genson.deserialize(consString, new GenericType<List<ConsumerData>>() {});
      String OcjString = cons.get(ijN).getOcj_ownership_structure();
      List<EnergyOwnership> Ocj = genson.deserialize(OcjString, new GenericType<List<EnergyOwnership>>() {});
      EnergyOwnership ocj = new EnergyOwnership(cons.get(ijN).getTxAddrC(), valueN, stateN, String.valueOf(tsN));
      Ocj.add(ocj);
      String assetSerial = genson.serialize(Ocj);
      cons.get(ijN).setOcj_ownership_structure(assetSerial);
      String assetSerialized = genson.serialize(cons);
      stub.invokeChaincodeWithStringArgs("smc", "set_registered_consumers", assetSerialized, channelName);
    }
    return "true";
  }
  /**
   * require smc
   */
  public String require(Context ctx, String addr, String channelName) {
    ChaincodeStub stub = ctx.getStub();
    ArrayList<String> argss = new ArrayList<>();
    argss.add(addr);
    String addrD = "0";
    addrD = addr;
    String smcString = stub.getStringState("smc");
    if (smcString == null) {
      System.out.println("No smc");
      return "false";
    }
    SmartContractData smc = new Genson().deserialize(smcString, SmartContractData.class);
    return String.valueOf(smc.getDsoaddr().equals(addrD));
  }
  /**
   * smc, registered
   */
  @Transaction
  public String register(Context ctx, String timestamp, String name, String ij, String channelName) {
    ChaincodeStub stub = ctx.getStub();
    ArrayList<String> argss = new ArrayList<>();
    argss.add(timestamp);
    argss.add(name);
    argss.add(ij);
    Chaincode.Response request = null;
    Long ts = 0L;
    Integer ijN = 0;
    String nameN = "";
    Genson genson = new Genson();
    ts = Long.valueOf(timestamp);
    nameN = String.valueOf(name);
    ijN = Integer.valueOf(ij);
    if (nameN.equalsIgnoreCase("prosumer")) {
      request = stub.invokeChaincodeWithStringArgs("smc", "valid_prosumers_get", channelName);
      String prosString = request.getStringPayload();
      if (prosString == null) {
        System.out.println("No asset");
        return null;
      }

      List<ProsumerData> pros = genson.deserialize(prosString, new GenericType<List<ProsumerData>>() {});
      request = stub.invokeChaincodeWithStringArgs("smc", "get_registered_prosumers", channelName);
      String regsString = request.getStringPayload();
      if (regsString == null) {
        System.out.println("No asset");
        return null;
      }
      List<ProsumerData> regs = genson.deserialize(regsString, new GenericType<List<ProsumerData>>() {});
      pros.get(ijN).setTimestampP(String.valueOf(ts));
      regs.add(pros.get(ijN));
      String assetSerialized = genson.serialize(regs);
      stub.invokeChaincodeWithStringArgs("smc", "set_registered_prosumers", assetSerialized, channelName);
    } else if (nameN.equalsIgnoreCase("consumer")) {
      request = stub.invokeChaincodeWithStringArgs("smc", "valid_consumers_get", channelName);
      String consString = request.getStringPayload();
      if (consString == null) {
        System.out.println("No asset");
        return null;
      }

      List<ConsumerData> cons = genson.deserialize(consString, new GenericType<List<ConsumerData>>() {});
      request = stub.invokeChaincodeWithStringArgs("smc", "get_registered_consumers", channelName);
      String regsString = request.getStringPayload();
      if (regsString == null) {
        System.out.println("No asset");
        return null;
      }
      List<ConsumerData> regs = genson.deserialize(regsString, new GenericType<List<ConsumerData>>() {});
      cons.get(ijN).setTimestampC(String.valueOf(ts));
      regs.add(cons.get(ijN));
      String assetSerialized = genson.serialize(regs);
      stub.invokeChaincodeWithStringArgs("smc", "set_registered_consumers", assetSerialized, channelName);
    }
    return "done";
  }
  /**
   * balances_consumer_set, smc
   */
  public String balances_consumer_set(Context ctx, String num, String i_c, String channelName) {
    // set_balances_consumer
    ChaincodeStub stub = ctx.getStub();
    ArrayList<String> argss = new ArrayList<>();
    argss.add(num);
    argss.add(i_c);
    String numN = "0";
    String i_cN = "0";
    numN = num;
    i_cN = i_c;
    String smcString = stub.getStringState("smc");
    if (smcString == null) {
      System.out.println("No smc");
      return null;
    }
    SmartContractData smc = new Genson().deserialize(smcString, SmartContractData.class);
    ArrayList<Double> balances = new Genson().deserialize(smc.getBalances(), new GenericType<ArrayList<Double>>() {});
    balances.set(Integer.valueOf(i_cN), Double.valueOf(numN) + Double.valueOf(balances.get(Integer.valueOf(i_cN))));
    smc.setBalances(new Genson().serialize(balances));
    stub.putStringState("smc", new Genson().serialize(smc));
    return "true";
  }

  /**
   * validate_prosumer, smc
   */
  @Transaction
  public String validate_prosumer(Context ctx, String startDate, String endDate, String timestamp, String pmax, String Si, String ij, String channelName) {
    ChaincodeStub stub = ctx.getStub();
    ArrayList<String> argss = new ArrayList<>();
    argss.add(startDate);
    argss.add(endDate);
    argss.add(timestamp);
    argss.add(pmax);
    argss.add(Si);
    argss.add(ij);
    Chaincode.Response request = null;
    Long ts = 0L;
    Integer ijN = 0;
    Double SiN = 0.0;
    Long startDateN = 0L;
    Long endDateN = 0L;
    startDateN = Long.valueOf(startDate);
    endDateN = Long.valueOf(endDate);
    ts = Long.valueOf(timestamp);
    ijN = Integer.valueOf(ij);
    boolean flag = false;
    request = stub.invokeChaincodeWithStringArgs("smc", "get_registered_prosumers", channelName);
    String regsString = request.getStringPayload();
    if (regsString == null) {
      System.out.println("No asset");
      return null;
    }
    List<ProsumerData> regs = new Genson().deserialize(regsString, new GenericType<List<ProsumerData>>() {});
    if (Double.valueOf(regs.get(ijN).getEi()) >= Double.valueOf(SiN) && ts >= startDateN && ts <= endDateN) {
      flag = true;
    }
    return String.valueOf(flag);
  }
  /**
   * pro_init, smc
   */
  @Transaction
  public String pro_init(Context ctx, String timestampP, String set_timestamp, String statusP, String set_status, String i_p, String channelName) {
    ChaincodeStub stub = ctx.getStub();
    ArrayList<String> argss = new ArrayList<>();
    argss.add(timestampP);
    argss.add(set_timestamp);
    argss.add(statusP);
    argss.add(set_status);
    argss.add(i_p);
    String assetI = "";
    assetI = i_p;
    Genson genson = new Genson();
    ArrayList<String> args = new ArrayList<String>();
    argss.remove(assetI);
    String smcString = stub.getStringState("smc");
    if (smcString == null) {
      System.out.println("No smc");
      return null;
    }
    SmartContractData smc = genson.deserialize(smcString, SmartContractData.class);
    String init_pros_string = smc.getInit_pros();
    ArrayList<ProsumerData> init_pros = genson.deserialize(init_pros_string, new GenericType<ArrayList<ProsumerData>>() {});
    String reg_pros_string = smc.getRegistered_prosumers();
    if (reg_pros_string == null) {
      System.out.println("No asset");
      return null;
    }
    ArrayList<ProsumerData> reg_pros = genson.deserialize(reg_pros_string, new GenericType<ArrayList<ProsumerData>>() {});
    reg_pros.add(init_pros.get(Integer.valueOf(assetI)));
    setAsset(stub, "prosumer", genson.serialize(init_pros.get(Integer.valueOf(assetI))), argss);
    reg_pros_string = genson.serialize(reg_pros);
    smc.setRegistered_prosumers(reg_pros_string);
    smcString = genson.serialize(smc);
    stub.putStringState("smc", smcString);
    return "done";
  }
  /**
   * con_init, smc
   */
  @Transaction
  public String con_init(Context ctx, String timestampC, String set_timestamp, String statusC, String set_status, String i_c, String channelName) {
    ChaincodeStub stub = ctx.getStub();
    ArrayList<String> argss = new ArrayList<>();
    argss.add(timestampC);
    argss.add(set_timestamp);
    argss.add(statusC);
    argss.add(set_status);
    argss.add(i_c);
    String assetI = "";
    assetI = i_c;
    Genson genson = new Genson();
    ArrayList<String> args = new ArrayList<String>();
    argss.remove(assetI);
    String smcString = stub.getStringState("smc");
    if (smcString == null) {
      System.out.println("No asset");
      return null;
    }
    SmartContractData smc = genson.deserialize(smcString, SmartContractData.class);
    String init_cons_string = smc.getInit_cons();
    ArrayList<ConsumerData> init_cons = genson.deserialize(init_cons_string, new GenericType<ArrayList<ConsumerData>>() {});
    String reg_cons_string = smc.getRegistered_consumers();
    if (reg_cons_string == null) {
      System.out.println("No asset");
      return null;
    }

    ArrayList<ConsumerData> reg_cons = genson.deserialize(reg_cons_string, new GenericType<ArrayList<ConsumerData>>() {});
    init_cons.get(Integer.valueOf(assetI)).setTimestampC(argss.get(2));
    reg_cons.add(init_cons.get(Integer.valueOf(assetI)));
    setAsset(stub, "consumer", genson.serialize(init_cons.get(Integer.valueOf(assetI))), argss);
    reg_cons_string = genson.serialize(reg_cons);
    smc.setRegistered_consumers(reg_cons_string);
    smcString = genson.serialize(smc);
    stub.putStringState("smc", smcString);
    return "true";
  }
  /**
   * get_registered_consumers
   */
  @Transaction
  public String get_registered_consumers(Context ctx, String channelName) {
    ChaincodeStub stub = ctx.getStub();
    String smcString = stub.getStringState("smc");
    if (smcString == null) {
      System.out.println("No asset");
      return null;
    }
    SmartContractData smc = new Genson().deserialize(smcString, SmartContractData.class);
    String reg_cons_string = smc.getRegistered_consumers();
    return reg_cons_string;
  }
  /**
   * get_registered_consumers_size
   */
  @Transaction
  public String get_registered_consumers_size(Context ctx, String channelName) {
    ChaincodeStub stub = ctx.getStub();
    String smcString = stub.getStringState("smc");
    if (smcString == null) {
      System.out.println("No asset");
      return null;
    }
    Genson genson = new Genson();
    SmartContractData smc = genson.deserialize(smcString, SmartContractData.class);
    String reg_cons_string = smc.getRegistered_consumers();
    ArrayList<ConsumerData> reg_cons = genson.deserialize(reg_cons_string, new GenericType<ArrayList<ConsumerData>>() {});
    return String.valueOf(reg_cons.size());
  }
  /**
   * get_registered_prosumers
   */
  @Transaction
  public String get_registered_prosumers(Context ctx, String channelName) {
    ChaincodeStub stub = ctx.getStub();
    String smcString = stub.getStringState("smc");
    if (smcString == null) {
      System.out.println("No asset");
      return null;
    }
    SmartContractData smc = new Genson().deserialize(smcString, SmartContractData.class);
    String reg_pros_string = smc.getRegistered_prosumers();
    return reg_pros_string;
  }
  /**
   * get_registered_prosumers_size
   */
  @Transaction
  public String get_registered_prosumers_size(Context ctx, String channelName) {
    ChaincodeStub stub = ctx.getStub();
    String smcString = stub.getStringState("smc");
    if (smcString == null) {
      System.out.println("No asset");
      return null;
    }
    Genson genson = new Genson();
    SmartContractData smc = genson.deserialize(smcString, SmartContractData.class);
    String reg_pros_string = smc.getRegistered_prosumers();
    ArrayList<ProsumerData> reg_pros = genson.deserialize(reg_pros_string, new GenericType<ArrayList<ProsumerData>>() {});
    return String.valueOf(reg_pros.size());
  }
  /**
   * get_valid_prosumers smc
   */
  @Transaction
  public String valid_prosumers_get(Context ctx, String channelName) {
    ChaincodeStub stub = ctx.getStub();
    String smcString = stub.getStringState("smc");
    if (smcString == null) {
      System.out.println("No asset");
      return null;
    }
    SmartContractData smc = new Genson().deserialize(smcString, SmartContractData.class);
    String val_pros_string = smc.getValid_prosumers();
    return val_pros_string;
  }

  /**
   * get_valid_consumers smc
   */
  @Transaction
  public String valid_consumers_get(Context ctx, String channelName) {
    ChaincodeStub stub = ctx.getStub();
    String smcString = stub.getStringState("smc");
    if (smcString == null) {
      System.out.println("No asset");
      return null;
    }
    SmartContractData smc = new Genson().deserialize(smcString, SmartContractData.class);
    String val_cons_string = smc.getValid_consumers();
    return val_cons_string;
  }





}
