package EnergyDSLExamples.a_model;

/*Generated by MPS */

import EnergyDSL.runtime.StateMachine;
import EnergyDSL.runtime.State;
import jetbrains.mps.internal.collections.runtime.MapSequence;

public class TestRegister extends StateMachine {
  public TestRegister() {
    super(new State());
    MapSequence.fromMap(states).put("initialize", startState);

    MapSequence.fromMap(states).put("initialize", new State());
    MapSequence.fromMap(states).put("registered", new State());


  }

}
