package EnergyDSLExamples.a_model;

/*Generated by MPS */

import org.hyperledger.fabric.contract.annotation.Contract;
import org.hyperledger.fabric.contract.annotation.Default;
import org.hyperledger.fabric.contract.ContractInterface;
import org.hyperledger.fabric.shim.ChaincodeStub;
import java.util.ArrayList;
import EnergyDSL.runtime.ProsumerData;
import com.owlike.genson.Genson;
import EnergyDSL.runtime.ConsumerData;
import EnergyDSL.runtime.DSOData;

@Contract(name = "MyContract")
@Default
public class Test implements ContractInterface {


  public static String setAsset(ChaincodeStub stub, String assetType, String assetString, ArrayList<String> argss) {
    String assetSerialized;
    if (assetString == null) {
      return null;
    }
    if (assetType.toLowerCase().contains("prosumer")) {
      ProsumerData assetObject = new Genson().deserialize(assetString, ProsumerData.class);
      String key;
      for (int i = 0; i < argss.size() - 1; i = i + 2) {
        String argKey = argss.get(i);
        String setKey = argss.get(i + 1).toLowerCase();
        if (setKey.startsWith("set_")) {
          key = setKey.substring(4);
          switch (key) {
            case "statusp":
              assetObject.setStatusP(argKey);
              break;
            case "txaddrp":
              assetObject.setTxAddrP(argKey);
              break;
            case "amountp":
              assetObject.setAmountP(argKey);
              break;
            case "balancesp":
              assetObject.setBalancesP(argKey);
              break;
            case "e_injected":
              assetObject.setE_injected(argKey);
              break;
            case "i_p":
              assetObject.setI_p(argKey);
              break;
            case "startdatep":
              assetObject.setStartDateP(argKey);
              break;
            case "enddatep":
              assetObject.setEndDateP(argKey);
              break;
            case "opi_ownership_structure":
              assetObject.setOpi_ownership_structure(argKey);
              break;
            case "smi_matched_amount":
              assetObject.setSmi_matched_amount(argKey);
              break;
          }
        }
      }
      String prosumerName = "prosumer_" + assetObject.getI_p();
      assetSerialized = new Genson().serialize(assetObject);
      stub.putStringState(prosumerName, assetSerialized);
      return assetSerialized;
    } else if (assetType.toLowerCase().contains("consumer")) {
      ConsumerData consumerObject = new Genson().deserialize(assetString, ConsumerData.class);
      String key;
      for (int i = 0; i < argss.size() - 1; i = i + 2) {
        String argKey = argss.get(i);
        String setKey = argss.get(i + 1).toLowerCase();
        if (setKey.startsWith("set_")) {
          key = setKey.substring(4);
          switch (key) {
            case "statusc":
              consumerObject.setStatusC(argKey);
              break;
            case "txaddrc":
              consumerObject.setTxAddrC(argKey);
              break;
            case "amountc":
              consumerObject.setAmountC(argKey);
              break;
            case "balancesc":
              consumerObject.setBalancesC(argKey);
              break;
            case "d_demand_to_buy_t":
              consumerObject.setD_demand_to_buy_t(argKey);
              break;
            case "i_c":
              consumerObject.setI_c(argKey);
              break;
            case "startdatec":
              consumerObject.setStartDateC(argKey);
              break;
            case "enddatec":
              consumerObject.setEndDateC(argKey);
              break;
            case "ocj_ownership_structure":
              consumerObject.setOcj_ownership_structure(argKey);
              break;
            case "dmj_matched_amount":
              consumerObject.setDmj_matched_amount(argKey);
              break;
            case "dmj":
              consumerObject.setDmj(argKey);
              break;
            case "dj_t":
              consumerObject.setDj_t(argKey);
              break;
          }
        }
      }
      String consumerName = "consumer_" + consumerObject.getI_c();
      assetSerialized = new Genson().serialize(consumerObject);
      stub.putStringState(consumerName, assetSerialized);
      return assetSerialized;

    } else if (assetType.contains("dso")) {
      DSOData dsoObject = new Genson().deserialize(assetString, DSOData.class);
      String key;
      for (int i = 0; i < argss.size() - 1; i = i + 2) {
        String argKey = argss.get(i);
        String setKey = argss.get(i + 1).toLowerCase();
        if (setKey.startsWith("set_")) {
          key = setKey.substring(4);
          switch (key) {
            case "es_t":
              dsoObject.setES_t(argKey);
              break;
            case "txaddrd":
              dsoObject.setTxAddrD(argKey);
              break;
            case "ed_t":
              dsoObject.setED_t(argKey);
              break;
            case "r_t":
              dsoObject.setR_t(argKey);
              break;
            case "d_t":
              dsoObject.setD_t(argKey);
              break;
            case "q":
              dsoObject.setQ(argKey);
              break;
            case "p_con":
              dsoObject.setP_con(argKey);
              break;
            case "p_max":
              dsoObject.setP_max(argKey);
              break;
            case "p_balance":
              dsoObject.setP_balance(argKey);
              break;
            case "dmj":
              dsoObject.setDmj(argKey);
              break;
            case "smi":
              dsoObject.setSmi(argKey);
              break;
            case "k":
              dsoObject.setK(argKey);
              break;
            case "si":
              dsoObject.setSi(argKey);
              break;
            case "dj":
              dsoObject.setDj(argKey);
              break;
            case "p_t":
              dsoObject.setP_t(argKey);
              break;
            case "delta_t":
              dsoObject.setDelta_t(argKey);
              break;
            case "change":
              dsoObject.setChange(argKey);
              break;
            case "timestampd":
              dsoObject.setTimestampD(argKey);
              break;
            case "begindated":
              dsoObject.setBeginDateD(argKey);
              break;
            case "enddated":
              dsoObject.setEndDateD(argKey);
              break;
          }
        }
      }
      String dsoName = "dso";
      assetSerialized = new Genson().serialize(dsoObject);
      System.out.println(dsoObject);
      stub.putStringState(dsoName, assetSerialized);
      return dsoObject.toString();
    }
    return null;
  }

  private String getProsumerAsset(ProsumerData assetObject, String propName) {
    if (assetObject == null) {
      return null;
    }
    String prop = propName.toLowerCase();
    switch (prop) {
      case "statusp":
        return assetObject.getStatusP();
      case "txaddrp":
        return assetObject.getTxAddrP();
      case "amountp":
        return assetObject.getAmountP();
      case "balancesp":
        return assetObject.getBalancesP();
      case "e_injected":
        return assetObject.getE_injected();
      case "i_p":
        return assetObject.getI_p();
      case "startdatep":
        return assetObject.getStartDateP();
      case "enddatep":
        return assetObject.getEndDateP();
      case "opi_ownership_structure":
        return assetObject.getOpi_ownership_structure();
      case "smi_matched_amount":
        return assetObject.getSmi_matched_amount();
    }
    return null;
  }

  private String getConsumerAsset(ConsumerData consumerObject, String propName) {
    if (consumerObject == null) {
      return null;
    }
    String prop = propName.toLowerCase();
    switch (prop) {
      case "statusc":
        return consumerObject.getStatusC();
      case "txaddrc":
        return consumerObject.getTxAddrC();
      case "amountc":
        return consumerObject.getAmountC();
      case "balancesc":
        consumerObject.getBalancesC();
      case "d_demand_to_buy_t":
        return consumerObject.getD_demand_to_buy_t();
      case "i_c":
        return consumerObject.getI_c();
      case "startdatec":
        return consumerObject.getStartDateC();
      case "enddatec":
        return consumerObject.getEndDateC();
      case "ocj_ownership_structure":
        return consumerObject.getOcj_ownership_structure();
      case "dmj_matched_amount":
        return consumerObject.getDmj_matched_amount();
    }
    return null;
  }

  private String getDSOAsset(DSOData dsoObject, String propName) {
    if (dsoObject == null) {
      return null;
    }
    String prop = propName.toLowerCase();
    switch (prop) {
      case "es_t":
        return dsoObject.getES_t();
      case "txaddrd":
        return dsoObject.getTxAddrD();
      case "ed_t":
        return dsoObject.getED_t();
      case "r_t":
        return dsoObject.getR_t();
      case "d_t":
        return dsoObject.getD_t();
      case "q":
        return dsoObject.getQ();
      case "p_con":
        return dsoObject.getP_con();
      case "p_balance":
        return dsoObject.getP_balance();
      case "dmj":
        return dsoObject.getDmj();
      case "smi":
        return dsoObject.getSmi();
      case "k":
        return dsoObject.getK();
      case "si":
        return dsoObject.getSi();
      case "dj":
        return dsoObject.getDj();
      case "p_t":
        return dsoObject.getP_t();
      case "delta_t":
        return dsoObject.getDelta_t();
      case "change":
        return dsoObject.getChange();
      case "timestampd":
        return dsoObject.getTimestampD();
      case "begindated":
        return dsoObject.getBeginDateD();
      case "enddated":
        return dsoObject.getEndDateD();
      case "p_max":
        return dsoObject.getP_max();
    }
    return null;
  }



























}
