package EnergyDSLModels.StateMachinesWithCore;

/*Generated by MPS */

import java.util.Comparator;
import java.util.Vector;
import java.util.Collections;
import jetbrains.mps.baseLanguage.closures.runtime._FunctionTypes;
import org.iets3.core.expr.genjava.base.rt.rt.AlternativesException;
import java.math.BigInteger;
import java.math.BigDecimal;
import java.math.RoundingMode;

public class Core {
  public enum User implements Comparator<User> {
    consumer("user consumer"),
    prosumer("user prosumer");

    private final String value;
    public static int order;

    User(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    public int compare(User a, User b) {
      int result = 0;
      return result;
    }

    public int indexOf() {
      Vector<User> eVector = new Vector<User>();
      for (User e : User.values()) {
        eVector.add(e);
      }
      Collections.sort(eVector, this);
      return eVector.indexOf(this);
    }


    public static User fromValue(String value) {
      for (User itDeclName : User.values()) {
        if (itDeclName.getValue().equals(value)) {
          return itDeclName;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }
  public enum State implements Comparator<State> {
    initial("initial state"),
    register("register state"),
    injected("injected state"),
    bidding("bidding state"),
    board("board state"),
    match("match state"),
    purchased("purchased state");

    private final String value;
    public static int order;

    State(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    public int compare(State a, State b) {
      int result = 0;
      return result;
    }

    public int indexOf() {
      Vector<State> eVector = new Vector<State>();
      for (State e : State.values()) {
        eVector.add(e);
      }
      Collections.sort(eVector, this);
      return eVector.indexOf(this);
    }


    public static State fromValue(String value) {
      for (State itDeclName : State.values()) {
        if (itDeclName.getValue().equals(value)) {
          return itDeclName;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }
  public enum SystemState implements Comparator<SystemState> {
    roundstart("Round start"),
    requestSell("Request sell"),
    requestBuy("Request Buy"),
    inject("Inject"),
    transfer("Transfer"),
    matching("Matching"),
    trade("Trading"),
    register("Register");

    private final String value;
    public static int order;

    SystemState(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    public int compare(SystemState a, SystemState b) {
      int result = 0;
      return result;
    }

    public int indexOf() {
      Vector<SystemState> eVector = new Vector<SystemState>();
      for (SystemState e : SystemState.values()) {
        eVector.add(e);
      }
      Collections.sort(eVector, this);
      return eVector.indexOf(this);
    }


    public static SystemState fromValue(String value) {
      for (SystemState itDeclName : SystemState.values()) {
        if (itDeclName.getValue().equals(value)) {
          return itDeclName;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }





  public static SystemState get_system_state(final State state) {
    SystemState res = new _FunctionTypes._return_P0_E0<SystemState>() {
      public SystemState invoke() {
        SystemState system_state = new _FunctionTypes._return_P0_E0<SystemState>() {
          public SystemState invoke() {
            if (state == State.purchased) {
              return SystemState.transfer;
            } else if (state == State.board) {
              return SystemState.requestBuy;
            } else if (state == State.board) {
              return SystemState.requestSell;
            } else if (state == State.injected) {
              return SystemState.inject;
            } else if (state == State.match) {
              return SystemState.matching;
            } else if (state == State.register) {
              return SystemState.register;
            } else {
              throw new AlternativesException("The proposed alternative does not exist.");
            }
          }
        }.invoke();
        return system_state;
      }
    }.invoke();

    return res;
  }
  public static State get_state(final SystemState system_state) {
    State res = new _FunctionTypes._return_P0_E0<State>() {
      public State invoke() {
        State state = new _FunctionTypes._return_P0_E0<State>() {
          public State invoke() {
            if (system_state == SystemState.roundstart) {
              return State.match;
            } else if (system_state == SystemState.transfer) {
              return State.purchased;
            } else if (system_state == SystemState.requestBuy) {
              return State.board;
            } else if (system_state == SystemState.requestSell) {
              return State.board;
            } else if (system_state == SystemState.inject) {
              return State.injected;
            } else if (system_state == SystemState.matching) {
              return State.match;
            } else if (system_state == SystemState.register) {
              return State.register;
            } else {
              throw new AlternativesException("The proposed alternative does not exist.");
            }
          }
        }.invoke();
        return state;
      }
    }.invoke();

    return res;
  }
  public static EnergyOwnership eoSet() {
    EnergyOwnership res = new _FunctionTypes._return_P0_E0<EnergyOwnership>() {
      public EnergyOwnership invoke() {
        EnergyOwnership eo = new EnergyOwnership(((Number) new BigInteger("0")), ((Number) new BigInteger("0")), State.initial.getValue(), ((Number) new BigInteger("1")), ((Number) new BigInteger("0")));
        return eo;
      }
    }.invoke();

    return res;
  }




  public static EnergyOwnership energy = new EnergyOwnership(((Number) new BigInteger("0")), ((Number) new BigInteger("0")), State.initial.getValue(), ((Number) new BigInteger("1")), ((Number) new BigInteger("0")));
  public static Number smcAddr = ((Number) new BigInteger("0"));
  public static Number startDate = ((Number) new BigInteger("0"));
  public static Number endDate = ((Number) new BigInteger("0"));
  public static Number Pmax = ((Number) (new BigDecimal("0.0").setScale(1, RoundingMode.DOWN)));
  public static EnergyOwnership ad = new EnergyOwnership(((Number) new BigInteger("0")), ((Number) new BigInteger("0")), State.register.getValue(), ((Number) new BigInteger("1")), ((Number) new BigInteger("0")));









}
