package EnergyDSLModels.StateMachinesWithCore;

/*Generated by MPS */

import EnergyDSL.runtime.Asset;
import java.lang.reflect.Field;
import com.owlike.genson.Genson;
import com.owlike.genson.GenericType;
import java.util.Map;
import java.util.HashMap;
import org.json.JSONObject;
import java.util.Objects;

/**
 * Concept that is a type of Asset that implements IRecodedDeclaration
 */
public class DSODataSec extends Asset {
  public DSODataSec(Object... args) {
    try {
      Field[] fields = this.getClass().getDeclaredFields();
      for (int i = 1; i - 1 < args.length; i++) {
        fields[i - 1].set(this, args[i - 1]);
      }
    } catch (IllegalAccessException e) {
      e.printStackTrace();
    }
  }
  public String eSt;
  public String eDt;
  public String rt;
  public String dt;
  public String q;
  public String pcon;
  public String pBalance;
  public String k;
  public String si;
  public String dj;
  public String pt;
  public String pmax;
  public String getESt() {
    return eSt;
  }
  public String getEDt() {
    return eDt;
  }
  public String getRt() {
    return rt;
  }
  public String getDt() {
    return dt;
  }
  public String getQ() {
    return q;
  }
  public String getPcon() {
    return pcon;
  }
  public String getPBalance() {
    return pBalance;
  }
  public String getK() {
    return k;
  }
  public String getSi() {
    return si;
  }
  public String getDj() {
    return dj;
  }
  public String getPt() {
    return pt;
  }
  public String getPmax() {
    return pmax;
  }
  public void setESt(String eSt) {
    this.eSt = eSt;
  }
  public void setEDt(String eDt) {
    this.eDt = eDt;
  }
  public void setRt(String rt) {
    this.rt = rt;
  }
  public void setDt(String dt) {
    this.dt = dt;
  }
  public void setQ(String q) {
    this.q = q;
  }
  public void setPcon(String pcon) {
    this.pcon = pcon;
  }
  public void setPBalance(String pBalance) {
    this.pBalance = pBalance;
  }
  public void setK(String k) {
    this.k = k;
  }
  public void setSi(String si) {
    this.si = si;
  }
  public void setDj(String dj) {
    this.dj = dj;
  }
  public void setPt(String pt) {
    this.pt = pt;
  }
  public void setPmax(String pmax) {
    this.pmax = pmax;
  }

  public static DSODataSec deserialize(String jsonObject) {
    DSODataSec asset = new Genson().deserialize(jsonObject, new GenericType<DSODataSec>() {});
    return asset;
  }

  public String serialize() {
    Map<String, Object> map = new HashMap<>();
    map.put("eSt", eSt);
    map.put("eDt", eDt);
    map.put("rt", rt);
    map.put("dt", dt);
    map.put("q", q);
    map.put("pcon", pcon);
    map.put("pBalance", pBalance);
    map.put("k", k);
    map.put("si", si);
    map.put("dj", dj);
    map.put("pt", pt);
    map.put("pmax", pmax);

    return new JSONObject(map).toString();
  }
  public String toString() {
    Map<String, Object> map = new HashMap<>();
    map.put("eSt", eSt);
    map.put("eDt", eDt);
    map.put("rt", rt);
    map.put("dt", dt);
    map.put("q", q);
    map.put("pcon", pcon);
    map.put("pBalance", pBalance);
    map.put("k", k);
    map.put("si", si);
    map.put("dj", dj);
    map.put("pt", pt);
    map.put("pmax", pmax);

    return new JSONObject(map).toString();
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (!(o instanceof DSODataSec)) {
      return false;
    }
    DSODataSec rd = (DSODataSec) o;
    boolean result = true;
    result = result && Objects.equals(eSt, rd.eSt);
    result = result && Objects.equals(eDt, rd.eDt);
    result = result && Objects.equals(rt, rd.rt);
    result = result && Objects.equals(dt, rd.dt);
    result = result && Objects.equals(q, rd.q);
    result = result && Objects.equals(pcon, rd.pcon);
    result = result && Objects.equals(pBalance, rd.pBalance);
    result = result && Objects.equals(k, rd.k);
    result = result && Objects.equals(si, rd.si);
    result = result && Objects.equals(dj, rd.dj);
    result = result && Objects.equals(pt, rd.pt);
    result = result && Objects.equals(pmax, rd.pmax);
    return result;
  }
  @Override
  public int hashCode() {
    return Objects.hash(eSt, eDt, rt, dt, q, pcon, pBalance, k, si, dj, pt, pmax);
  }
}
