package EnergyDSLModels.StateMachinesWithCore;

/*Generated by MPS */

import EnergyDSL.runtime.StateMachine;
import jetbrains.mps.baseLanguage.closures.runtime._FunctionTypes;
import java.math.BigInteger;
import java.util.logging.Logger;
import EnergyDSL.runtime.State;
import jetbrains.mps.internal.collections.runtime.MapSequence;
import EnergyDSL.runtime.Transition;
import java.util.Map;

public class EnergyStateMachine extends StateMachine {
  public static Boolean changeWork(final Boolean v) {
    Boolean res = new _FunctionTypes._return_P0_E0<Boolean>() {
      public Boolean invoke() {
        return EnergyStateMachine.work = v;
      }
    }.invoke();

    return res;
  }
  public static Boolean test() {
    Boolean res = new _FunctionTypes._return_P0_E0<Boolean>() {
      public Boolean invoke() {
        return true;
      }
    }.invoke();

    return res;
  }

  public static Number deltaTime = ((Number) new BigInteger("0"));
  public static Boolean work = true;
  public static ProsumerData prosumer_0 = new ProsumerData("match", "10", "", "10", "10", "1634500577500", "0", "1000", "1634500577000", "1634500579000");
  public static ProsumerData prosumer_1 = new ProsumerData("match", "10", "", "10", "10", "1634500577500", "1", "900", "1634500577000", "1634500579000");
  public static ConsumerData consumer_2 = new ConsumerData("match", "10", "", "10", "10", "1634500577500", "2", "800", "1634500577000", "1634500578000");
  public static ConsumerData consumer_0 = new ConsumerData("match", "10", "", "10", "10", "1634500577500", "0", "1100", "1634500577000", "1634500578000");
  public static DSODataSec dsoData = new DSODataSec("12", "10", "10", "4", "5", "5", "1000", "30", "10", "10", "10", "1000");
  public static SmcData smcData = new SmcData("true", "true");

  private static final Logger logger = Logger.getLogger("StateMachine");

  public EnergyStateMachine() {
    super(new State());
    MapSequence.fromMap(states).put("initialize", startState);

    MapSequence.fromMap(states).put("initialize", new State("initialize"));
    MapSequence.fromMap(states).put("initialized", new State("initialized"));

    MapSequence.fromMap(states).get("initialize").addTransition("init", new Transitioninitinitialize(MapSequence.fromMap(states).get("initialized")));
    MapSequence.fromMap(states).get("initialized").addTransition("bid", new Transitionbidinitialized(MapSequence.fromMap(states).get("finished")));

  }
  public static class Transitioninitinitialize extends Transition {
    public Transitioninitinitialize(State state) {
      super(state);
    }
    @Override
    public State fireEvent(Map<String, Object> parameters, Object vr) {
      boolean conditionsFullfilled = true;


      if (!(EnergyStateMachine.work == true)) {
        conditionsFullfilled = false;
      }

      if (!(conditionsFullfilled)) {
        return null;
      }

      return targetState;
    }
  }
  public static class Transitionbidinitialized extends Transition {
    public Transitionbidinitialized(State state) {
      super(state);
    }
    @Override
    public State fireEvent(Map<String, Object> parameters, Object vr) {
      boolean conditionsFullfilled = true;



      if (!(conditionsFullfilled)) {
        return null;
      }

      return targetState;
    }
  }

}
