package EnergyDSLModels.StateMachinesWithCore;

/*Generated by MPS */

import EnergyDSL.runtime.Asset;
import java.lang.reflect.Field;
import com.owlike.genson.Genson;
import com.owlike.genson.GenericType;
import java.util.Map;
import java.util.HashMap;
import org.json.JSONObject;
import java.util.Objects;

/**
 * Concept that is a type of Asset that implements IRecodedDeclaration
 */
public class MyConsumer extends Asset {
  public MyConsumer(Object... args) {
    try {
      Field[] fields = this.getClass().getDeclaredFields();
      for (int i = 1; i - 1 < args.length; i++) {
        fields[i - 1].set(this, args[i - 1]);
      }
    } catch (IllegalAccessException e) {
      e.printStackTrace();
    }
  }
  public Number amount;
  public Number energy;
  public Number getAmount() {
    return amount;
  }
  public Number getEnergy() {
    return energy;
  }
  public void setAmount(Number amount) {
    this.amount = amount;
  }
  public void setEnergy(Number energy) {
    this.energy = energy;
  }

  public static MyConsumer deserialize(String jsonObject) {
    MyConsumer asset = new Genson().deserialize(jsonObject, new GenericType<MyConsumer>() {});
    return asset;
  }

  public String serialize() {
    Map<String, Object> map = new HashMap<>();
    map.put("amount", amount);
    map.put("energy", energy);

    return new JSONObject(map).toString();
  }
  public String toString() {
    Map<String, Object> map = new HashMap<>();
    map.put("amount", amount);
    map.put("energy", energy);

    return new JSONObject(map).toString();
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (!(o instanceof MyConsumer)) {
      return false;
    }
    MyConsumer rd = (MyConsumer) o;
    boolean result = true;
    result = result && Objects.equals(amount, rd.amount);
    result = result && Objects.equals(energy, rd.energy);
    return result;
  }
  @Override
  public int hashCode() {
    return Objects.hash(amount, energy);
  }
}
