package EnergyDSLModels.StateMachinesWithCore;

/*Generated by MPS */

import EnergyDSL.runtime.Asset;
import java.lang.reflect.Field;
import com.owlike.genson.Genson;
import com.owlike.genson.GenericType;
import java.util.Map;
import java.util.HashMap;
import org.json.JSONObject;
import java.util.Objects;

/**
 * Concept that is a type of Asset that implements IRecodedDeclaration
 */
public class ProsumerData extends Asset {
  public ProsumerData(Object... args) {
    try {
      Field[] fields = this.getClass().getDeclaredFields();
      for (int i = 1; i - 1 < args.length; i++) {
        fields[i - 1].set(this, args[i - 1]);
      }
    } catch (IllegalAccessException e) {
      e.printStackTrace();
    }
  }
  public String statusP;
  public String eInjected;
  public String opiOwnershipStructure;
  public String sIntentToSellT;
  public String misMatchedAmount;
  public String timestampP;
  public String ip;
  public String balances;
  public String startDate;
  public String endDateP;
  public String getStatusP() {
    return statusP;
  }
  public String getEInjected() {
    return eInjected;
  }
  public String getOpiOwnershipStructure() {
    return opiOwnershipStructure;
  }
  public String getSIntentToSellT() {
    return sIntentToSellT;
  }
  public String getMisMatchedAmount() {
    return misMatchedAmount;
  }
  public String getTimestampP() {
    return timestampP;
  }
  public String getIp() {
    return ip;
  }
  public String getBalances() {
    return balances;
  }
  public String getStartDate() {
    return startDate;
  }
  public String getEndDateP() {
    return endDateP;
  }
  public void setStatusP(String statusP) {
    this.statusP = statusP;
  }
  public void setEInjected(String eInjected) {
    this.eInjected = eInjected;
  }
  public void setOpiOwnershipStructure(String opiOwnershipStructure) {
    this.opiOwnershipStructure = opiOwnershipStructure;
  }
  public void setSIntentToSellT(String sIntentToSellT) {
    this.sIntentToSellT = sIntentToSellT;
  }
  public void setMisMatchedAmount(String misMatchedAmount) {
    this.misMatchedAmount = misMatchedAmount;
  }
  public void setTimestampP(String timestampP) {
    this.timestampP = timestampP;
  }
  public void setIp(String ip) {
    this.ip = ip;
  }
  public void setBalances(String balances) {
    this.balances = balances;
  }
  public void setStartDate(String startDate) {
    this.startDate = startDate;
  }
  public void setEndDateP(String endDateP) {
    this.endDateP = endDateP;
  }

  public static ProsumerData deserialize(String jsonObject) {
    ProsumerData asset = new Genson().deserialize(jsonObject, new GenericType<ProsumerData>() {});
    return asset;
  }

  public String serialize() {
    Map<String, Object> map = new HashMap<>();
    map.put("statusP", statusP);
    map.put("eInjected", eInjected);
    map.put("opiOwnershipStructure", opiOwnershipStructure);
    map.put("sIntentToSellT", sIntentToSellT);
    map.put("misMatchedAmount", misMatchedAmount);
    map.put("timestampP", timestampP);
    map.put("ip", ip);
    map.put("balances", balances);
    map.put("startDate", startDate);
    map.put("endDateP", endDateP);

    return new JSONObject(map).toString();
  }
  public String toString() {
    Map<String, Object> map = new HashMap<>();
    map.put("statusP", statusP);
    map.put("eInjected", eInjected);
    map.put("opiOwnershipStructure", opiOwnershipStructure);
    map.put("sIntentToSellT", sIntentToSellT);
    map.put("misMatchedAmount", misMatchedAmount);
    map.put("timestampP", timestampP);
    map.put("ip", ip);
    map.put("balances", balances);
    map.put("startDate", startDate);
    map.put("endDateP", endDateP);

    return new JSONObject(map).toString();
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (!(o instanceof ProsumerData)) {
      return false;
    }
    ProsumerData rd = (ProsumerData) o;
    boolean result = true;
    result = result && Objects.equals(statusP, rd.statusP);
    result = result && Objects.equals(eInjected, rd.eInjected);
    result = result && Objects.equals(opiOwnershipStructure, rd.opiOwnershipStructure);
    result = result && Objects.equals(sIntentToSellT, rd.sIntentToSellT);
    result = result && Objects.equals(misMatchedAmount, rd.misMatchedAmount);
    result = result && Objects.equals(timestampP, rd.timestampP);
    result = result && Objects.equals(ip, rd.ip);
    result = result && Objects.equals(balances, rd.balances);
    result = result && Objects.equals(startDate, rd.startDate);
    result = result && Objects.equals(endDateP, rd.endDateP);
    return result;
  }
  @Override
  public int hashCode() {
    return Objects.hash(statusP, eInjected, opiOwnershipStructure, sIntentToSellT, misMatchedAmount, timestampP, ip, balances, startDate, endDateP);
  }
}
