package EnergyDSL.runtime;

/*Generated by MPS */

import org.hyperledger.fabric.contract.ContractInterface;
import org.hyperledger.fabric.contract.Context;
import org.hyperledger.fabric.shim.ChaincodeStub;

@org.hyperledger.fabric.contract.annotation.Contract(name = "Consumer")
public class Contract implements ContractInterface {
  /*package*/ String currentState = "initial";
  public String init(Context ctx) {
    ChaincodeStub stub = ctx.getStub();
    stub.putStringState("statusC", "initialized");
    currentState = "initialized";
    return "Status set";
  }
}
