package EnergyDSL.runtime;

/*Generated by MPS */


public class DSOData {
  public String txAddrD;
  public String ES_t;
  public String ED_t;
  public String R_t;
  public String D_t;
  public String q;
  public String p_con;
  public String p_balance;
  public String Dmj;
  public String Smi;
  public String k;
  public String Si;
  public String Dj;
  public String p_t;
  public String delta_t;
  public String change;
  public String timestampD;
  public String beginDateD;
  public String endDateD;

  public void settxAddrD(String txAddrD) {
    this.txAddrD = txAddrD;
  }
  public void setES_t(String ES_t) {
    this.ES_t = ES_t;
  }
  public void setED_t(String ED_t) {
    this.ED_t = ED_t;
  }
  public void setR_t(String R_t) {
    this.R_t = R_t;
  }
  public void setD_t(String D_t) {
    this.D_t = D_t;
  }
  public void setq(String q) {
    this.q = q;
  }
  public void setp_con(String p_con) {
    this.p_con = p_con;
  }
  public void setp_balance(String p_balance) {
    this.p_balance = p_balance;
  }
  public void setDmj(String Dmj) {
    this.Dmj = Dmj;
  }
  public void setSmi(String Smi) {
    this.Smi = Smi;
  }
  public void setk(String k) {
    this.k = k;
  }
  public void setSi(String Si) {
    this.Si = Si;
  }
  public void setDj(String Dj) {
    this.Dj = Dj;
  }
  public void setp_t(String p_t) {
    this.p_t = p_t;
  }
  public void setdelta_t(String delta_t) {
    this.delta_t = delta_t;
  }
  public void setchange(String change) {
    this.change = change;
  }
  public void settimestampD(String timestampD) {
    this.timestampD = timestampD;
  }
  public void setbeginDateD(String beginDateD) {
    this.beginDateD = beginDateD;
  }
  public void setendDateD(String endDateD) {
    this.endDateD = endDateD;
  }








  public String gettxAddrD() {
    return txAddrD;
  }

  public String getES_t() {
    return ES_t;
  }
  public String getED_t() {
    return ED_t;
  }
  public String getR_t() {
    return R_t;
  }
  public String getD_t() {
    return D_t;
  }
  public String getq() {
    return q;
  }
  public String getp_con() {
    return p_con;
  }
  public String getp_balance() {
    return p_balance;
  }
  public String getDmj() {
    return Dmj;
  }
  public String getSmi() {
    return Smi;
  }
  public String getk() {
    return k;
  }
  public String getSi() {
    return Si;
  }
  public String getDj() {
    return Dj;
  }
  public String getp_t() {
    return p_t;
  }
  public String getdelta_t() {
    return delta_t;
  }
  public String getchange() {
    return change;
  }
  public String gettimestampD() {
    return timestampD;
  }
  public String getbeginDateD() {
    return beginDateD;
  }
  public String getendDateD() {
    return endDateD;
  }


}
