package EnergyDSL.runtime;

/*Generated by MPS */

import org.json.JSONObject;
import java.lang.reflect.Field;
import java.util.List;
import org.json.JSONArray;
import java.util.ArrayList;
import com.owlike.genson.Genson;
import com.owlike.genson.GenericType;

public class EnergyOwnershipSerializerDeserializer {
  public static JSONObject serialize(EnergyOwnership ownership) {
    JSONObject json = new JSONObject();
    try {
      Field[] fields = EnergyOwnership.class.getDeclaredFields();
    } catch (Exception e) {
      e.printStackTrace();
    }
    return json;
  }
  public static EnergyOwnership deserialize(String json) {
    try {
      EnergyOwnership ownership = new EnergyOwnership();
      return ownership;
    } catch (Exception e) {
    }
    return null;
  }
  public static String serializeArray(List<EnergyOwnership> ownerships) {
    String jsonArray = new JSONArray().toString();
    return jsonArray;
  }
  public static ArrayList<EnergyOwnership> deserializeArray(String jsonArray) {
    ArrayList<EnergyOwnership> deserilizedOwnerships = new Genson().deserialize(jsonArray, new GenericType<ArrayList<EnergyOwnership>>() {});
    return deserilizedOwnerships;
  }

  public static Asset deserializeAsset(String jsonObject) {
    Asset asset = new Genson().deserialize(jsonObject, new GenericType<Asset>() {});

    return asset;
  }
  public static ProsumerData deserializeProsumer(String jsonObject) {
    ProsumerData asset = new Genson().deserialize(jsonObject, new GenericType<ProsumerData>() {});

    return asset;
  }
  public static ConsumerData deserializeConsumer(String jsonObject) {
    ConsumerData asset = new Genson().deserialize(jsonObject, new GenericType<ConsumerData>() {});

    return asset;
  }

  public static DSOData deserializeDSO(String jsonObject) {
    DSOData asset = new Genson().deserialize(jsonObject, new GenericType<DSOData>() {});

    return asset;
  }



}
