package EnergyDSL.runtime;

/*Generated by MPS */

import java.math.BigInteger;

public class EnergyOwnership extends Asset {
  /*package*/ BigInteger address;

  /*package*/ Double amount;
  /*package*/ String state;
  /*package*/ Long timestamp;
  public EnergyOwnership(BigInteger address, Double amount, String state, Long ts) {
    this.address = address;
    this.amount = amount;
    this.state = state;
    this.timestamp = ts;
  }
  public EnergyOwnership() {
  }
}
