package EnergyDSL.runtime;

/*Generated by MPS */


public class ProsumerData {
  public String statusP = "initial";
  public String txAddrP;
  public String amountP;
  public String balancesP;
  public String E_injected;
  public String timestampP;
  public String i_p;
  public String startDateP;
  public String endDateP;
  public String Opi_ownership_structure;
  public String Smi_matched_amount;
  public String S_intent_to_sell_t;

  public void setstatusP(String statusP) {
    this.statusP = statusP;
  }
  public void settxAddrP(String txAddrP) {
    this.txAddrP = txAddrP;
  }
  public void setamountP(String amountP) {
    this.amountP = amountP;
  }
  public void setbalancesP(String balancesP) {
    this.balancesP = balancesP;
  }
  public void setE_injected(String E_injected) {
    this.E_injected = E_injected;
  }
  public void settimestampP(String timestampP) {
    this.timestampP = timestampP;
  }
  public void seti_p(String i_p) {
    this.i_p = i_p;
  }
  public void setstartDateP(String startDateP) {
    this.startDateP = startDateP;
  }
  public void setendDateP(String endDateP) {
    this.endDateP = endDateP;
  }
  public void setOpi_ownership_structure(String Opi_ownership_structure) {
    this.Opi_ownership_structure = Opi_ownership_structure;
  }
  public void setSmi_matched_amount(String Smi_matched_amount) {
    this.Smi_matched_amount = Smi_matched_amount;
  }





  public String getstatusP() {
    return statusP;
  }
  public String gettxAddrP() {
    return txAddrP;
  }
  public String getamountP() {
    return amountP;
  }
  public String getbalancesP() {
    return balancesP;
  }
  public String getE_injected() {
    return E_injected;
  }
  public String gettimestampP() {
    return timestampP;
  }
  public String geti_p() {
    return i_p;
  }
  public String getstartDateP() {
    return startDateP;
  }
  public String getendDateP() {
    return endDateP;
  }
  public String getOpi_ownership_structure() {
    return Opi_ownership_structure;
  }
  public String getSmi_matched_amount() {
    return Smi_matched_amount;
  }






}
