package EnergyDSL.runtime;

/*Generated by MPS */

import java.util.Map;
import jetbrains.mps.internal.collections.runtime.MapSequence;
import java.util.HashMap;

public abstract class StateMachine {
  protected State startState;
  protected static Object vr;
  protected static Object types;
  protected static void function() {
  }
  protected Map<String, State> states;

  public StateMachine(State startState) {
    this.startState = startState;
    this.states = MapSequence.fromMap(new HashMap<String, State>());
  }

  public State getStartState() {
    return this.startState;
  }
}
