package EnergyDSL.runtime;

/*Generated by MPS */

import org.hyperledger.fabric.contract.annotation.DataType;
import org.hyperledger.fabric.contract.annotation.Property;

@DataType
public class SmartContractData extends ContractAsset {
  @Property
  private String balances = "[]";
  @Property
  private String initPros = "[]";
  @Property
  private String initCons = "[]";
  @Property
  private String registeredProsumers = "[]";
  @Property
  private String registeredConsumers = "[]";
  @Property
  private String pmax = "12000";
  @Property
  private String dsoId = "0";

  public SmartContractData() {
  }

  public SmartContractData(String balances, String initPros, String initCons, String registeredProsumers, String registeredConsumers, String pmax, String dsoId) {
    this.balances = balances;
    this.initPros = initPros;
    this.initCons = initCons;
    this.registeredProsumers = registeredProsumers;
    this.registeredConsumers = registeredConsumers;
    this.pmax = pmax;
    this.dsoId = dsoId;
  }

  public String getBalances() {
    return this.balances;
  }

  public void setBalances(String balances) {
    this.balances = balances;
  }

  public String getInitPros() {
    return this.initPros;
  }

  public void setInitPros(String initPros) {
    this.initPros = initPros;
  }

  public String getInitCons() {
    return this.initCons;
  }

  public void setInitCons(String initCons) {
    this.initCons = initCons;
  }

  public String getRegisteredProsumers() {
    return this.registeredProsumers;
  }

  public void setRegisteredProsumers(String registeredProsumers) {
    this.registeredProsumers = registeredProsumers;
  }

  public String getRegisteredConsumers() {
    return this.registeredConsumers;
  }

  public void setRegisteredConsumers(String registeredConsumers) {
    this.registeredConsumers = registeredConsumers;
  }

  public String getPmax() {
    return this.pmax;
  }

  public void setPmax(String pmax) {
    this.pmax = pmax;
  }

  public String getDsoId() {
    return this.dsoId;
  }

  public void setDsoId(String dsoId) {
    this.dsoId = dsoId;
  }
  @Override
  public void updateProperty(String key, String value) {
  }
}
