package EnergyDSL.runtime;

/*Generated by MPS */

import java.util.Map;
import jetbrains.mps.internal.collections.runtime.MapSequence;
import java.util.HashMap;
import jetbrains.mps.internal.collections.runtime.IWhereFilter;
import jetbrains.mps.internal.collections.runtime.IMapping;

public abstract class StateMachine {
  protected State startState;
  protected static Object vr;
  protected static Object types;
  protected static void function() {
  }
  protected static Map<String, State> states;

  public StateMachine(State startState) {
    this.startState = startState;
    states = MapSequence.fromMap(new HashMap<String, State>());
  }

  public State getStartState() {
    return this.startState;
  }
  public State getStateValue(final String str) {
    return MapSequence.fromMap(states).findFirst(new IWhereFilter<IMapping<String, State>>() {
      public boolean accept(IMapping<String, State> it) {
        return it.key() == str;
      }
    }).value();
  }
  public String getStateKey(final String str) {
    return MapSequence.fromMap(states).findFirst(new IWhereFilter<IMapping<String, State>>() {
      public boolean accept(IMapping<String, State> it) {
        return it.key() == str;
      }
    }).key();
  }

}
