package EnergyDSL.runtime;

/*Generated by MPS */

import java.util.Map;
import jetbrains.mps.internal.collections.runtime.MapSequence;
import java.util.HashMap;

public class State {

  private Map<String, Transition> transitions;
  private String name;
  public State() {
    this.name = "init";
    transitions = MapSequence.fromMap(new HashMap<String, Transition>());
  }
  public State(String str) {
    this.name = str;
    transitions = MapSequence.fromMap(new HashMap<String, Transition>());
  }
  public String getName() {
    return name;
  }
  public void setName(String str) {
    this.name = str;
  }
  public String toString() {
    return name;
  }

  public void addTransition(String event, Transition transition) {
    MapSequence.fromMap(transitions).put(event, transition);
  }

  public State fireTransition(String event, Map<String, Object> parameters) {
    Transition transition = MapSequence.fromMap(transitions).get(event);
    if (transition == null) {
      System.out.println("⚠ No transition for event '" + event + "' in state '" + name + "'");
      return this;
    }
    State targetState = transition.fireEvent(parameters, StateMachine.vr);
    return (targetState != null ? targetState : this);

  }
}
