package EnergyDSL.typesystem;

/*Generated by MPS */

import java.util.Set;

public class AllowedNames {
  public static final Set<String> allowedCommonTransactionNames = Set.of("oneGet", "oneSet", "reset", "simpleGet", "getState", "addState", "setState", "setStateAdd", "setOwnershipStructureAdd", "simpleInit", "sendTx", "requireDso", "deleteAsset");

  public static final Set<String> allowedConsumerTransactionNames = Set.of("transfer", "consumerGet");

  public static final Set<String> allowedProsumerTransactionNames = Set.of("msg", "transfer", "prosumerGet");

  public static final Set<String> allowedDSOTransactionNames = Set.of("dsoSet", "dsoGet", "getDso", "createDso", "pricingDso", "isDso", "calculate");

  public static final Set<String> allowedSMCTransactionNames = Set.of("createSmc", "calculateBalances", "orderElements", "delete", "event", "require", "register", "balancesConsumerSet", "balancesProsumerSet", "validateProsumer", "validateConsumer", "proInit", "conInit", "getRegisteredConsumers", "getRegisteredConsumersSize", "getRegisteredProsumers", "getRegisteredProsumersSize", "validProsumersGet", "validConsumersGet", "setRegisteredProsumers", "setRegisteredConsumers", "registeredProsumerSet", "registeredConsumerSet", "smcGet", "smcSet");

  public static final Set<String> allowedEnergyTradingTransactionNames = Set.of("energyTrading", "register", "injectEnergy", "aggregation", "matching", "tradeEnergy");

}
