package EnergyDSL.typesystem;

/*Generated by MPS */

import jetbrains.mps.lang.typesystem.runtime.AbstractInferenceRule_Runtime;
import jetbrains.mps.lang.typesystem.runtime.InferenceRule_Runtime;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.typesystem.inference.TypeCheckingContext;
import jetbrains.mps.lang.typesystem.runtime.IsApplicableStatus;
import jetbrains.mps.typesystem.inference.EquationInfo;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import org.jetbrains.mps.openapi.language.SReferenceLink;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SConcept;

public class typeof_CoreConceptRef_InferenceRule extends AbstractInferenceRule_Runtime implements InferenceRule_Runtime {
  public typeof_CoreConceptRef_InferenceRule() {
  }
  public void applyRule(final SNode coreConceptRef, final TypeCheckingContext typeCheckingContext, IsApplicableStatus status) {
    {
      SNode _nodeToCheck_1029348928467 = coreConceptRef;
      EquationInfo _info_12389875345 = new EquationInfo(_nodeToCheck_1029348928467, null, "r:d923e83c-ce48-4a43-888a-e0b6b0fe8670(EnergyDSL.typesystem)", "2067117006973025229", 0, null);
      typeCheckingContext.createEquation((SNode) typeCheckingContext.typeOf(_nodeToCheck_1029348928467, "r:d923e83c-ce48-4a43-888a-e0b6b0fe8670(EnergyDSL.typesystem)", "2067117006973023283", true), (SNode) typeCheckingContext.typeOf(SLinkOperations.getTarget(coreConceptRef, LINKS.core$p4Xt), "r:d923e83c-ce48-4a43-888a-e0b6b0fe8670(EnergyDSL.typesystem)", "2067117006973025427", true), _info_12389875345);
    }
  }
  public SAbstractConcept getApplicableConcept() {
    return CONCEPTS.CoreConceptRef$Y_;
  }
  public IsApplicableStatus isApplicableAndPattern(SNode argument) {
    return new IsApplicableStatus(argument.getConcept().isSubConceptOf(getApplicableConcept()), null);
  }
  public boolean overrides() {
    return false;
  }

  private static final class LINKS {
    /*package*/ static final SReferenceLink core$p4Xt = MetaAdapterFactory.getReferenceLink(0xbde2436d1f60406fL, 0xa6ddb2e955d43687L, 0x1cafdff73dafa54cL, 0x1cafdff73dc0479aL, "core");
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept CoreConceptRef$Y_ = MetaAdapterFactory.getConcept(0xbde2436d1f60406fL, 0xa6ddb2e955d43687L, 0x1cafdff73dafa54cL, "EnergyDSL.structure.CoreConceptRef");
  }
}
