package EnergyDSL.typesystem;

/*Generated by MPS */

import jetbrains.mps.lang.typesystem.runtime.AbstractInferenceRule_Runtime;
import jetbrains.mps.lang.typesystem.runtime.InferenceRule_Runtime;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.typesystem.inference.TypeCheckingContext;
import jetbrains.mps.lang.typesystem.runtime.IsApplicableStatus;
import jetbrains.mps.typesystem.inference.EquationInfo;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import org.jetbrains.mps.openapi.language.SReferenceLink;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SConcept;

public class typeof_TransactionArgRef_InferenceRule extends AbstractInferenceRule_Runtime implements InferenceRule_Runtime {
  public typeof_TransactionArgRef_InferenceRule() {
  }
  public void applyRule(final SNode transactionArgRef, final TypeCheckingContext typeCheckingContext, IsApplicableStatus status) {
    {
      SNode _nodeToCheck_1029348928467 = transactionArgRef;
      EquationInfo _info_12389875345 = new EquationInfo(_nodeToCheck_1029348928467, null, "r:d923e83c-ce48-4a43-888a-e0b6b0fe8670(EnergyDSL.typesystem)", "7003027276159004074", 0, null);
      typeCheckingContext.createEquation((SNode) typeCheckingContext.typeOf(_nodeToCheck_1029348928467, "r:d923e83c-ce48-4a43-888a-e0b6b0fe8670(EnergyDSL.typesystem)", "7003027276159004081", true), (SNode) typeCheckingContext.typeOf(SLinkOperations.getTarget(transactionArgRef, LINKS.arg$bRzn), "r:d923e83c-ce48-4a43-888a-e0b6b0fe8670(EnergyDSL.typesystem)", "7003027276159004076", true), _info_12389875345);
    }
  }
  public SAbstractConcept getApplicableConcept() {
    return CONCEPTS.TransactionArgRef$uw;
  }
  public IsApplicableStatus isApplicableAndPattern(SNode argument) {
    return new IsApplicableStatus(argument.getConcept().isSubConceptOf(getApplicableConcept()), null);
  }
  public boolean overrides() {
    return false;
  }

  private static final class LINKS {
    /*package*/ static final SReferenceLink arg$bRzn = MetaAdapterFactory.getReferenceLink(0xbde2436d1f60406fL, 0xa6ddb2e955d43687L, 0x77666e84444ab17aL, 0x77666e84444ab960L, "arg");
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept TransactionArgRef$uw = MetaAdapterFactory.getConcept(0xbde2436d1f60406fL, 0xa6ddb2e955d43687L, 0x77666e84444ab17aL, "EnergyDSL.structure.TransactionArgRef");
  }
}
