package EnergyDSL.behavior;

/*Generated by MPS */

import jetbrains.mps.core.aspects.behaviour.BaseBehaviorAspectDescriptor;
import jetbrains.mps.core.aspects.behaviour.api.BHDescriptor;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.lang.smodel.ConceptSwitchIndex;
import jetbrains.mps.lang.smodel.ConceptSwitchIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;

public final class BehaviorAspectDescriptor extends BaseBehaviorAspectDescriptor {
  private final BHDescriptor myCoreConceptRef__BehaviorDescriptor = new CoreConceptRef__BehaviorDescriptor();
  private final BHDescriptor myContract__BehaviorDescriptor = new Contract__BehaviorDescriptor();
  private final BHDescriptor myGlobal__BehaviorDescriptor = new Global__BehaviorDescriptor();
  private final BHDescriptor myAsset__BehaviorDescriptor = new Asset__BehaviorDescriptor();
  private final BHDescriptor myCoreConcept__BehaviorDescriptor = new CoreConcept__BehaviorDescriptor();
  private final BHDescriptor myStateMachine__BehaviorDescriptor = new StateMachine__BehaviorDescriptor();
  private final BHDescriptor myTransaction__BehaviorDescriptor = new Transaction__BehaviorDescriptor();

  public BehaviorAspectDescriptor() {
  }

  @Nullable
  public BHDescriptor getDescriptor(@NotNull SAbstractConcept concept) {
    SAbstractConcept cncpt = concept;
    switch (conceptIndex.index(cncpt)) {
      case 0:
        return myAsset__BehaviorDescriptor;
      case 1:
        return myContract__BehaviorDescriptor;
      case 2:
        return myCoreConcept__BehaviorDescriptor;
      case 3:
        return myCoreConceptRef__BehaviorDescriptor;
      case 4:
        return myGlobal__BehaviorDescriptor;
      case 5:
        return myStateMachine__BehaviorDescriptor;
      case 6:
        return myTransaction__BehaviorDescriptor;
      default:
    }
    return null;
  }
  private static final ConceptSwitchIndex conceptIndex = new ConceptSwitchIndexBuilder().put(MetaIdFactory.conceptId(0xbde2436d1f60406fL, 0xa6ddb2e955d43687L, 0x3f05b6ba90233f03L), MetaIdFactory.conceptId(0xbde2436d1f60406fL, 0xa6ddb2e955d43687L, 0x221233f0603e998cL), MetaIdFactory.conceptId(0xbde2436d1f60406fL, 0xa6ddb2e955d43687L, 0x3f05b6ba905417efL), MetaIdFactory.conceptId(0xbde2436d1f60406fL, 0xa6ddb2e955d43687L, 0x1cafdff73dafa54cL), MetaIdFactory.conceptId(0xbde2436d1f60406fL, 0xa6ddb2e955d43687L, 0x2e1d6d32ecc79eedL), MetaIdFactory.conceptId(0xbde2436d1f60406fL, 0xa6ddb2e955d43687L, 0x3f05b6ba906cc3dcL), MetaIdFactory.conceptId(0xbde2436d1f60406fL, 0xa6ddb2e955d43687L, 0x77666e8443841ec8L)).seal();
}
