package EnergyDSL.behavior;

/*Generated by MPS */

import jetbrains.mps.core.aspects.behaviour.BaseBHDescriptor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import jetbrains.mps.core.aspects.behaviour.api.SMethod;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.core.aspects.behaviour.SMethodBuilder;
import jetbrains.mps.core.aspects.behaviour.SJavaCompoundTypeImpl;
import jetbrains.mps.core.aspects.behaviour.AccessPrivileges;
import java.util.List;
import java.util.Arrays;
import org.jetbrains.annotations.NotNull;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SConceptOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.internal.collections.runtime.Sequence;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SModelOperations;
import com.mbeddr.core.base.behavior.IVisibleElementProvider__BehaviorDescriptor;
import jetbrains.mps.core.aspects.behaviour.api.SConstructor;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.core.aspects.behaviour.api.BHMethodNotFoundException;
import org.jetbrains.mps.openapi.language.SContainmentLink;
import org.jetbrains.mps.openapi.language.SConcept;
import org.jetbrains.mps.openapi.language.SInterfaceConcept;

public final class StateMachine__BehaviorDescriptor extends BaseBHDescriptor {
  private static final SAbstractConcept CONCEPT = MetaAdapterFactory.getConcept(0xbde2436d1f60406fL, 0xa6ddb2e955d43687L, 0x3f05b6ba906cc3dcL, "EnergyDSL.structure.StateMachine");

  public static final SMethod<Iterable<SNode>> visibleContentsOfType_id6clJcrJXo2_ = new SMethodBuilder<Iterable<SNode>>(new SJavaCompoundTypeImpl((Class<Iterable<SNode>>) ((Class) Object.class))).name("visibleContentsOfType").modifiers(8, AccessPrivileges.PUBLIC).concept(CONCEPT).baseMethodId(7139820346881179813L).languageId(0xaa41d1b2bffa7eb1L, 0xd4280a54f6df4383L).build2(SMethodBuilder.createJavaParameter((Class<SNode>) ((Class) Object.class), ""));

  private static final List<SMethod<?>> BH_METHODS = Arrays.<SMethod<?>>asList(visibleContentsOfType_id6clJcrJXo2_);

  private static void ___init___(@NotNull SNode __thisNode__) {
  }

  @Deprecated
  /*package*/ static Iterable<SNode> visibleContentsOfType_id6clJcrJXo2_(@NotNull SNode __thisNode__, SNode targetConcept) {
    if (SConceptOperations.isSubConceptOf(SNodeOperations.asSConcept(targetConcept), CONCEPTS.State$av)) {
      return ListSequence.fromList(SLinkOperations.getChildren(__thisNode__, LINKS.states$N_Sj)).concat(Sequence.fromIterable(SLinkOperations.collectMany(SModelOperations.rootsIncludingImported(SNodeOperations.getModel(__thisNode__), CONCEPTS.StateMachine$av), LINKS.states$N_Sj))).concat(ListSequence.fromList(SModelOperations.rootsIncludingImported(SNodeOperations.getModel(__thisNode__), CONCEPTS.Asset$of))).concat(Sequence.fromIterable(SLinkOperations.collectMany(SModelOperations.rootsIncludingImported(SNodeOperations.getModel(__thisNode__), CONCEPTS.Global$eL), LINKS.variables$MXva))).concat(Sequence.fromIterable(SLinkOperations.collectMany(SModelOperations.rootsIncludingImported(SNodeOperations.getModel(__thisNode__), CONCEPTS.Global$eL), LINKS.types$MXIb)));
    }
    if (SConceptOperations.isSubConceptOf(SNodeOperations.asSConcept(targetConcept), CONCEPTS.Event$X4)) {
      return ListSequence.fromList(SLinkOperations.getChildren(__thisNode__, LINKS.events$Q69q)).concat(Sequence.fromIterable(SLinkOperations.collectMany(SModelOperations.rootsIncludingImported(SNodeOperations.getModel(__thisNode__), CONCEPTS.StateMachine$av), LINKS.events$Q69q))).concat(ListSequence.fromList(SModelOperations.rootsIncludingImported(SNodeOperations.getModel(__thisNode__), CONCEPTS.Asset$of))).concat(Sequence.fromIterable(SLinkOperations.collectMany(SModelOperations.rootsIncludingImported(SNodeOperations.getModel(__thisNode__), CONCEPTS.Global$eL), LINKS.variables$MXva))).concat(Sequence.fromIterable(SLinkOperations.collectMany(SModelOperations.rootsIncludingImported(SNodeOperations.getModel(__thisNode__), CONCEPTS.Global$eL), LINKS.types$MXIb)));
    }
    return IVisibleElementProvider__BehaviorDescriptor.visibleContentsOfType_id6clJcrJXo2_.invoke0(__thisNode__, CONCEPTS.Global$eL, targetConcept);
  }

  /*package*/ StateMachine__BehaviorDescriptor() {
  }

  @Override
  protected void initNode(@NotNull SNode node, @NotNull SConstructor constructor, @Nullable Object[] parameters) {
    ___init___(node);
  }

  @Override
  protected <T> T invokeSpecial0(@NotNull SNode node, @NotNull SMethod<T> method, @Nullable Object[] parameters) {
    int methodIndex = BH_METHODS.indexOf(method);
    if (methodIndex < 0) {
      throw new BHMethodNotFoundException(this, method);
    }
    switch (methodIndex) {
      case 0:
        return (T) ((Iterable<SNode>) visibleContentsOfType_id6clJcrJXo2_(node, (SNode) parameters[0]));
      default:
        throw new BHMethodNotFoundException(this, method);
    }
  }

  @Override
  protected <T> T invokeSpecial0(@NotNull SAbstractConcept concept, @NotNull SMethod<T> method, @Nullable Object[] parameters) {
    int methodIndex = BH_METHODS.indexOf(method);
    if (methodIndex < 0) {
      throw new BHMethodNotFoundException(this, method);
    }
    switch (methodIndex) {
      default:
        throw new BHMethodNotFoundException(this, method);
    }
  }

  @NotNull
  @Override
  public List<SMethod<?>> getDeclaredMethods() {
    return BH_METHODS;
  }

  @NotNull
  @Override
  public SAbstractConcept getConcept() {
    return CONCEPT;
  }

  private static final class LINKS {
    /*package*/ static final SContainmentLink states$N_Sj = MetaAdapterFactory.getContainmentLink(0xbde2436d1f60406fL, 0xa6ddb2e955d43687L, 0x3f05b6ba906cc3dcL, 0x221233f05fad4b4bL, "states");
    /*package*/ static final SContainmentLink variables$MXva = MetaAdapterFactory.getContainmentLink(0xbde2436d1f60406fL, 0xa6ddb2e955d43687L, 0x2e1d6d32ecc79eedL, 0x2e1d6d32ece5c45bL, "variables");
    /*package*/ static final SContainmentLink types$MXIb = MetaAdapterFactory.getContainmentLink(0xbde2436d1f60406fL, 0xa6ddb2e955d43687L, 0x2e1d6d32ecc79eedL, 0x2e1d6d32ece5c45cL, "types");
    /*package*/ static final SContainmentLink events$Q69q = MetaAdapterFactory.getContainmentLink(0xbde2436d1f60406fL, 0xa6ddb2e955d43687L, 0x3f05b6ba906cc3dcL, 0x3f05b6ba906cc8d9L, "events");
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept StateMachine$av = MetaAdapterFactory.getConcept(0xbde2436d1f60406fL, 0xa6ddb2e955d43687L, 0x3f05b6ba906cc3dcL, "EnergyDSL.structure.StateMachine");
    /*package*/ static final SConcept Asset$of = MetaAdapterFactory.getConcept(0xbde2436d1f60406fL, 0xa6ddb2e955d43687L, 0x3f05b6ba90233f03L, "EnergyDSL.structure.Asset");
    /*package*/ static final SInterfaceConcept Global$eL = MetaAdapterFactory.getInterfaceConcept(0xbde2436d1f60406fL, 0xa6ddb2e955d43687L, 0x2e1d6d32ecc79eedL, "EnergyDSL.structure.Global");
    /*package*/ static final SConcept State$av = MetaAdapterFactory.getConcept(0xbde2436d1f60406fL, 0xa6ddb2e955d43687L, 0x3f05b6ba906cbea9L, "EnergyDSL.structure.State");
    /*package*/ static final SConcept Event$X4 = MetaAdapterFactory.getConcept(0xbde2436d1f60406fL, 0xa6ddb2e955d43687L, 0x3f05b6ba906c8481L, "EnergyDSL.structure.Event");
  }
}
