package EnergyDSLExamples.a_model;

/*Generated by MPS */

import org.iets3.core.expr.simpleTypes.runtime.AH;
import jetbrains.mps.baseLanguage.closures.runtime._FunctionTypes;
import org.iets3.core.expr.genjava.base.rt.rt.AlternativesException;
import java.math.BigInteger;

public class Core {




  public static class Account {
    private Number address;
    private Number balance;

    public Account(Number address, Number balance) {
      this.address = address;
      this.balance = balance;
      evaluateContracts();
    }

    private Account() {
    }

    public Number getaddress() {
      return address;
    }
    public Number getbalance() {
      return balance;
    }

    public Account setaddress(Number address) {
      Account result = new Account();
      result.setValaddress(this.address);
      result.setValbalance(this.balance);
      result.setValaddress(address);
      return result;
    }
    public Account setbalance(Number balance) {
      Account result = new Account();
      result.setValaddress(this.address);
      result.setValbalance(this.balance);
      result.setValbalance(balance);
      return result;
    }

    public void setValaddress(Number address) {
      this.address = address;
    }
    public void setValbalance(Number balance) {
      this.balance = balance;
    }

    public void evaluateContracts() {
    }

    @Override
    public boolean equals(Object o) {
      if (!(o instanceof Account)) {
        return false;
      }
      Account rd = ((Account) o);

      if (!(AH.isEqual(this.address, rd.getaddress()))) {
        return false;
      }


      return true;
    }


    @Override
    public String toString() {
      String result = "";
      result = result.concat("address" + " : " + address.toString() + ";  ");
      result = result.concat("balance" + " : " + balance.toString() + ";  ");

      return result;
    }

  }
  public static class EnergyOwnership {
    private Number address;
    private Number amount;
    private State state;
    private Number timestamp;

    public EnergyOwnership(Number address, Number amount, State state, Number timestamp) {
      this.address = address;
      this.amount = amount;
      this.state = state;
      this.timestamp = timestamp;
      evaluateContracts();
    }

    private EnergyOwnership() {
    }

    public Number getaddress() {
      return address;
    }
    public Number getamount() {
      return amount;
    }
    public State getstate() {
      return state;
    }
    public Number gettimestamp() {
      return timestamp;
    }

    public EnergyOwnership setaddress(Number address) {
      EnergyOwnership result = new EnergyOwnership();
      result.setValaddress(this.address);
      result.setValamount(this.amount);
      result.setValstate(this.state);
      result.setValtimestamp(this.timestamp);
      result.setValaddress(address);
      return result;
    }
    public EnergyOwnership setamount(Number amount) {
      EnergyOwnership result = new EnergyOwnership();
      result.setValaddress(this.address);
      result.setValamount(this.amount);
      result.setValstate(this.state);
      result.setValtimestamp(this.timestamp);
      result.setValamount(amount);
      return result;
    }
    public EnergyOwnership setstate(State state) {
      EnergyOwnership result = new EnergyOwnership();
      result.setValaddress(this.address);
      result.setValamount(this.amount);
      result.setValstate(this.state);
      result.setValtimestamp(this.timestamp);
      result.setValstate(state);
      return result;
    }
    public EnergyOwnership settimestamp(Number timestamp) {
      EnergyOwnership result = new EnergyOwnership();
      result.setValaddress(this.address);
      result.setValamount(this.amount);
      result.setValstate(this.state);
      result.setValtimestamp(this.timestamp);
      result.setValtimestamp(timestamp);
      return result;
    }

    public void setValaddress(Number address) {
      this.address = address;
    }
    public void setValamount(Number amount) {
      this.amount = amount;
    }
    public void setValstate(State state) {
      this.state = state;
    }
    public void setValtimestamp(Number timestamp) {
      this.timestamp = timestamp;
    }

    public void evaluateContracts() {
    }

    @Override
    public boolean equals(Object o) {
      if (!(o instanceof EnergyOwnership)) {
        return false;
      }
      EnergyOwnership rd = ((EnergyOwnership) o);

      if (!(AH.isEqual(this.address, rd.getaddress()))) {
        return false;
      }


      return true;
    }


    @Override
    public String toString() {
      String result = "";
      result = result.concat("address" + " : " + address.toString() + ";  ");
      result = result.concat("amount" + " : " + amount.toString() + ";  ");
      result = result.concat("state" + " : " + state.toString() + ";  ");
      result = result.concat("timestamp" + " : " + timestamp.toString() + ";  ");

      return result;
    }

  }
  public enum System_state {
    roundstart("Round start"),
    request_sell("Request sell"),
    request_buy("Request Buy"),
    inject("Inject"),
    transfer("Transfer"),
    matching("Matching"),
    trade("Trading"),
    register("Register");

    private final String value;
    System_state(String value) {
      this.value = value;
    }
    public String getValue() {
      return this.value;
    }

    public static System_state fromValue(String value) {
      for (System_state it : System_state.values()) {
        if (it.value.equals(value)) {
          return it;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

  }
  public enum State {
    initial("initial state"),
    register("register state"),
    injected("injected state"),
    board("board state"),
    match("match state"),
    purchased("purchased state");

    private final String value;
    State(String value) {
      this.value = value;
    }
    public String getValue() {
      return this.value;
    }

    public static State fromValue(String value) {
      for (State it : State.values()) {
        if (it.value.equals(value)) {
          return it;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

  }
  public enum User {
    consumer("user consumer"),
    prosumer("user prosumer");

    private final String value;
    User(String value) {
      this.value = value;
    }
    public String getValue() {
      return this.value;
    }

    public static User fromValue(String value) {
      for (User it : User.values()) {
        if (it.value.equals(value)) {
          return it;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

  }
  public static System_state get_system_state(final State state) {
    System_state res = new _FunctionTypes._return_P0_E0<System_state>() {
      public System_state invoke() {
        System_state system_state = new _FunctionTypes._return_P0_E0<System_state>() {
          public System_state invoke() {
            if (state == State.purchased) {
              return System_state.transfer;
            } else if (state == State.board) {
              return System_state.request_buy;
            } else if (state == State.board) {
              return System_state.request_sell;
            } else if (state == State.injected) {
              return System_state.inject;
            } else if (state == State.match) {
              return System_state.matching;
            } else if (state == State.register) {
              return System_state.register;
            } else {
              throw new AlternativesException("The proposed alternative does not exist.");
            }
          }
        }.invoke();
        return system_state;
      }
    }.invoke();

    return res;
  }
  public static State get_state(final System_state system_state) {
    State res = new _FunctionTypes._return_P0_E0<State>() {
      public State invoke() {
        State state = new _FunctionTypes._return_P0_E0<State>() {
          public State invoke() {
            if (system_state == System_state.roundstart) {
              return State.match;
            } else if (system_state == System_state.transfer) {
              return State.purchased;
            } else if (system_state == System_state.request_buy) {
              return State.board;
            } else if (system_state == System_state.request_sell) {
              return State.board;
            } else if (system_state == System_state.inject) {
              return State.injected;
            } else if (system_state == System_state.matching) {
              return State.match;
            } else if (system_state == System_state.register) {
              return State.register;
            } else {
              throw new AlternativesException("The proposed alternative does not exist.");
            }
          }
        }.invoke();
        return state;
      }
    }.invoke();

    return res;
  }


  public static Energy energy = new Energy(((Number) new BigInteger("1")));
  public static Number smcAddr = ((Number) new BigInteger("0"));
  public static Number publickey = ((Number) new BigInteger("1234"));
  public static Number public_key_of_whisper = ((Number) new BigInteger("4321"));
  public static Number start_date = ((Number) new BigInteger("0"));
  public static Number end_date = ((Number) new BigInteger("0"));
  public static Number Pmax = ((Number) new BigInteger("1"));
  public static EnergyOwnership ad = new EnergyOwnership(((Number) new BigInteger("0")), ((Number) new BigInteger("0")), State.initial, ((Number) new BigInteger("1")));





}
