package EnergyDSLExamples.a_model;

/*Generated by MPS */

import org.hyperledger.fabric.contract.annotation.Contract;
import org.hyperledger.fabric.contract.annotation.Default;
import org.hyperledger.fabric.contract.ContractInterface;
import org.hyperledger.fabric.shim.ChaincodeStub;
import java.util.ArrayList;
import EnergyDSL.runtime.ProsumerData;
import com.owlike.genson.Genson;
import EnergyDSL.runtime.ConsumerData;
import EnergyDSL.runtime.DSOData;
import org.hyperledger.fabric.contract.annotation.Transaction;
import org.hyperledger.fabric.contract.Context;
import org.hyperledger.fabric.shim.Chaincode;
import com.owlike.genson.GenericType;
import jetbrains.mps.baseLanguage.closures.runtime._FunctionTypes;
import org.iets3.core.expr.simpleTypes.runtime.AH;
import java.math.BigInteger;
import EnergyDSL.runtime.SmartContractData;
import java.util.List;
import java.util.Map;
import java.util.HashMap;

@Contract(name = "MyContract")
@Default
public class DSO implements ContractInterface {

  public static String currentState = "initial";

  public static String setAsset(ChaincodeStub stub, String assetType, String assetString, ArrayList<String> argss) {
    String assetSerialized;
    if (assetString == null) {
      return null;
    }
    if (assetType.toLowerCase().contains("prosumer")) {
      ProsumerData assetObject = new Genson().deserialize(assetString, ProsumerData.class);
      String key;
      for (int i = 0; i < argss.size() - 1; i = i + 2) {
        String argKey = argss.get(i);
        String setKey = argss.get(i + 1).toLowerCase();
        if (setKey.startsWith("set_")) {
          key = setKey.substring(4);
          switch (key) {
            case "statusp":
              assetObject.setStatusP(argKey);
              break;
            case "txaddrp":
              assetObject.setTxAddrP(argKey);
              break;
            case "amountp":
              assetObject.setAmountP(argKey);
              break;
            case "balancesp":
              assetObject.setBalancesP(argKey);
              break;
            case "e_injected":
              assetObject.setE_injected(argKey);
              break;
            case "i_p":
              assetObject.setI_p(argKey);
              break;
            case "startdatep":
              assetObject.setStartDateP(argKey);
              break;
            case "enddatep":
              assetObject.setEndDateP(argKey);
              break;
            case "opi_ownership_structure":
              assetObject.setOpi_ownership_structure(argKey);
              break;
            case "smi_matched_amount":
              assetObject.setSmi_matched_amount(argKey);
              break;
          }
        }
      }
      String prosumerName = "prosumer_" + assetObject.getI_p();
      assetSerialized = new Genson().serialize(assetObject);
      stub.putStringState(prosumerName, assetSerialized);
      return assetSerialized;
    } else if (assetType.toLowerCase().contains("consumer")) {
      ConsumerData consumerObject = new Genson().deserialize(assetString, ConsumerData.class);
      String key;
      for (int i = 0; i < argss.size() - 1; i = i + 2) {
        String argKey = argss.get(i);
        String setKey = argss.get(i + 1).toLowerCase();
        if (setKey.startsWith("set_")) {
          key = setKey.substring(4);
          switch (key) {
            case "statusc":
              consumerObject.setStatusC(argKey);
              break;
            case "txaddrc":
              consumerObject.setTxAddrC(argKey);
              break;
            case "amountc":
              consumerObject.setAmountC(argKey);
              break;
            case "balancesc":
              consumerObject.setBalancesC(argKey);
              break;
            case "d_demand_to_buy_t":
              consumerObject.setD_demand_to_buy_t(argKey);
              break;
            case "i_c":
              consumerObject.setI_c(argKey);
              break;
            case "startdatec":
              consumerObject.setStartDateC(argKey);
              break;
            case "enddatec":
              consumerObject.setEndDateC(argKey);
              break;
            case "ocj_ownership_structure":
              consumerObject.setOcj_ownership_structure(argKey);
              break;
            case "dmj_matched_amount":
              consumerObject.setDmj_matched_amount(argKey);
              break;
            case "dmj":
              consumerObject.setDmj(argKey);
              break;
            case "dj_t":
              consumerObject.setDj_t(argKey);
              break;
          }
        }
      }
      String consumerName = "consumer_" + consumerObject.getI_c();
      assetSerialized = new Genson().serialize(consumerObject);
      stub.putStringState(consumerName, assetSerialized);
      return assetSerialized;

    } else if (assetType.contains("dso")) {
      DSOData dsoObject = new Genson().deserialize(assetString, DSOData.class);
      String key;
      for (int i = 0; i < argss.size() - 1; i = i + 2) {
        String argKey = argss.get(i);
        String setKey = argss.get(i + 1).toLowerCase();
        if (setKey.startsWith("set_")) {
          key = setKey.substring(4);
          switch (key) {
            case "es_t":
              dsoObject.setES_t(argKey);
              break;
            case "txaddrd":
              dsoObject.setTxAddrD(argKey);
              break;
            case "ed_t":
              dsoObject.setED_t(argKey);
              break;
            case "r_t":
              dsoObject.setR_t(argKey);
              break;
            case "d_t":
              dsoObject.setD_t(argKey);
              break;
            case "q":
              dsoObject.setQ(argKey);
              break;
            case "p_con":
              dsoObject.setP_con(argKey);
              break;
            case "p_max":
              dsoObject.setP_max(argKey);
              break;
            case "p_balance":
              dsoObject.setP_balance(argKey);
              break;
            case "dmj":
              dsoObject.setDmj(argKey);
              break;
            case "smi":
              dsoObject.setSmi(argKey);
              break;
            case "k":
              dsoObject.setK(argKey);
              break;
            case "si":
              dsoObject.setSi(argKey);
              break;
            case "dj":
              dsoObject.setDj(argKey);
              break;
            case "p_t":
              dsoObject.setP_t(argKey);
              break;
            case "delta_t":
              dsoObject.setDelta_t(argKey);
              break;
            case "change":
              dsoObject.setChange(argKey);
              break;
            case "timestampd":
              dsoObject.setTimestampD(argKey);
              break;
            case "begindated":
              dsoObject.setBeginDateD(argKey);
              break;
            case "enddated":
              dsoObject.setEndDateD(argKey);
              break;
          }
        }
      }
      String dsoName = "dso";
      assetSerialized = new Genson().serialize(dsoObject);
      System.out.println(dsoObject);
      stub.putStringState(dsoName, assetSerialized);
      return dsoObject.toString();
    }
    return null;
  }

  private String getProsumerAsset(ProsumerData assetObject, String propName) {
    if (assetObject == null) {
      return null;
    }
    String prop = propName.toLowerCase();
    switch (prop) {
      case "statusp":
        return assetObject.getStatusP();
      case "txaddrp":
        return assetObject.getTxAddrP();
      case "amountp":
        return assetObject.getAmountP();
      case "balancesp":
        return assetObject.getBalancesP();
      case "e_injected":
        return assetObject.getE_injected();
      case "i_p":
        return assetObject.getI_p();
      case "startdatep":
        return assetObject.getStartDateP();
      case "enddatep":
        return assetObject.getEndDateP();
      case "opi_ownership_structure":
        return assetObject.getOpi_ownership_structure();
      case "smi_matched_amount":
        return assetObject.getSmi_matched_amount();
    }
    return null;
  }

  private String getConsumerAsset(ConsumerData consumerObject, String propName) {
    if (consumerObject == null) {
      return null;
    }
    String prop = propName.toLowerCase();
    switch (prop) {
      case "statusc":
        return consumerObject.getStatusC();
      case "txaddrc":
        return consumerObject.getTxAddrC();
      case "amountc":
        return consumerObject.getAmountC();
      case "balancesc":
        consumerObject.getBalancesC();
      case "d_demand_to_buy_t":
        return consumerObject.getD_demand_to_buy_t();
      case "i_c":
        return consumerObject.getI_c();
      case "startdatec":
        return consumerObject.getStartDateC();
      case "enddatec":
        return consumerObject.getEndDateC();
      case "ocj_ownership_structure":
        return consumerObject.getOcj_ownership_structure();
      case "dmj_matched_amount":
        return consumerObject.getDmj_matched_amount();
    }
    return null;
  }

  private String getDSOAsset(DSOData dsoObject, String propName) {
    if (dsoObject == null) {
      return null;
    }
    String prop = propName.toLowerCase();
    switch (prop) {
      case "es_t":
        return dsoObject.getES_t();
      case "txaddrd":
        return dsoObject.getTxAddrD();
      case "ed_t":
        return dsoObject.getED_t();
      case "r_t":
        return dsoObject.getR_t();
      case "d_t":
        return dsoObject.getD_t();
      case "q":
        return dsoObject.getQ();
      case "p_con":
        return dsoObject.getP_con();
      case "p_balance":
        return dsoObject.getP_balance();
      case "dmj":
        return dsoObject.getDmj();
      case "smi":
        return dsoObject.getSmi();
      case "k":
        return dsoObject.getK();
      case "si":
        return dsoObject.getSi();
      case "dj":
        return dsoObject.getDj();
      case "p_t":
        return dsoObject.getP_t();
      case "delta_t":
        return dsoObject.getDelta_t();
      case "change":
        return dsoObject.getChange();
      case "timestampd":
        return dsoObject.getTimestampD();
      case "begindated":
        return dsoObject.getBeginDateD();
      case "enddated":
        return dsoObject.getEndDateD();
      case "p_max":
        return dsoObject.getP_max();
    }
    return null;
  }









  /**
   * sendTx
   */
  @Transaction
  public String sendTx(Context ctx, String state, String txAddrP, String txAddrC, String timetsamp, String startDate, String endDate, String Ei, String Smi, String Dmj, String Dj, String Si, String ij, String p_t, String prosumerj, String consumeri, String channelName) {
    ChaincodeStub stub = ctx.getStub();
    ArrayList<String> argss = new ArrayList<>();
    argss.add(state);
    argss.add(txAddrP);
    argss.add(txAddrC);
    argss.add(timetsamp);
    argss.add(startDate);
    argss.add(endDate);
    argss.add(Ei);
    argss.add(Smi);
    argss.add(Dmj);
    argss.add(Dj);
    argss.add(Si);
    argss.add(ij);
    argss.add(p_t);
    argss.add(prosumerj);
    argss.add(consumeri);
    Chaincode.Response request = null;
    Genson genson = new Genson();
    String stateN = "";
    String timestampN = "";
    String numN = "";
    String i_n = "";
    String startDateN;
    String endDateN;
    String pmaxN = "";
    stateN = state;
    startDateN = startDate;
    endDateN = endDate;
    i_n = ij;

    {
      /*
        <type> <var>;

      */


      String SmiN = "";
      String DmjN = "";
      String DjN = "";
      String EiN = "";
      String SiN = "";
      String ijN = "0";
      String system_stateN = "";
      String txAddrPiN = "";
      String txAddrCjN = "";
      String tsN = "";
      String pt = "";
      String start_date = "";
      String end_date = "";
      String prosumerNj = "";
      String consumerNi = "";
      system_stateN = state;
      txAddrPiN = txAddrP;
      txAddrCjN = txAddrC;
      start_date = startDate;
      end_date = endDate;
      EiN = Ei;
      SmiN = Smi;
      DmjN = Dmj;
      DjN = Dj;
      SiN = Si;
      ijN = ij;
      pt = p_t;
      prosumerNj = prosumerj;
      consumerNi = consumeri;

      String dsoString = stub.getStringState("dso");
      if (dsoString == null) {
        System.out.println("No asset");
        return null;
      }
      DSOData dso = new Genson().deserialize(dsoString, DSOData.class);
      if (dso == null) {
        System.out.println("No asset");
        return null;
      }
      String dsoAddress = dso.getTxAddrD();
      switch (system_stateN) {
        case "inject":
          request = stub.invokeChaincodeWithStringArgs("smc", "require", dsoAddress, channelName);

          boolean is_dso = Boolean.valueOf(request.getStringPayload());
          if (is_dso) {
            request = stub.invokeChaincodeWithStringArgs("smc", "event", "prosumer", tsN, EiN, "injected", ijN, channelName);
          }
          return "";
        case "roundstart":
          request = stub.invokeChaincodeWithStringArgs("smc", "order_elements", tsN, channelName);
          return request.getStringPayload();
        case "trade":
          request = stub.invokeChaincodeWithStringArgs("smc", "calculate_balances", pt, tsN, start_date, end_date, channelName);
          return "";
        case "matching":
          ArrayList<String> smiList = new Genson().deserialize(SmiN, new GenericType<ArrayList<String>>() {});
          ArrayList<String> djList = new Genson().deserialize(DjN, new GenericType<ArrayList<String>>() {});
          ArrayList<String> dmjList = new Genson().deserialize(DjN, new GenericType<ArrayList<String>>() {});
          ArrayList<String> EiList = new Genson().deserialize(EiN, new GenericType<ArrayList<String>>() {});
          ArrayList<String> SiList = new Genson().deserialize(SiN, new GenericType<ArrayList<String>>() {});
          ArrayList<String> txAddrCjNList = new Genson().deserialize(txAddrCjN, new GenericType<ArrayList<String>>() {});
          ArrayList<String> txAddrPiNList = new Genson().deserialize(txAddrPiN, new GenericType<ArrayList<String>>() {});
          request = stub.invokeChaincodeWithStringArgs("dso", "calculate", tsN, ijN, channelName);
          for (int ik = 0; ik < txAddrPiNList.size(); ik++) {
            request = stub.invokeChaincodeWithStringArgs("smc", "event", "prosumer", tsN, smiList.get(ik), "match", String.valueOf(ik), channelName);
            request = stub.invokeChaincodeWithStringArgs("smc", "delete", "prosumer", tsN, SiList.get(ik), "board", String.valueOf(ik), channelName);
            request = stub.invokeChaincodeWithStringArgs("smc", "event", "prosumer", tsN, String.valueOf(Double.valueOf(SiList.get(ik)) - Double.valueOf(smiList.get(ik))), "injected", String.valueOf(ik), channelName);
          }
          for (int j = 0; j < txAddrCjNList.size(); j++) {
            request = stub.invokeChaincodeWithStringArgs("smc", "event", "consumer", tsN, dmjList.get(j), "match", String.valueOf(j), channelName);
          }
          return "true";
        default:
          return "false";
      }
    }
  }

  /**
   * pricing, dso
   */
  @Transaction
  public String pricingByDSO(Context ctx, String channelName) {
    ChaincodeStub stub = ctx.getStub();
    String msg = "";
    String dsoString = stub.getStringState("dso");
    if (dsoString == null) {
      System.out.println("No dso");
      return null;
    }
    DSOData dso = new Genson().deserialize(dsoString, new GenericType<DSOData>() {});
    if (dso == null) {
      System.out.println("No asset");
      return null;
    }
    Double p_con = Double.valueOf(dso.getP_con());
    Double Ed_t = Double.valueOf(dso.getED_t());
    Double Es_t = Double.valueOf(dso.getES_t());
    Double k = Double.valueOf(dso.getK());
    Double p_balance = Double.valueOf(dso.getP_balance());
    Double p_t = ((2 / Math.PI) * p_con * Math.pow(Math.tan(Math.pow(Ed_t / Es_t, k)), -1) + p_balance);
    return String.valueOf(p_t);
  }




  /**
   * require_dso
   */
  public String require_dso(Context ctx, String addrTxDs, String channelName) {
    ChaincodeStub stub = ctx.getStub();
    Chaincode.Response request = null;
    request = stub.invokeChaincodeWithStringArgs("dso", "is_dso", addrTxDs, channelName);
    if (request.getStringPayload().equalsIgnoreCase("true")) {
      return "true";
    }
    return "false";
  }


  public static Number pricingByDSO(final Number ED_t, final Number ES_t, final Number k, Number e, final Number p_con, final Number p_balance) {
    Number res = new _FunctionTypes._return_P0_E0<Number>() {
      public Number invoke() {

        Number p_t = (AH.add(AH.mul(AH.mul(AH.div(((Number) new BigInteger("2")), Math.PI), p_con), Math.pow(((Double) ((Number) new BigInteger("-1"))), ((Double) Math.tan(Math.log(Math.pow(((Double) k), ((Double) AH.div(ED_t, ES_t)))))))), p_balance));
        return p_t;
      }
    }.invoke();

    return res;
  }

  /**
   * dso, is_dso
   */
  public Boolean is_dso(Context ctx, String addrTxDs, String channelName) {
    ChaincodeStub stub = ctx.getStub();
    ArrayList<String> argss = new ArrayList<>();
    argss.add(addrTxDs);
    String smcString = stub.getStringState("smc");
    if (smcString == null) {
      System.out.println("No smc");
      return null;
    }
    SmartContractData smc = new Genson().deserialize(smcString, new GenericType<SmartContractData>() {});
    if (smc.getDsoaddr() == argss.get(0)) {
      return true;
    }
    return false;
  }
  /**
   * dso, calculate
   */
  @Transaction
  public String calculate(Context ctx, String timestamp, String ij, String channelName) {
    ChaincodeStub stub = ctx.getStub();
    ArrayList<String> argss = new ArrayList<>();
    argss.add(timestamp);
    argss.add(ij);
    Chaincode.Response request = null;
    Genson genson = new Genson();
    request = stub.invokeChaincodeWithStringArgs("smc", "get_registered_prosumers_size", channelName);
    int n_num_prosumers = Integer.valueOf(request.getStringPayload());
    request = stub.invokeChaincodeWithStringArgs("smc", "get_registered_consumers_size", channelName);
    int n_num_consumers = Integer.valueOf(request.getStringPayload());
    request = stub.invokeChaincodeWithStringArgs("smc", "get_registered_prosumers", channelName);
    String prosString = request.getStringPayload();
    if (prosString == null) {
      System.out.println("No registered prosumers");
      return null;
    }
    List<ProsumerData> pros = genson.deserialize(prosString, new GenericType<List<ProsumerData>>() {});
    if (pros == null) {
      System.out.println("No pros");
      return null;
    }
    Double p = 1.0;
    int i = 0;
    int j = 0;
    int index_sell_trd = 0;
    int index_buy_trd = 0;
    Map<Long, Double> sS = new HashMap<Long, Double>();
    Long ts = 0L;
    Double tnum = 0.0;
    ts = Long.valueOf(timestamp);
    j = Integer.valueOf(ij);
    List<Double> S;
    double ES_t = 0;
    double sum = 0;
    for (int ii = 0; ii < pros.size(); ii++) {
      Double Si = genson.deserialize(pros.get(ii).getSi_t(), new GenericType<Double>() {

      });
      Map<Long, Double> s_intent = genson.deserialize(pros.get(ii).getSi_t(), new GenericType<HashMap<Long, Double>>() {});
      sS.putAll(s_intent);
      if (sS.containsKey(ts)) {
        tnum = sS.get(ts);
      } else {
        tnum = 0.0;
      }
      pros.get(ii).setSi_t(String.valueOf(tnum));
      sum += tnum;
      sS.clear();
    }
    ES_t = sum;
    argss.add("dso");
    argss.add("ES_t");
    argss.add(String.valueOf(sum));
    request = stub.invokeChaincodeWithStringArgs("smc", "get_registered_consumers", channelName);
    String consString = request.getStringPayload();
    if (consString == null) {
      System.out.println("No registered consumers");
      return null;
    }
    List<ConsumerData> cons = genson.deserialize(consString, new GenericType<List<ConsumerData>>() {});
    if (cons == null) {
      System.out.println("No consumers");
      return null;
    }
    double ED_t = 0;
    Map<Long, Double> dD = new HashMap<Long, Double>();
    for (int jj = 0; jj < cons.size(); jj++) {
      List<Double> Dj = genson.deserialize(cons.get(jj).getDj(), new GenericType<List<Double>>() {});
      Map<Long, Double> demand = genson.deserialize(cons.get(jj).getDj_t(), new GenericType<Map<Long, Double>>() {});
      sum = 0.0;
      dD.putAll(demand);
      if (dD.containsKey(ts)) {
        tnum = dD.get(ts);
      } else {
        tnum = 0.0;
      }
      cons.get(jj).setDj(String.valueOf(tnum));
      dD.clear();
      sum += Double.valueOf(cons.get(j).getDj());
    }
    ED_t = sum;
    double R_t = ED_t / ES_t;
    double D_t = ED_t - ES_t;
    Double Sm = 0.0;
    Double Dm = 0.0;
    Double q = R_t;
    ArrayList<String> argsv = new ArrayList<>();
    argsv.add(String.valueOf(ED_t));
    argsv.add("set_eD_t");
    argsv.add(String.valueOf(ES_t));
    argsv.add("set_eS_t");
    argsv.add(String.valueOf(R_t));
    argsv.add("set_r_t");
    argsv.add(String.valueOf(D_t));
    argsv.add("set_d_t");
    argsv.add(String.valueOf(q));
    argsv.add("set_q");
    setAsset(stub, "dso", stub.getStringState("dso"), argsv);
    if (ES_t >= ED_t) {
      for (int ik = 0; ik < pros.size(); ik++) {
        Sm += R_t * Double.valueOf(pros.get(ik).getS());
        pros.get(ik).setSmi(String.valueOf(R_t * Double.valueOf(pros.get(ik).getS())));
      }
      for (int jk = 0; jk < cons.size(); jk++) {
        Dm += Double.valueOf(cons.get(jk).getDj());
        cons.get(jk).setDmj(String.valueOf(cons.get(j).getDj()));
      }
      if (Sm != Dm) {
        return "false";
      }
    } else {
      Sm = 0.0;
      Dm = 0.0;
      for (int in = 0; in < pros.size(); in++) {
        Sm += Double.valueOf(pros.get(in).getS());
        pros.get(in).setSmi(pros.get(in).getS());
      }
      for (int jn = 0; jn < cons.size(); jn++) {
        Dm += Double.valueOf(cons.get(jn).getDj()) / R_t;
        cons.get(jn).setDmj(String.valueOf(Double.valueOf(cons.get(jn).getDj()) / R_t));
      }
      if (Sm != Dm) {
        return "false";
      }
    }
    String stringCons = genson.serialize(cons);
    String stringPros = genson.serialize(pros);
    request = stub.invokeChaincodeWithStringArgs("smc", "set_registered_prosumers", stringPros, channelName);
    request = stub.invokeChaincodeWithStringArgs("smc", "set_registered_consumers", stringCons, channelName);
    return "done";
  }










}
