package EnergyDSLExamples.a_model;

/*Generated by MPS */

import EnergyDSL.runtime.StateMachine;
import jetbrains.mps.baseLanguage.closures.runtime._FunctionTypes;
import org.iets3.core.expr.simpleTypes.runtime.AH;
import java.math.BigInteger;
import org.pcollections.PVector;
import org.pcollections.TreePVector;
import EnergyDSL.runtime.State;
import jetbrains.mps.internal.collections.runtime.MapSequence;
import EnergyDSL.runtime.Transition;
import java.util.Map;

public class MyStateMachine extends StateMachine {
  public static class Producer {

    public Producer() {
      evaluateContracts();
    }





    public void evaluateContracts() {
    }

    @Override
    public boolean equals(Object o) {
      if (!(o instanceof Producer)) {
        return false;
      }
      Producer rd = ((Producer) o);



      return true;
    }


    @Override
    public String toString() {
      String result = "";

      return result;
    }

  }


  public enum state_enum {
    init("Init");

    private final String value;
    state_enum(String value) {
      this.value = value;
    }
    public String getValue() {
      return this.value;
    }

    public static state_enum fromValue(String value) {
      for (state_enum it : state_enum.values()) {
        if (it.value.equals(value)) {
          return it;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

  }


  public static Number increment_by_value(final Number v) {
    Number res = new _FunctionTypes._return_P0_E0<Number>() {
      public Number invoke() {
        return AH.add(v, ((Number) new BigInteger("7")));
      }
    }.invoke();

    return res;
  }
  public static PVector<Number> energy_transfer = new _FunctionTypes._return_P0_E0<TreePVector<Number>>() {
    public TreePVector<Number> invoke() {
      TreePVector<Number> tpv = TreePVector.empty();
      tpv = tpv.plus(((Number) new BigInteger("1")));
      tpv = tpv.plus(((Number) new BigInteger("2")));
      tpv = tpv.plus(((Number) new BigInteger("3")));
      tpv = tpv.plus(((Number) new BigInteger("4")));
      return tpv;
    }
  }.invoke();
  public static Number value = ((Number) new BigInteger("7"));
  public static Number p_max = ((Number) new BigInteger("1"));
  public MyStateMachine() {
    super(new State());
    MapSequence.fromMap(states).put("initialize", startState);

    MapSequence.fromMap(states).put("initi", new State());

    MapSequence.fromMap(states).get("initialize").addTransition("biding", new Transitionbidinginitialize(MapSequence.fromMap(states).get("initialize")));

  }
  public static class Transitionbidinginitialize extends Transition {
    public Transitionbidinginitialize(State state) {
      super(state);
    }
    @Override
    public State fireEvent(Map<String, Object> parameters, Object vr) {
      boolean conditionsFullfilled = true;

      new _FunctionTypes._void_P0_E0() {
        public void invoke() {
        }
      }.invoke();

      if (!(new _FunctionTypes._return_P0_E0<Boolean>() {
        public Boolean invoke() {
          return AH.isEqual(MyStateMachine.p_max, ((Number) new BigInteger("9")));
        }
      }.invoke())) {
        conditionsFullfilled = false;
      }

      if (conditionsFullfilled) {
        return targetState;
      }

      return null;
    }
  }

}
