package EnergyDSLExamples.a_model;

/*Generated by MPS */

import EnergyDSL.runtime.StateMachine;
import jetbrains.mps.baseLanguage.closures.runtime._FunctionTypes;
import java.math.BigInteger;
import org.pcollections.PVector;
import org.pcollections.TreePVector;
import EnergyDSL.runtime.State;
import jetbrains.mps.internal.collections.runtime.MapSequence;
import EnergyDSL.runtime.Transition;
import java.util.Map;
import org.iets3.core.expr.simpleTypes.runtime.AH;

public class SmartContract extends StateMachine {
  public static Boolean require_dso(Number msg_addr) {
    Boolean res = new _FunctionTypes._return_P0_E0<Boolean>() {
      public Boolean invoke() {
        Boolean bool = new _FunctionTypes._return_P0_E0<Boolean>() {
          public Boolean invoke() {
            if (true) {
              return true;
            } else {
              return false;
            }
          }
        }.invoke();
        return bool;
      }
    }.invoke();

    return res;
  }
  public static Number smcAddr = ((Number) new BigInteger("0"));
  public static Number msgAddr = ((Number) new BigInteger("0"));
  public static Number balance = ((Number) new BigInteger("0"));
  public static Boolean temp = false;
  public static Boolean is_dso = false;
  public static Boolean valid_prosumer = false;
  public static Boolean valid_consumer = false;
  public static Number timestamp = ((Number) new BigInteger("0"));
  public static Number test = ((Number) new BigInteger("0"));
  public static PVector<Number> pros = new _FunctionTypes._return_P0_E0<TreePVector<Number>>() {
    public TreePVector<Number> invoke() {
      TreePVector<Number> tpv = TreePVector.empty();
      tpv = tpv.plus(((Number) new BigInteger("0")));
      return tpv;
    }
  }.invoke();
  public static Boolean init_pros = false;
  public static Boolean init_cons = false;
  public static Number t = ((Number) new BigInteger("0"));
  public static Boolean no_opi = true;
  public static Number fff = ((Number) new BigInteger("1"));
  public static String tstring = "";
  public static SmcData smc = new SmcData();
  public SmartContract() {
    super(new State());
    MapSequence.fromMap(states).put("initi", startState);

    MapSequence.fromMap(states).put("biding", new State());

    MapSequence.fromMap(states).get("initi").addTransition("biding", new Transitionbidinginiti(MapSequence.fromMap(states).get("biding")));

  }
  public static class Transitionbidinginiti extends Transition {
    public Transitionbidinginiti(State state) {
      super(state);
    }
    @Override
    public State fireEvent(Map<String, Object> parameters, Object vr) {
      boolean conditionsFullfilled = true;

      new _FunctionTypes._return_P0_E0<Boolean>() {
        public Boolean invoke() {
          no_opi = true;
          fff = ((Number) new BigInteger("645646"));
          return AH.isEqual(((Number) new BigInteger("8")), ((Number) new BigInteger("9")));
        }
      }.invoke();

      if (!(new _FunctionTypes._return_P0_E0<Boolean>() {
        public Boolean invoke() {
          return false == true;
        }
      }.invoke())) {
        conditionsFullfilled = false;
      }

      if (conditionsFullfilled) {
        return targetState;
      }

      return null;
    }
  }

}
