package EnergyDSL.BuiltIns;

/*Generated by MPS */


public class AllowedNamesTransactions {
  public static final String energyTrading = "energyTrading";
  public static final String injectEnergy = "injectEnergy";
  public static final String aggregation = "aggregation";
  public static final String matching = "matching";
  public static final String tradeEnergy = "tradeEnergy";

  public static final String createSmc = "createSmc";
  public static final String calculateBalances = "calculateBalances";
  public static final String orderElements = "orderElements";
  public static final String delete = "delete";

  public static final String event = "event";
  public static final String require = "require";
  public static final String register = "register";
  public static final String balancesConsumerSet = "balancesConsumerSet";
  public static final String balancesProsumerSet = "balancesProsumerSet";
  public static final String validateProsumer = "validateProsumer";
  public static final String validateConsumer = "validateConsumer";
  public static final String proInit = "proInit";
  public static final String conInit = "conInit";
  public static final String getRegisteredConsumers = "getRegisteredConsumers";
  public static final String getRegisteredConsumersSize = "getRegisteredConsumersSize";
  public static final String getRegisteredProsumers = "getRegisteredProsumers";
  public static final String getRegisteredProsumersSize = "getRegisteredProsumersSize";
  public static final String validProsumersGet = "validProsumersGet";
  public static final String validConsumersGet = "validConsumersGet";
  public static final String setRegisteredProsumers = "setRegisteredProsumers";
  public static final String setRegisteredConsumers = "setRegisteredConsumers";
  public static final String registeredProsumerSet = "registeredProsumerSet";
  public static final String registeredConsumerSet = "registeredConsumerSet";
  public static final String smcGet = "smcGet";
  public static final String smcSet = "smcSet";

  public static final String oneGet = "oneGet";
  public static final String oneSet = "oneSet";
  public static final String reset = "reset";
  public static final String simpleGet = "simpleGet";
  public static final String getState = "getState";
  public static final String addState = "addState";
  public static final String setState = "setState";
  public static final String setStateAdd = "setStateAdd";
  public static final String setOwnershipStructureAdd = "setOwnershipStructureAdd";
  public static final String simpleInit = "simpleInit";
  public static final String sendTx = "sendTx";
  public static final String requireDso = "requireDso";
  public static final String deleteAsset = "deleteAsset";

  public static final String transfer = "transfer";
  public static final String consumerGet = "consumerGet";

  public static final String msg = "msg";
  public static final String prosumerGet = "prosumerGet";

  public static final String dsoSet = "dsoSet";
  public static final String dsoGet = "dsoGet";
  public static final String getDso = "getDso";
  public static final String createDso = "createDso";
  public static final String pricingDso = "pricingDso";
  public static final String isDso = "isDso";
  public static final String calculate = "calculate";

}
