package Energy_Program.tests;

/*Generated by MPS */

import jetbrains.mps.lang.test.runtime.BaseTransformationTest;
import org.junit.ClassRule;
import jetbrains.mps.lang.test.runtime.TestParametersCache;
import org.junit.Rule;
import jetbrains.mps.lang.test.runtime.RunWithCommand;
import org.junit.Test;
import jetbrains.mps.MPSLaunch;
import jetbrains.mps.lang.test.runtime.BaseTestBody;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import org.iets3.core.expr.tests.rt.runtime.TestRunner;
import jetbrains.mps.lang.test.runtime.TransformationTest;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class Injectenergy_Test extends BaseTransformationTest {

  @ClassRule
  public static final TestParametersCache ourParamCache = new TestParametersCache(Injectenergy_Test.class, "", "r:16a1329e-6f25-4902-bc4c-e3a292027528(Energy_Program.tests)", false);

  @Rule
  public final RunWithCommand myWithCommandRule = new RunWithCommand(this);

  public Injectenergy_Test() {
    super(ourParamCache);
  }


  @Test
  public void Injectenergy_item0_402101814179531664() throws Throwable {
    new TestBody(this).Injectenergy_item0_402101814179531664();
  }


  @MPSLaunch
  public static class TestBody extends BaseTestBody {

    public void Injectenergy_item0_402101814179531664() throws Exception {
      SNode ti = SNodeOperations.cast(getRealNodeById("402101814179531664"), CONCEPTS.AbstractTestItem$9u);
      TestRunner.doExecuteTest(ti);
    }

    protected TestBody(TransformationTest owner) {
      super(owner);
    }
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept AbstractTestItem$9u = MetaAdapterFactory.getConcept(0xd441fba0f46b43cdL, 0xb723dad7b65da615L, 0x7211e50064e6dba0L, "org.iets3.core.expr.tests.structure.AbstractTestItem");
  }
}
