package Energy_Program.tests;

/*Generated by MPS */

import jetbrains.mps.lang.test.runtime.BaseTransformationTest;
import org.junit.ClassRule;
import jetbrains.mps.lang.test.runtime.TestParametersCache;
import org.junit.Rule;
import jetbrains.mps.lang.test.runtime.RunWithCommand;
import org.junit.Test;
import jetbrains.mps.MPSLaunch;
import jetbrains.mps.lang.test.runtime.BaseTestBody;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import org.iets3.core.expr.tests.rt.runtime.TestRunner;
import jetbrains.mps.lang.test.runtime.TransformationTest;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class Test_Test extends BaseTransformationTest {

  @ClassRule
  public static final TestParametersCache ourParamCache = new TestParametersCache(Test_Test.class, "", "r:16a1329e-6f25-4902-bc4c-e3a292027528(Energy_Program.tests)", false);

  @Rule
  public final RunWithCommand myWithCommandRule = new RunWithCommand(this);

  public Test_Test() {
    super(ourParamCache);
  }


  @Test
  public void Test_item0_595681780542165792() throws Throwable {
    new TestBody(this).Test_item0_595681780542165792();
  }
  @Test
  public void Test_item1_595681780562415204() throws Throwable {
    new TestBody(this).Test_item1_595681780562415204();
  }
  @Test
  public void Test_item2_595681780562424307() throws Throwable {
    new TestBody(this).Test_item2_595681780562424307();
  }
  @Test
  public void Test_item3_595681780562425263() throws Throwable {
    new TestBody(this).Test_item3_595681780562425263();
  }
  @Test
  public void Test_item4_595681780562426556() throws Throwable {
    new TestBody(this).Test_item4_595681780562426556();
  }
  @Test
  public void Test_item5_595681780562438127() throws Throwable {
    new TestBody(this).Test_item5_595681780562438127();
  }
  @Test
  public void Test_item6_595681780562451927() throws Throwable {
    new TestBody(this).Test_item6_595681780562451927();
  }
  @Test
  public void Test_item7_1262845581623032421() throws Throwable {
    new TestBody(this).Test_item7_1262845581623032421();
  }


  @MPSLaunch
  public static class TestBody extends BaseTestBody {

    public void Test_item0_595681780542165792() throws Exception {
      SNode ti = SNodeOperations.cast(getRealNodeById("595681780542165792"), CONCEPTS.AbstractTestItem$9u);
      TestRunner.doExecuteTest(ti);
    }
    public void Test_item1_595681780562415204() throws Exception {
      SNode ti = SNodeOperations.cast(getRealNodeById("595681780562415204"), CONCEPTS.AbstractTestItem$9u);
      TestRunner.doExecuteTest(ti);
    }
    public void Test_item2_595681780562424307() throws Exception {
      SNode ti = SNodeOperations.cast(getRealNodeById("595681780562424307"), CONCEPTS.AbstractTestItem$9u);
      TestRunner.doExecuteTest(ti);
    }
    public void Test_item3_595681780562425263() throws Exception {
      SNode ti = SNodeOperations.cast(getRealNodeById("595681780562425263"), CONCEPTS.AbstractTestItem$9u);
      TestRunner.doExecuteTest(ti);
    }
    public void Test_item4_595681780562426556() throws Exception {
      SNode ti = SNodeOperations.cast(getRealNodeById("595681780562426556"), CONCEPTS.AbstractTestItem$9u);
      TestRunner.doExecuteTest(ti);
    }
    public void Test_item5_595681780562438127() throws Exception {
      SNode ti = SNodeOperations.cast(getRealNodeById("595681780562438127"), CONCEPTS.AbstractTestItem$9u);
      TestRunner.doExecuteTest(ti);
    }
    public void Test_item6_595681780562451927() throws Exception {
      SNode ti = SNodeOperations.cast(getRealNodeById("595681780562451927"), CONCEPTS.AbstractTestItem$9u);
      TestRunner.doExecuteTest(ti);
    }
    public void Test_item7_1262845581623032421() throws Exception {
      SNode ti = SNodeOperations.cast(getRealNodeById("1262845581623032421"), CONCEPTS.AbstractTestItem$9u);
      TestRunner.doExecuteTest(ti);
    }

    protected TestBody(TransformationTest owner) {
      super(owner);
    }
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept AbstractTestItem$9u = MetaAdapterFactory.getConcept(0xd441fba0f46b43cdL, 0xb723dad7b65da615L, 0x7211e50064e6dba0L, "org.iets3.core.expr.tests.structure.AbstractTestItem");
  }
}
