package EnergyDSLModels.EnergyTradingAlgorithmFabric;

/*Generated by MPS */

import org.hyperledger.fabric.contract.annotation.Contract;
import org.hyperledger.fabric.contract.annotation.Default;
import org.hyperledger.fabric.contract.ContractInterface;
import com.owlike.genson.Genson;
import org.hyperledger.fabric.Logger;
import java.util.Map;
import java.util.function.Function;
import EnergyDSL.runtime.ProsumerData;
import EnergyDSL.runtime.ConsumerData;
import EnergyDSL.runtime.DSOData;
import EnergyDSL.runtime.ContractAsset;
import org.hyperledger.fabric.shim.ChaincodeException;
import EnergyDSL.runtime.ChaincodeConstants;
import java.util.Locale;
import java.util.ArrayList;
import org.hyperledger.fabric.contract.annotation.Transaction;
import org.hyperledger.fabric.contract.Context;
import org.hyperledger.fabric.shim.ChaincodeStub;
import com.owlike.genson.GenericType;
import org.hyperledger.fabric.shim.Chaincode;
import EnergyDSL.runtime.SmartContractData;
import java.util.List;
import EnergyDSL.runtime.EnergyOwnership;
import java.util.HashMap;

@Contract(name = "smc")
@Default
public class ContractSMC implements ContractInterface {

  private static final Genson genson = new Genson();
  private static final Logger logger = Logger.getLogger("contractLogger");
  public static final Map<String, Function<ProsumerData, String>> PROSUMER_PROPERTIES = Map.ofEntries(Map.entry("balancesp", ProsumerData::getBalancesP), Map.entry("ip", ProsumerData::getIp), Map.entry("opiownershipstructure", ProsumerData::getOpiOwnershipStructure), Map.entry("smi", ProsumerData::getSmi), Map.entry("sit", ProsumerData::getSit), Map.entry("ei", ProsumerData::getEi));
  public static final Map<String, Function<ConsumerData, String>> CONSUMER_PROPERTIES = Map.ofEntries(Map.entry("balancesc", ConsumerData::getBalancesC), Map.entry("ic", ConsumerData::getIc), Map.entry("ocjownershipstructure", ConsumerData::getOcjOwnershipStructure), Map.entry("djt", ConsumerData::getDjt), Map.entry("dmj", ConsumerData::getDmj));
  public static final Map<String, Function<DSOData, String>> DSO_PROPERTIES = Map.ofEntries(Map.entry("est", DSOData::getESt), Map.entry("dsoid", DSOData::getDsoId), Map.entry("edt", DSOData::getEDt), Map.entry("rt", DSOData::getRt), Map.entry("dt", DSOData::getDt), Map.entry("q", DSOData::getQ), Map.entry("pcon", DSOData::getPcon), Map.entry("k", DSOData::getK), Map.entry("pt", DSOData::getPt), Map.entry("deltat", DSOData::getDeltat), Map.entry("pbalance", DSOData::getPbalance));
  /**
   *  Retrieves a specific property value from a asset object based on the given property name. 
   *  The property name matching is case-insensitive. 
   *  Returns null if the asset object is null or the property name is unrecognized. 
   *  @param assetObject the object from which to retrieve the property 
   *  @param propName the name of the property to retrieve (e.g., "smi", "est", "balancep") 
   *  @return the value of the specified property as a String, or null if the property is unknown or asset is null
   * 
   */
  public static String getAssetProperty(final ContractAsset asset, final String propName) {
    if (asset == null || propName == null) {
      return null;
    }
    String prop = propName.toLowerCase();
    if (asset instanceof ProsumerData) {
      ProsumerData prosumer = (ProsumerData) asset;
      Function<ProsumerData, String> fn = PROSUMER_PROPERTIES.get(prop);
      return (fn != null ? fn.apply(prosumer) : null);
    } else
    if (asset instanceof ConsumerData) {
      ConsumerData consumer = (ConsumerData) asset;
      Function<ConsumerData, String> fn = CONSUMER_PROPERTIES.get(prop);
      return (fn != null ? fn.apply(consumer) : null);
    } else
    if (asset instanceof DSOData) {
      DSOData dso = (DSOData) asset;
      Function<DSOData, String> fn = DSO_PROPERTIES.get(prop);
      return (fn != null ? fn.apply(dso) : null);
    }
    return null;
  }
  /**
   * Represents safe checked type cast
   * 
   * @param asset Contract asset to be cast
   * @param expectedType Type of the asset class
   * @param <T> generic type parameter
   * @throws ChaincodeException if asset is null or not of the expected type
   * @return Casted asset
   */
  public static <T extends ContractAsset> T castAsset(ContractAsset asset, Class<T> expectedType) {
    if (asset == null || !(expectedType.isInstance(asset))) {
      if (asset == null) {
        handleError("Asset is null", ChaincodeConstants.TYPE_MISMATCH);
      }

      handleError("Asset is of type " + asset.getClass().getSimpleName() + ", expected " + expectedType.getSimpleName(), ChaincodeConstants.TYPE_MISMATCH);
    }
    return expectedType.cast(asset);
  }
  /**
   * Represents safe parsing integer numbers
   * 
   * @param value String value that needs to be parsed into Integer
   * @param fieldName Name of the field
   * @throws ChaincodeException if value is null or not a valid 
   * @return Parsed Integer value 
   */
  public static Integer parseInteger(String value, String fieldName) {
    try {
      return Integer.parseInt(value);
    } catch (NumberFormatException e) {
      handleError("Invalid integer for " + fieldName + ": " + value, ChaincodeConstants.PARSE_ERROR);
      return null;
    }
  }
  /**
   * Represents safe parsing double numbers
   * 
   * @param value String value that needs to be parsed into Double
   * @param fieldName Name of the field
   * @throws ChaincodeException if value is null or not a valid 
   * @return Parsed Double value 
   */
  public static Double parseDouble(String value, String fieldName) {
    try {

      return Double.parseDouble(value);
    } catch (NumberFormatException e) {
      handleError("Invalid double for " + fieldName + ": " + value, ChaincodeConstants.PARSE_ERROR);
      return null;
    }
  }
  /**
   * Represents safe parsing long numbers
   * 
   * @param value String value that needs to be parsed into Long
   * @param fieldName Name of the field
   * @throws ChaincodeException if value is null or not a valid 
   * @return Parsed Long Integer value 
   */
  public static Long parseLong(String value, String fieldName) {
    try {
      return Long.parseLong(value);
    } catch (NumberFormatException e) {
      handleError("Invalid Long integer for " + fieldName + ": " + value, ChaincodeConstants.PARSE_ERROR);
      return null;
    }
  }
  /**
   *  Validates that the provided value is a non-negative number. 
   *  This utility method ensures that a given numeric value (provided as a String, Double, or Integer) 
   *  is not negative. It throws a chaincode exception if the value is negative or of an unsupported type. 
   *  @param value      the value to be validated; can be a String, Double, or Integer (mostly String) 
   *  @param fieldName  the name of the field associated with the value (used in error messages). 
   *  @throws ChaincodeException if the value is negative or of an unsupported type.
   */
  public static void validatePositiveNumber(Object value, String fieldName) {
    double number = 0.0;
    // Convert the value to a double based on its type
    if (value instanceof String) {
      number = parseDouble((String) value, ChaincodeConstants.num);
    } else if (value instanceof Double) {
      number = ((Double) value);
    } else if (value instanceof Integer) {
      number = ((Integer) value).doubleValue();
    } else {
      // Unsupported type provided
      handleError("Unsupported type for " + fieldName);
    }
    // Validate the number is not negative
    if (number < 0) {
      handleError(fieldName + "must not be negative. Value is: " + value);
    }
  }
  /**
   *  Rounds down a given timestamp (in milliseconds) to the nearest 15-minute interval. 
   *  This method is useful for aligning timestamps to discrete intervals, such as those used in  
   *  energy trading or time-series aggregation, where data needs to be grouped into uniform time slots. 
   *  @param timeInMillis the original timestamp in milliseconds (e.g., System.currentTimeMillis()). 
   *  @return the timestamp (in milliseconds) rounded down to the previous 15-minute boundary. 
   *  Example: If the input is 10:17 AM, the result will be 10:15 AM.
   * 
   */
  public static Long roundDownTo15Minutes(Long timeInMillis) {
    // Convert milliseconds to total minutes
    Long mins = timeInMillis / (ChaincodeConstants.MILLISECONDS_IN_MINUTE);
    // Round down to the nearest 15-minute interval and convert back to milliseconds
    return (mins / ChaincodeConstants.FIFTEEN_MINUTES) * ChaincodeConstants.FIFTEEN_MINUTES * ChaincodeConstants.MILLISECONDS_IN_MINUTE;
  }
  /**
   *  Rounds up a given timestamp (in milliseconds) to the nearest 15-minute interval. 
   *  This function is used to ensure that time values align with the next quarter-hour mark, while leaving 
   * timestamps that are already aligned unchanged.
   *  This  is particularly useful in scheduling, forecasting, and aggregating data into uniform time windows. 
   *  @param timeInMillis the original timestamp in milliseconds (e.g., System.currentTimeMillis()). 
   *  @return the timestamp (in milliseconds) rounded up to the next 15-minute boundary. 
   *  Example: If the input is 10:17 AM, the result will be 10:30 AM. 
   *  If the input is exactly on a 15-minute boundary (e.g., 10:15 AM), it will remain unchanged
   */
  public static Long roundUpTo15Minutes(Long timeInMillis) {
    // Convert milliseconds to total minutes
    Long mins = timeInMillis / (ChaincodeConstants.MILLISECONDS_IN_MINUTE);
    // If already on a 15-minute boundary, keep it; otherwise round up to the next one
    return (((mins % ChaincodeConstants.FIFTEEN_MINUTES) == 0 ? mins : mins + (ChaincodeConstants.FIFTEEN_MINUTES - (mins % ChaincodeConstants.FIFTEEN_MINUTES)))) * ChaincodeConstants.MILLISECONDS_IN_MINUTE;
  }
  /**
   *  Handles an error by logging it and throwing a ChaincodeException. 
   *  This utility method is used to handle errors in a consistent way across the smart contract. 
   *  It prints the error message to the standard error stream and throws a code ChaincodeException 
   *  to halt execution and signal failure to the Hyperledger Fabric runtime.
   *  This method is a convenience overload that uses a default error code. 
   *  @param message the error message to be logged and included in the thrown exception. 
   *  @throws ChaincodeException always thrown with the provided message and default code.
   */
  public static void handleError(String message) {
    // Call the overload method
    handleError(message, ChaincodeConstants.GENERAL_ERROR);

  }
  /**
   *  Handles errors by logging the message with a specific error code and throwing a ChaincodeException.
   *  This method allows for more granular error categorization, which is useful for debugging and client-side handling.
   *  @param message The error message to log and include in the exception.
   *  @param code    A string representing the error category or code (e.g., "VALIDATION_ERROR", "CHAINCODE_INVOKE_ERROR")
   *  @throws ChaincodeException always thrown with the provided message and code. 
   */
  public static void handleError(String message, String code) {
    // Log the error message and code
    logger.error("[" + code + "] " + message);
    // Throw a chaincode exception with the message and code
    throw new ChaincodeException(message, code);

  }
  /**
   *  Deserializes a JSON string into a specific type of ContractAsset based on the asset type. 
   *  This method is used to convert a JSON representation of an asset into its corresponding 
   *  Java object subclass (ProsumerData, ConsumerData, or DSOData), which implements the ContractAsset interface. 
   *  If the asset type is unknown, a  ChaincodeException is thrown. 
   *  @param assetType the type of the asset (e.g., "prosumer", "consumer", or "dso"); case-insensitive. 
   *  @param assetJSON the JSON string representing the asset.
   *  @return a deserialized object of type ContractAsset corresponding to the asset type. 
   *  @throws ChaincodeException if the asset type is not recognized.
   */
  private static ContractAsset deserializeAsset(String assetType, String assetJSON) {
    // Normalize the asset type string to lowercase and determine the correct class for deserialization
    switch (assetType.toLowerCase(Locale.ROOT)) {
      case ChaincodeConstants.PROSUMER:
        return genson.deserialize(assetJSON, ProsumerData.class);
      case ChaincodeConstants.CONSUMER:
        return genson.deserialize(assetJSON, ConsumerData.class);
      case ChaincodeConstants.DSO:
        return genson.deserialize(assetJSON, DSOData.class);
      default:
        // If the type is unrecognized, throw an error to stop execution
        throw new ChaincodeException("Unknown asset type: " + assetType);
    }
  }
  /**
   *  Updates the properties of a given ContractAsset using key-value pairs from a list of arguments. 
   *  The method expects the argument list to contain pairs in the format:  
   *  [value1, setKey1, value2, setKey2, ...], where each `setKey` should start with "set". 
   *  <p>If the list has two or fewer elements, no updates are performed. Each key is normalized by  
   *  removing the "set" prefix and lowercasing the remainder before passing it to the asset's  
   *  updateProperty} method. 
   *  @param asset the asset whose properties are to be updated 
   *  @param args  a list of alternating values and setter keys (e.g., "100", "setBalance")
   */
  private static void updateAssetProperties(ContractAsset asset, ArrayList<String> args) {
    // If the list doesn't contain enough pairs to update, exit early
    int size = args.size();
    if (size <= 2) {
      return;
    }
    // Iterate over the list in steps of two (value and key)
    for (int i = 0; i < size - 1; i = i + 2) {
      String value = args.get(i);
      String setKey = args.get(i + 1).toLowerCase(Locale.ROOT);
      // Check if the key starts with "set"
      if (setKey.startsWith(ChaincodeConstants.SETTER_PREFIX)) {
        // Remove the "set" prefix to extract the actual property name
        setKey = setKey.substring(3);
        // Update the property on the asset with the given value
        asset.updateProperty(setKey, value);
      }
    }
  }
  /**
   *  Creates or updates an asset on the ledger based on its type and provided JSON and arguments. 
   *  <p>This method:
   *  <ul> 
   *    <li>Deserializes a JSON string into an asset object based on the provided asset type.</li> 
   *    <li>Updates the asset’s properties using a list of key-value pairs.</li> 
   *    <li>Determines a unique asset name (key) based on the asset type and identifier field.</li> 
   *    <li>Stores the updated asset back to the ledger using  ChaincodeStub#putStringState}.</li> 
   *  </ul> 
   *  If assetString  is null, the method returns null without making any changes.</p> 
   *  @param ctx         the transaction context, providing access to the chaincode stub 
   *  @param assetType   the type of asset ("prosumer", "consumer", or "dso") 
   *  @param assetString the JSON string representing the asset object\n 
   *  @param args        a JSON-formatted list of alternating values and setter keys to update the asset 
   *  @return            the updated and serialized asset as a JSON string 
   *  @throws ChaincodeException if asset type is unknown or if any internal logic fails
   */
  @Transaction(intent = Transaction.TYPE.SUBMIT)
  public static String setAsset(Context ctx, final String assetType, final String assetString, final String args) {
    // Obtain stub to interact with ledger state
    ChaincodeStub stub = ctx.getStub();
    // Deserialize arguments from JSON into a list of strings
    ArrayList<String> argsList = genson.deserialize(args, new GenericType<ArrayList<String>>() {});
    String assetSerialized;
    String name;
    // If the asset string is null, skip processing, throw error
    if (assetString == null) {
      handleError("No asset", ChaincodeConstants.INVALID_ASSET_INPUT);
    }
    // Deserialize the JSON string based on its type into specific asset object
    ContractAsset asset = deserializeAsset(assetType, assetString);
    // Update the asset's fields based on the key-value argument pairs
    updateAssetProperties(asset, argsList);

    // Generate a unique name (key) for storing in the ledger
    if (assetType.toLowerCase(Locale.ROOT).contains(ChaincodeConstants.PROSUMER)) {
      name = ChaincodeConstants.PREFIX_PROSUMER + ((ProsumerData) asset).getIp();
    } else if (assetType.toLowerCase(Locale.ROOT).contains(ChaincodeConstants.CONSUMER)) {
      name = ChaincodeConstants.PREFIX_CONSUMER + ((ConsumerData) asset).getIc();
    } else {
      name = ChaincodeConstants.DSO;
    }
    // Serialize the updated asset back into JSON format
    assetSerialized = genson.serialize(asset);
    // Store the asset state on the ledger using the determined key
    stub.putStringState(name, assetSerialized);
    // Return the serialized string
    return assetSerialized;
  }
  /**
   * * Validates that specific index is within the valid range
   * 
   * @param index the index to validate
   * @param size the size of the collection
   */
  public static void validateIndex(int index, int size) {
    if (index < 0 || index >= size) {
      handleError("Invalid index: " + index, ChaincodeConstants.INDEX_ERROR);
    }
  }

  /**
   *  smcSet - Sets the SMC asset state with the given serialized string. 
   *  This transaction updates the ledger with the provided `smcString` data under the key 
   *  associated with the SMC identifier. It effectively stores or overwrites 
   *  the current SMC asset on the blockchain. 
   *  @param ctx         the transaction context providing access to the chaincode stub 
   *  @param smcString   the serialized representation of the SMC object to store 
   *  @param channelName the name of the channel (currently unused in this method) 
   *  @return the same serialized SMC string that was stored
   */
  @Transaction(intent = Transaction.TYPE.SUBMIT)
  public String smcSet(Context ctx, final String smcString, final String channelName) {
    ChaincodeStub stub = ctx.getStub();
    // Store the serialized SMC string in the ledger under the "smc" key
    stub.putStringState(ChaincodeConstants.SMC, smcString);
    // Return the stored SMC string
    return smcString;
  }
  /**
   *  smcGet - Returns/Gets the smc asset
   *  Retrieves the current SmartContractData (SMC) asset from the ledger state. 
   *  This method is used to read the serialized SmartContractData object stored 
   *  under a predefined key in the Fabric ledger. If the SMC asset does not exist, 
   *  it logs an error and returns an empty JSON object. 
   *  @param ctx          The Fabric transaction context 
   *  @param channelName  The name of the channel (not used in the logic) 
   *  @return             Serialized SMC asset as a JSON string; returns "{}" if not found
   */
  @Transaction(intent = Transaction.TYPE.SUBMIT)
  public String smcGet(Context ctx, final String channelName) {
    // Retrieve chaincode stub to access ledger state
    ChaincodeStub stub = ctx.getStub();
    // Attempt to get the serialized SmartContractData (SMC) from the ledger
    String smcString = stub.getStringState(ChaincodeConstants.SMC);
    // Check if the SMC asset is present
    if (smcString == null || smcString.isEmpty()) {
      ContractSMC.logger.error("No smc in smcGet");
      smcString = ChaincodeConstants.empty_json_string;
    }
    // Log the retrieved SMC value
    ContractSMC.logger.info(smcString);
    // Return the SMC JSON string (or "{}" if not found)
    return smcString;
  }
  /**
   *  oneSet - Sets or updates the value of an asset in the ledger. 
   *  This method stores the provided string value under the specified asset name key. 
   *  If the key already exists, its value is overwritten.\n *\n 
   *  @param ctx         The transaction context provided by Hyperledger Fabric. 
   *  @param name        The key (asset name) to be created or updated in the ledger. 
   *  @param value       The new string value to associate with the given key. 
   *  @param channelName The name of the channel on which the transaction is submitted (not used in this method).
   *  @return            A confirmation string in the format "name: value".
   */
  @Transaction(intent = Transaction.TYPE.SUBMIT)
  public String oneSet(Context ctx, final String name, final String value, final String channelName) {
    // Get the stub for accessing ledger state
    ChaincodeStub stub = ctx.getStub();
    // Write the new value to the ledger under the given key
    stub.putStringState(name, value);
    // Log the update operation
    ContractSMC.logger.info(name + ": " + value);
    // Return a confirmation message
    return name + ": " + value;
  }
  /**
   *  oneGet - Retrieves the value of a specific asset stored in the ledger
   *  If the asset is not found (i.e., no value exists for the given key), an error is handled
   *  through a custom error handler defined in the contract 
   *  @param ctx         The transaction context provided by Hyperledger Fabric.
   *  @param name        The key (asset name) whose value is to be retrieved. 
   *  @param channelName The name of the channel on which the transaction is evaluated (not used in this method). 
   *  @return            The string value associated with the given key.
   */
  @Transaction(intent = Transaction.TYPE.EVALUATE)
  public String oneGet(Context ctx, final String name, final String channelName) {
    // Get the stub to access ledger state
    ChaincodeStub stub = ctx.getStub();
    // Retrieve the value for the given key
    String value = stub.getStringState(name);
    // If the asset doesn't exist or is empty, handle the error
    if (value == null || value.isEmpty()) {
      ContractSMC.handleError("No asset: " + name);
    }
    // Return the asset value
    return value;
  }
  /**
   *  deleteAsset - Deletes the asset 
   *  Deletes a specified asset from the ledger state. 
   *  This transaction removes the asset identified by its key (name) 
   *  from the ledger and logs the operation. It is a state-changing operation. 
   *  @param ctx          The transaction context provided by Hyperledger Fabric
   *  @param name         The name (key) of the asset to be deleted from the ledger
   *  @param channelName  The name of the channel where this transaction is executed (not used in logic) 
   *  @return A confirmation message indicating that the asset has been deleted
   */
  @Transaction(intent = Transaction.TYPE.SUBMIT)
  public String deleteAsset(Context ctx, String name, final String channelName) {
    // Get the stub to access and modify the ledger state
    ChaincodeStub stub = ctx.getStub();
    // Delete the asset from the ledger state using its key
    stub.delState(name);
    // Log the deletion for traceability
    ContractSMC.logger.info(name + " is deleted");
    // Return a confirmation message
    return name + " is deleted";
  }
  /**
   *  sendTx - Handles the transmission of blockchain transactions between participants. 
   *  This method is used to route transaction requests to the appropriate smart contract, 
   *  either for consumers or prosumers, depending on the context (e.g., transfer, trade). 
   *  It encapsulates a cross-chaincode invocation on a specified channel. 
   *  
   *  Expected arguments: 
   *  - A state identifier (e.g., "transfer", "trade") 
   *  - A serialized SmartContractData object 
   *  - An index (iN) indicating which participant (consumer/prosumer) is affected 
   *  - A value (valueN) to be transferred (e.g., energy, balance) 
   *  @param ctx          The transaction context provided by Fabric runtime. 
   *  @param $arg         Templated argument(s) such as state, SMC asset string, index, value. 
   *  @param channelName  Name of the Fabric channel for the cross-chaincode call. 
   *  @return             The resulting updated SmartContractData string from the called chaincode.
   */
  @Transaction(intent = Transaction.TYPE.SUBMIT)
  public String sendTx(Context ctx, final String name, final String state, final String ij, final String num, final String smcstring, final String channelName) {
    ChaincodeStub stub = ctx.getStub();
    // Collect arguments into a list
    ArrayList<String> argumentsList = new ArrayList<String>();
    argumentsList.add(name);
    argumentsList.add(state);
    argumentsList.add(ij);
    argumentsList.add(num);
    argumentsList.add(smcstring);
    Chaincode.Response request = null;
    String stateN = "";
    String smcStringN = null;
    stateN = state;
    smcStringN = smcstring;

    if (smcStringN == null || smcStringN.isEmpty()) {
      ContractSMC.handleError("No smc in tx");
    }
    {
      String valueN = "";
      String iN = "";
      iN = ij;
      valueN = num;
      // Determine if it's a consumer transaction
      if (argumentsList.get(0).equalsIgnoreCase(ChaincodeConstants.CONSUMER)) {
        // Invoke consumer chaincode for transfer
        request = stub.invokeChaincodeWithStringArgs(ChaincodeConstants.consumerContract, ChaincodeConstants.transfer, iN, valueN, smcStringN, channelName);
        // Handle error if invocation fails
        if (request.getStatusCode() != ChaincodeConstants.SUCCESS_STATUS) {
          ContractSMC.handleError("Error invoking consumer transfer in sendTx: " + request.getMessage());
        }
      } else {
        // Prosumer-related transaction (either "transfer" or "trade")
        if (stateN.equals(ChaincodeConstants.transfer)) {
          request = stub.invokeChaincodeWithStringArgs(ChaincodeConstants.prosumerContract, ChaincodeConstants.transfer, iN, valueN, smcStringN, channelName);
          if (request.getStatusCode() != ChaincodeConstants.SUCCESS_STATUS) {
            ContractSMC.handleError("Error invoking prosumer transfer in sendTx: " + request.getMessage());
          }
        } else if (stateN.equals(ChaincodeConstants.trade)) {
          request = stub.invokeChaincodeWithStringArgs(ChaincodeConstants.prosumerContract, ChaincodeConstants.transfer, iN, valueN, smcStringN, channelName);
          if (request.getStatusCode() != ChaincodeConstants.SUCCESS_STATUS) {
            ContractSMC.handleError("Error invoking prosumer transfer in sendTx: " + request.getMessage());
          }
        }
      }
    }
    // Parse result or raise error
    smcStringN = (request != null ? request.getStringPayload() : null);
    if (smcStringN == null || smcStringN.isEmpty()) {
      ContractSMC.handleError("No smc in sendTx SMC.");
    }
    return smcStringN;
  }
  /**
   * calculateBalances - Calculate balances of all consumers and prosumers. Not used in the algorithm now
   */
  @Transaction(intent = Transaction.TYPE.SUBMIT)
  public String calculateBalances(Context ctx, final String p, final String timestamp, final String startDate, final String endDate, final String channelName) {
    ChaincodeStub stub = ctx.getStub();
    Chaincode.Response request = null;
    Long ts = 0L;
    Double pN = 0.0;
    String smcString = "";
    pN = Double.valueOf(p);
    ts = Long.valueOf(timestamp);
    SmartContractData smc = ContractSMC.genson.deserialize(smcString, SmartContractData.class);
    String prosString = smc.getRegisteredProsumers();
    if (prosString == null || prosString.isEmpty()) {
      ContractSMC.handleError("No registered prosumers in calculateBalances");
    }
    List<ProsumerData> pros = ContractSMC.genson.deserialize(prosString, new GenericType<List<ProsumerData>>() {});
    ArrayList<EnergyOwnership> del = new ArrayList<EnergyOwnership>();
    for (ProsumerData pro : pros) {
      pro.setBalancesP(String.valueOf(ContractSMC.parseDouble(pro.getBalancesP(), ChaincodeConstants.prosumer_balance) + ContractSMC.parseDouble(pro.getSmi(), ChaincodeConstants.Smi) * pN));
      request = stub.invokeChaincodeWithStringArgs(ChaincodeConstants.prosumerContract, ChaincodeConstants.transfer, pro.getIp(), String.valueOf(ContractSMC.parseDouble(pro.getSmi(), ChaincodeConstants.Smi) * pN), smcString, channelName);
      if (request.getStatusCode() != ChaincodeConstants.SUCCESS_STATUS) {
        ContractSMC.handleError("Error invoking prosumer transfer: " + request.getMessage());
      }
      smcString = request.getStringPayload();
      if (smcString == null || smcString.isEmpty()) {
        ContractSMC.handleError("No smc in calcualteBalances");
      }
      smc = ContractSMC.genson.deserialize(smcString, new GenericType<SmartContractData>() {});
      String regsString = smc.getRegisteredProsumers();
      if (regsString == null || regsString.isEmpty()) {
        ContractSMC.handleError("No registered prosumers in calcualteBalances");
      }
      List<ProsumerData> regs = ContractSMC.genson.deserialize(regsString, new GenericType<List<ProsumerData>>() {});
      String OpiString = regs.get(ContractSMC.parseInteger(pro.getIp(), ChaincodeConstants.asset_index)).getOpiOwnershipStructure();
      List<EnergyOwnership> Opi = ContractSMC.genson.deserialize(OpiString, new GenericType<List<EnergyOwnership>>() {});
      regs.get(ContractSMC.parseInteger(pro.getIp(), ChaincodeConstants.asset_index)).setBalancesP(String.valueOf(ContractSMC.parseDouble(pro.getBalancesP(), ChaincodeConstants.prosumer_balance) + ContractSMC.parseDouble(pro.getSmi(), ChaincodeConstants.Smi) * pN));
      for (EnergyOwnership op : Opi) {
        if (ContractSMC.parseLong(op.getTimestamp(), ChaincodeConstants.timestamp).equals(ts) && op.getState().equalsIgnoreCase(ChaincodeConstants.match) && ContractSMC.parseDouble(op.getAmount(), ChaincodeConstants.Op).equals(ContractSMC.parseDouble(pro.getSmi(), ChaincodeConstants.Smi))) {
          del.add(op);
        }
        final String ESt;
      }
      Opi.removeAll(del);
      String assetSerial = ContractSMC.genson.serialize(Opi);
      pro.setOpiOwnershipStructure(assetSerial);
      regs.get(ContractSMC.parseInteger(pro.getIp(), ChaincodeConstants.asset_index)).setOpiOwnershipStructure(assetSerial);
      smc.setRegisteredProsumers(ContractSMC.genson.serialize(regs));
      del = new ArrayList<EnergyOwnership>();
    }
    Double pmax = ContractSMC.parseDouble(smc.getPmax(), "SMC Pmax");
    String consString = smc.getRegisteredConsumers();
    if (consString == null || consString.isEmpty()) {
      ContractSMC.handleError("No registered consumers in calcualteBalances");
    }
    ArrayList<ConsumerData> cons = ContractSMC.genson.deserialize(consString, new GenericType<ArrayList<ConsumerData>>() {});
    ArrayList<Double> balances = ContractSMC.genson.deserialize(smc.getBalances(), new GenericType<ArrayList<Double>>() {});
    smcString = ContractSMC.genson.serialize(smc);
    for (ConsumerData con : cons) {
      HashMap<String, String> djt = ContractSMC.genson.deserialize(con.getDjt(), new GenericType<HashMap<String, String>>() {});
      con.setBalancesC(String.valueOf(ContractSMC.parseDouble(con.getBalancesC(), ChaincodeConstants.balance) + (ContractSMC.parseDouble(djt.get(ts.toString()), ChaincodeConstants.Djt)) * pmax - ContractSMC.parseDouble(con.getDmj(), ChaincodeConstants.Dmj) * pN));
      balances.set(ContractSMC.parseInteger(con.getIc(), ChaincodeConstants.asset_index), 0.0);
      request = stub.invokeChaincodeWithStringArgs(ChaincodeConstants.consumerContract, ChaincodeConstants.transfer, con.getIc(), String.valueOf(ContractSMC.parseDouble(con.getBalancesC(), ChaincodeConstants.balance) + (ContractSMC.parseDouble(djt.get(ts.toString()), ChaincodeConstants.Djt)) * pmax - ContractSMC.parseDouble(con.getDmj(), ChaincodeConstants.Dmj) * pN), smcString, channelName);
      if (request.getStatusCode() != ChaincodeConstants.SUCCESS_STATUS) {
        ContractSMC.handleError("Error invoking consumer transfer " + request.getMessage());
      }
      smcString = request.getStringPayload();
      if (smcString == null || smcString.isEmpty()) {
        ContractSMC.handleError("No smc from invoked consumer transfer");
      }
      smc = ContractSMC.genson.deserialize(smcString, new GenericType<SmartContractData>() {});
      String regsString = smc.getRegisteredConsumers();
      if (regsString == null || regsString.isEmpty()) {
        ContractSMC.handleError("No registered consumers from invoked consumer transfer");
      }
      List<ConsumerData> regs = ContractSMC.genson.deserialize(regsString, new GenericType<List<ConsumerData>>() {});
      String OciString = con.getOcjOwnershipStructure();
      List<EnergyOwnership> Oci = ContractSMC.genson.deserialize(OciString, new GenericType<List<EnergyOwnership>>() {});
      // DotExpression
      del = new ArrayList<EnergyOwnership>();
      regs.get(ContractSMC.parseInteger(con.getIc(), ChaincodeConstants.asset_index)).setBalancesC(String.valueOf(ContractSMC.parseDouble(con.getBalancesC(), ChaincodeConstants.balance) + (ContractSMC.parseDouble(djt.get(ts.toString()), ChaincodeConstants.balance)) * pmax - ContractSMC.parseDouble(con.getDmj(), ChaincodeConstants.Dmj) * pN));
      for (EnergyOwnership oc : Oci) {
        if (ContractSMC.parseLong(oc.getTimestamp(), ChaincodeConstants.timestamp).equals(ts) && oc.getState().equalsIgnoreCase(ChaincodeConstants.match) && ContractSMC.parseDouble(oc.getAmount(), ChaincodeConstants.Oc).equals(ContractSMC.parseDouble(con.getDmj(), ChaincodeConstants.Dmj))) {
          del.add(oc);
        }
      }
      Oci.removeAll(del);
      EnergyOwnership ocj = new EnergyOwnership(con.getIc(), con.getDmj(), ChaincodeConstants.purchased, String.valueOf(ts));
      Oci.add(ocj);
      String assetSerial = ContractSMC.genson.serialize(Oci);
      con.setOcjOwnershipStructure(assetSerial);
      regs.get(ContractSMC.parseInteger(con.getIc(), ChaincodeConstants.asset_index)).setOcjOwnershipStructure(assetSerial);
      smc.setRegisteredConsumers(ContractSMC.genson.serialize(regs));
      smcString = ContractSMC.genson.serialize(smc);
      smc = ContractSMC.genson.deserialize(smcString, new GenericType<SmartContractData>() {});
    }
    String assetSerialized = "";
    assetSerialized = ContractSMC.genson.serialize(cons);
    smc.setRegisteredConsumers(assetSerialized);
    smc.setBalances(ContractSMC.genson.serialize(balances));
    assetSerialized = ContractSMC.genson.serialize(smc);
    stub.putStringState(ChaincodeConstants.SMC, assetSerialized);
    return assetSerialized;
  }
  /**
   *  delete - Delete particular entity from the ownership structure of consumer/prosumer
   *  delete - Removes a specific `EnergyOwnership` record from a consumer's or prosumer's ownership structure. 
   *  The record is identified based on: 
   *  - Timestamp range (rounded to 15-minute window) 
   *  - Ownership value (amount) 
   *  - State (only for prosumers) 
   *  Applies changes to:\n * - SmartContractData's registered consumers/prosumers 
   *  - Calls external setAsset via cross-chaincode invocation 
   *  - Updates ledger state\n 
   *  @param ctx          The Fabric transaction context. 
   *  @param $arg         Template argument providing timestamp, state, etc. 
   *  @param channelName  The name of the Fabric channel where the transaction is executed. 
   *  @return             The updated SmartContractData serialized as JSON
   */
  @Transaction(intent = Transaction.TYPE.SUBMIT)
  public String delete(Context ctx, final String name, final String timestamp, final String value, final String state, final String ij, final String smcstring, final String channelName) {
    Long tsN = 0L;
    Double valueN = 0.0;
    String nameN = "";
    String stateN = "";
    Integer ijN = 0;
    String smcStringN = "";
    Long startDateN = 0l;
    Long endDateN = 0l;
    ChaincodeStub stub = ctx.getStub();
    Chaincode.Response request = null;
    nameN = String.valueOf(name);
    tsN = Long.valueOf(timestamp);
    valueN = Double.valueOf(value);
    stateN = String.valueOf(state);
    ijN = Integer.valueOf(ij);
    smcStringN = smcstring;
    // Define time window to match energy records
    startDateN = ContractSMC.roundDownTo15Minutes(tsN);
    endDateN = ContractSMC.roundUpTo15Minutes(tsN);
    SmartContractData smc = ContractSMC.genson.deserialize(smcStringN, SmartContractData.class);
    // === HANDLE PROSUMER CASE ===
    if (nameN.equalsIgnoreCase(ChaincodeConstants.PROSUMER)) {
      String prosString = smc.getRegisteredProsumers();
      if (prosString == null || prosString.isEmpty()) {
        ContractSMC.handleError("No registered prosumers in delete");
      }
      ArrayList<ProsumerData> pros = ContractSMC.genson.deserialize(prosString, new GenericType<ArrayList<ProsumerData>>() {});
      // Get ownership structure of targeted prosumer
      String OpiString = pros.get(ijN).getOpiOwnershipStructure();
      ArrayList<EnergyOwnership> Opi = ContractSMC.genson.deserialize(OpiString, new GenericType<ArrayList<EnergyOwnership>>() {});
      // Mark elements for deletion
      ArrayList<EnergyOwnership> del = new ArrayList<EnergyOwnership>();
      for (EnergyOwnership op : Opi) {
        if (ContractSMC.parseLong(op.getTimestamp(), ChaincodeConstants.timestamp) <= endDateN && ContractSMC.parseLong(op.getTimestamp(), ChaincodeConstants.timestamp) >= startDateN && op.getState().equalsIgnoreCase(stateN) && ContractSMC.parseDouble(op.getAmount(), ChaincodeConstants.Op).equals(valueN)) {
          del.add(op);
          break;
        }
      }
      // Remove marked entries from the structure
      Opi.removeAll(del);
      // Do serializations
      String assetSerial = ContractSMC.genson.serialize(Opi);
      pros.get(ijN).setOpiOwnershipStructure(assetSerial);
      String assetSerialized = ContractSMC.genson.serialize(pros);
      smc.setRegisteredProsumers(assetSerialized);
      // Log new state for debugging
      ContractSMC.logger.info(assetSerialized);
      // Cross-chaincode call to update asset in prosumer contract
      request = stub.invokeChaincodeWithStringArgs(ChaincodeConstants.prosumerContract, ChaincodeConstants.setAsset, ChaincodeConstants.PROSUMER, ContractSMC.genson.serialize(pros.get(ijN)), ChaincodeConstants.empty_array_string, channelName);
      // Error handling on chaincode call
      if (request.getStatusCode() != ChaincodeConstants.SUCCESS_STATUS) {
        ContractSMC.handleError("Error invoking prosumer setAsset " + request.getMessage());
      }
      // Update global SmartContractData
      assetSerialized = ContractSMC.genson.serialize(smc);
      ContractSMC.logger.info(assetSerialized);
      stub.putStringState(ChaincodeConstants.SMC, assetSerialized);
      return assetSerialized;
      // === HANDLE CONSUMER CASE ===
    } else if (nameN.equalsIgnoreCase(ChaincodeConstants.CONSUMER)) {
      String consString = smc.getRegisteredConsumers();
      if (consString == null || consString.isEmpty()) {
        ContractSMC.handleError("No registered consumers in delete");
      }
      List<ConsumerData> cons = ContractSMC.genson.deserialize(consString, new GenericType<List<ConsumerData>>() {});
      // Get ownership structure of targeted consumer
      String OciString = cons.get(ijN).getOcjOwnershipStructure();
      List<EnergyOwnership> Oci = ContractSMC.genson.deserialize(OciString, new GenericType<List<EnergyOwnership>>() {});
      ArrayList<EnergyOwnership> del = new ArrayList<EnergyOwnership>();
      for (EnergyOwnership oc : Oci) {
        // Match entry based on time window, state, and value


        if (ContractSMC.parseLong(oc.getTimestamp(), ChaincodeConstants.timestamp) <= endDateN && ContractSMC.parseLong(oc.getTimestamp(), ChaincodeConstants.timestamp) >= startDateN && ContractSMC.parseDouble(oc.getAmount(), ChaincodeConstants.Oc).equals(valueN) && oc.getState().equalsIgnoreCase(stateN)) {
          del.add(oc);
          break;
        }
        final String Op;
      }
      // Remove marked entries from the structure
      Oci.removeAll(del);
      // Update ownership structure and serialize it
      String assetSerial = ContractSMC.genson.serialize(Oci);
      cons.get(ijN).setOcjOwnershipStructure(assetSerial);
      // Serialize and update consumers list
      String assetSerialized = ContractSMC.genson.serialize(cons);

      ContractSMC.logger.info(assetSerialized);
      smc.setRegisteredConsumers(assetSerialized);
      assetSerialized = ContractSMC.genson.serialize(smc);
      // Log state
      ContractSMC.logger.info(assetSerialized);
      // Cross-chaincode update to consumer asset
      request = stub.invokeChaincodeWithStringArgs(ChaincodeConstants.consumerContract, ChaincodeConstants.setAsset, ChaincodeConstants.CONSUMER, ContractSMC.genson.serialize(cons.get(ijN)), ChaincodeConstants.empty_array_string, channelName);
      if (request.getStatusCode() != ChaincodeConstants.SUCCESS_STATUS) {
        ContractSMC.handleError("Error invoking consumer setAsset " + request.getMessage());
      }
      // Finalize SmartContractData update
      stub.putStringState(ChaincodeConstants.SMC, assetSerialized);
      return assetSerialized;
    }
    // If no valid consumer/prosumer role provided
    return "Errors in delete transaction";
  }
  /**
   *  require - check DSO id in smc
   *  Verifies that the DSO (Distribution System Operator) ID stored in the smart contract 
   *  matches the DSO ID provided as input. 
   *  This is a read-only operation that does not modify blockchain state. 
   *  @param ctx         The transaction context 
   *  @param arg        Arguments containing the DSO ID to verify 
   *  @param channelName Name of the channel (not used in this method but part of the signature) 
   *  @return "true" if the DSO ID matches; "false" otherwise 
   */
  @Transaction(intent = Transaction.TYPE.EVALUATE)
  public String require(Context ctx, final String dsoID, final String channelName) {
    // Get the chaincode stub for accessing the ledger
    ChaincodeStub stub = ctx.getStub();
    // Declare variables
    String dsoIdN = ChaincodeConstants.ZERO_INT;
    SmartContractData smcc = null;
    String smcString = null;
    dsoIdN = dsoID;
    // Retrieve the current smart contract state from the ledger
    smcString = stub.getStringState(ChaincodeConstants.SMC);
    // Error if no contract data is found


    if (smcString == null || smcString.isEmpty()) {
      ContractSMC.handleError("No smc in require");
    }
    // Deserialize the smart contract data
    smcc = ContractSMC.genson.deserialize(smcString, SmartContractData.class);
    // Log DSO ID values for debugging
    ContractSMC.logger.info("-------in require smc ----");
    ContractSMC.logger.info(smcc.getDsoId());
    ContractSMC.logger.info(dsoIdN);
    // Compare and return result as string
    return String.valueOf(smcc.getDsoId().equals(dsoIdN));
  }
  /**
   *  register - Registers the prosumer/consumer from i
   *  Registers a prosumer or consumer into the SmartContractData structure at index `i`. 
   *  - For a prosumer: Adds their asset to the list of registered prosumers if not already present.
   *  - For a consumer: Adds their asset to the list of registered consumers if not already present.
   *  - In both cases, it also removes the registered asset from the list of "init" (unregistered) entries. 
   *  @param ctx           The Fabric transaction context.
   *  @param arg     List of arguments (e.g. nameN, ijN, assetN).
   *  @param channelName   The channel name (not used in the method logic).
   *  @return              String "done" if registration is successful.
   */
  @Transaction(intent = Transaction.TYPE.SUBMIT)
  public String register(Context ctx, final String name, final String ij, final String channelName) {
    // Get Fabric stub
    ChaincodeStub stub = ctx.getStub();
    Chaincode.Response request = null;
    // Input variables
    Integer ijN = 0;
    String nameN = "";
    String assetN = ChaincodeConstants.empty_json_string;
    nameN = String.valueOf(name);
    ijN = Integer.valueOf(ij);
    // Get the current SMC from the ledger
    String smcString = stub.getStringState(ChaincodeConstants.SMC);
    SmartContractData smc = ContractSMC.genson.deserialize(smcString, new GenericType<SmartContractData>() {});
    // === Prosumer Registration ===
    if (nameN.equalsIgnoreCase(ChaincodeConstants.PROSUMER)) {
      String prosString = smc.getRegisteredProsumers();
      List<String> regs = ContractSMC.genson.deserialize(prosString, new GenericType<List<String>>() {});
      String prosVString = smc.getInitPros();
      List<String> regsInit = ContractSMC.genson.deserialize(prosVString, new GenericType<List<String>>() {});
      // If index i is valid (not already registered)
      if (regs.size() <= ijN) {
        regs.add(assetN);
        regsInit.remove(assetN);
      } else {
        ContractSMC.handleError("Error registering prosumer. It is already in the list. ");
      }
      // Serialize updated lists and save to SMC
      String assetSerialized = ContractSMC.genson.serialize(regs);
      smc.setRegisteredProsumers(assetSerialized);
      assetSerialized = ContractSMC.genson.serialize(smc);
      stub.putStringState(ChaincodeConstants.SMC, assetSerialized);
      // === Consumer Registration ===
    } else if (nameN.equalsIgnoreCase(ChaincodeConstants.CONSUMER)) {
      String consString = smc.getInitCons();
      List<String> consInit = ContractSMC.genson.deserialize(consString, new GenericType<List<String>>() {});
      String regsString = (request != null ? request.getStringPayload() : null);
      List<String> regs = ContractSMC.genson.deserialize(regsString, new GenericType<List<String>>() {});
      // If index i is valid (not already registered)
      if (regs.size() <= ijN) {
        regs.add(assetN);
        consInit.remove(assetN);
      } else {
        ContractSMC.handleError("Error registering consumer. It is already in the list. ");
      }
      // Serialize updated lists and save to SMC
      String assetSerialized = ContractSMC.genson.serialize(regs);
      smc.setRegisteredConsumers(assetSerialized);
      assetSerialized = ContractSMC.genson.serialize(smc);
      stub.putStringState(ChaincodeConstants.SMC, assetSerialized);
    }
    return "done";
  }
  /**
   *  proInit - Add the prosumer to the list of registered prosumers, if it is not already in the list
   *  proInit - Adds a prosumer to the list of registered prosumers if it is not already registered.
   *  The prosumer is taken from the "initPros" list inside SmartContractData at the index specified by `assetI`.
   *  If the prosumer is already registered (based on the index), an error is thrown.
   *  Otherwise, the prosumer is added to the registered prosumers list and the updated data is saved to the ledger.
   *  @param ctx           The transaction context provided by Fabric.
   *  @param arg     List of arguments including:
   *                       - assetI: The index of the prosumer in the initPros list to register.
   *                       - smcStringN: The current serialized SmartContractData JSON string.
   *  @param channelName   The channel name (not used inside this function).
   *  @return              The updated serialized SmartContractData JSON string after registration.
   */
  @Transaction(intent = Transaction.TYPE.SUBMIT)
  public String proInit(Context ctx, final String timestampP, final String ip, final String smcstring, final String channelName) {
    // Obtain Fabric chaincode stub
    ChaincodeStub stub = ctx.getStub();
    // Variables for inputs
    String assetI = ChaincodeConstants.ZERO_INT;
    String smcStringN = "";
    SmartContractData smc = null;
    assetI = ip;
    smcStringN = smcstring;
    // Deserialize SmartContractData from provided JSON string
    smc = ContractSMC.genson.deserialize(smcStringN, SmartContractData.class);
    // Deserialize the initial (unregistered) prosumers list
    String initProsString = smc.getInitPros();
    ArrayList<ProsumerData> initPros = ContractSMC.genson.deserialize(initProsString, new GenericType<ArrayList<ProsumerData>>() {});
    // Deserialize the currently registered prosumers list
    String regProsString = smc.getRegisteredProsumers();
    // Handle case where registered prosumers list might be null or empty
    if (regProsString == null || regProsString.isEmpty()) {
      ContractSMC.logger.error("No reg pros in pro init");
      regProsString = ChaincodeConstants.empty_array_string;
    }
    ArrayList<ProsumerData> regPros = ContractSMC.genson.deserialize(regProsString, new GenericType<ArrayList<ProsumerData>>() {});
    ContractSMC.logger.info("==========2======");
    ContractSMC.logger.info(assetI);
    ContractSMC.logger.info(String.valueOf(initPros));
    // Check if prosumer at assetI index is already registered
    if (regPros.size() > ContractSMC.parseInteger(assetI, ChaincodeConstants.asset_index)) {
      ContractSMC.handleError("Prosumer with the given id already exists.");
    } else {
      regPros.add(initPros.get(ContractSMC.parseInteger(assetI, ChaincodeConstants.asset_index)));
    }
    // Serialize updated registered prosumers list back to JSON string
    regProsString = ContractSMC.genson.serialize(regPros);
    smc.setRegisteredProsumers(regProsString);
    // Serialize updated SmartContractData and save it back to ledger state
    smcStringN = ContractSMC.genson.serialize(smc);
    stub.putStringState(ChaincodeConstants.SMC, smcStringN);
    // Return updated SmartContractData JSON string
    return smcStringN;
  }
  /**
   *  conInit - Add the consumer to the list of registered consumers, if it is not already in the list
   *  conInit - Adds a consumer to the list of registered consumers if not already registered.
   *  The consumer is taken from the "initCons" list inside SmartContractData at the index specified by `assetI`. 
   *  If the consumer is already registered (based on the index), an error is thrown. 
   *  Otherwise, the consumer is added to the registered consumers list and the updated SmartContractData 
   *  is saved back to the ledger. 
   *  @param ctx           The transaction context provided by Fabric. 
   *  @param arg           List of arguments including: 
   *                       - assetI: The index of the consumer in the initCons list to register. 
   *                       - smcStringN: The current serialized SmartContractData JSON string. 
   *  @param channelName   The channel name (not used in this method). 
   *  @return              The updated serialized SmartContractData JSON string after registration.
   */
  @Transaction(intent = Transaction.TYPE.SUBMIT)
  public String conInit(Context ctx, final String timestampC, final String ic, final String smcstring, final String channelName) {
    // Variables to hold inputs
    String assetI = "";
    SmartContractData smc = null;
    String smcStringN = null;
    assetI = ic;
    smcStringN = smcstring;
    // Deserialize SmartContractData from JSON string
    smc = ContractSMC.genson.deserialize(smcStringN, SmartContractData.class);
    // Handle missing SmartContractData
    if (smc == null) {
      ContractSMC.handleError("No smc in conInit");
    }
    // Deserialize initial (unregistered) consumers list
    String initConsString = smc.getInitCons();
    if (initConsString == null || initConsString.isEmpty()) {
      initConsString = ChaincodeConstants.empty_array_string;
    }
    ArrayList<ConsumerData> initCons = ContractSMC.genson.deserialize(initConsString, new GenericType<ArrayList<ConsumerData>>() {});
    // Deserialize registered consumers list
    String regConsString = smc.getRegisteredConsumers();
    if (regConsString == null || regConsString.isEmpty()) {
      regConsString = ChaincodeConstants.empty_array_string;
    }
    ArrayList<ConsumerData> regCons = ContractSMC.genson.deserialize(regConsString, new GenericType<ArrayList<ConsumerData>>() {});
    // Check if consumer at index assetI already registered
    if (regCons.size() > ContractSMC.parseInteger(assetI, ChaincodeConstants.asset_index)) {
      ContractSMC.handleError("Consumer with the given id already exists.");

    } else {
      regCons.add(initCons.get(ContractSMC.parseInteger(assetI, ChaincodeConstants.asset_index)));
    }
    // Serialize updated registered consumers list and set in SmartContractData
    regConsString = ContractSMC.genson.serialize(regCons);
    smc.setRegisteredConsumers(regConsString);
    // Serialize updated SmartContractData and log info
    smcStringN = ContractSMC.genson.serialize(smc);
    ContractSMC.logger.info(smcStringN);
    ContractSMC.logger.info("-----------------------In cons init-----------------------");
    // Save updated SmartContractData back to ledger
    return smcStringN;
  }
  /**
   *  validateProsumer - Validates that Energy amount injected by prosumer i is greater than 
   *  Amount of intent to sell
   *  Validates whether the specified prosumer has injected enough energy 
   *  to support their intent to sell. 
   *  This evaluation transaction ensures that the injected energy (`Ei`) from a prosumer 
   *  at a given index is greater than or equal to the declared selling intent. 
   *  @param ctx          The transaction context provided by the Fabric runtime 
   *  @param $arg         A looped sequence of arguments  
   *  @param channelName  The name of the Fabric channel (not used directly in logic) 
   *  @return             "true" if injected energy ≥ selling intent, "false" otherwise
   */
  @Transaction(intent = Transaction.TYPE.EVALUATE)
  public String validateProsumer(Context ctx, final String timestamp, final String startDate, final String endDate, final String sit, final String ij, final String channelName) {
    // Get the stub for accessing ledger state
    ChaincodeStub stub = ctx.getStub();
    // Initialize input values
    Integer ijN = 0;
    String SiTN = ChaincodeConstants.ZERO_DOUBLE;
    SmartContractData smcc = null;
    SiTN = sit;
    ijN = Integer.valueOf(ij);
    // Default return value
    String flag = ChaincodeConstants.FALSE_STRING;
    // Fetch the smart contract data from the ledger
    String smcString = stub.getStringState(ChaincodeConstants.SMC);
    if (smcString == null || smcString.isEmpty()) {
      ContractSMC.handleError("No smc in validate");
    }
    // Deserialize the smart contract data
    smcc = ContractSMC.genson.deserialize(smcString, SmartContractData.class);
    // Get the registered prosumer list from the smart contract state
    String regsString = smcc.getRegisteredProsumers();
    if (regsString == null || regsString.isEmpty()) {
      ContractSMC.handleError("No reg pros in validate");
    }
    // Deserialize the list of registered prosumers
    GenericType<ArrayList<ProsumerData>> mapType = new GenericType<ArrayList<ProsumerData>>() {};
    ArrayList<ProsumerData> regs = ContractSMC.genson.deserialize(regsString, mapType);
    // Compare injected energy with selling intent
    if (ContractSMC.parseDouble(regs.get(ijN).getEi(), ChaincodeConstants.Ei) >= ContractSMC.parseDouble(SiTN, ChaincodeConstants.num)) {
      flag = ChaincodeConstants.TRUE_STRING;
    }
    // Log the result
    ContractSMC.logger.info("-----------validateProsumer---------");
    ContractSMC.logger.info(flag);
    // Return the evaluation result
    return flag;
  }
  /**
   *  validateConsumer - checks if consumer has enough balance
   *  Validates whether the specified consumer has enough balance to perform a transaction. 
   *  This evaluation transaction checks if the consumer at the given index has sufficient  
   *  monetary balance to support the required energy transaction  
   *  @param ctx          The transaction context from Hyperledger Fabric 
   *  @param $arg         A looped sequence of arguments 
   *  @param channelName  The channel where the transaction is evaluated (not used in logic) 
   *  @return             "true" if the consumer has enough balance, "false" otherwise
   */
  @Transaction(intent = Transaction.TYPE.EVALUATE)
  public String validateConsumer(Context ctx, final String timestamp, final String startDate, final String endDate, final String djt, final String pmax, final String ij, final String channelName) {
    // Access the Fabric stub for querying state
    ChaincodeStub stub = ctx.getStub();
    // Initialize variables
    Integer ijN = 0;
    String DjtN = ChaincodeConstants.ZERO_DOUBLE;
    Double pmaxN = 1.0;
    SmartContractData smcc = null;
    DjtN = djt;
    pmaxN = Double.valueOf(pmax);
    ijN = Integer.valueOf(ij);
    // Default result flag
    String flag = ChaincodeConstants.FALSE_STRING;
    // Retrieve current SmartContractData state
    String smcString = stub.getStringState(ChaincodeConstants.SMC);
    if (smcString == null || smcString.isEmpty()) {
      ContractSMC.handleError("No smc in validateConsumer");
    }
    // Deserialize SMC string into object
    smcc = ContractSMC.genson.deserialize(smcString, SmartContractData.class);
    // Get all registered consumers from SMC
    String regsString = smcc.getRegisteredConsumers();
    if (regsString == null || regsString.isEmpty()) {
      ContractSMC.handleError("No reg cons in in validateConsumer");
    }
    // Deserialize consumer list
    GenericType<ArrayList<ConsumerData>> mapType = new GenericType<ArrayList<ConsumerData>>() {};
    ArrayList<ConsumerData> regs = ContractSMC.genson.deserialize(regsString, mapType);
    // Check if consumer has enough balance
    if (ContractSMC.parseDouble(regs.get(ijN).getBalancesC(), ChaincodeConstants.balance) >= ContractSMC.parseDouble(DjtN, ChaincodeConstants.num) * pmaxN) {
      flag = ChaincodeConstants.TRUE_STRING;
    }
    // Log the validation result
    ContractSMC.logger.info("-----------validateConsumer---------");
    ContractSMC.logger.info(flag);
    // Return validation result
    return flag;
  }
  /**
   *  getRegisteredConsumers - Return/Get the list of registered prosumers
   *  getRegisteredConsumers - Retrieves the list of registered consumers.
   *  This method reads the current SmartContractData (SMC) from the ledger,
   *  deserializes it, and returns the JSON string representing the list of 
   *  registered consumers.
   *  @param ctx          The transaction context provided by Fabric.
   *  @param channelName  The channel name (not used directly in this method).
   *  @return             JSON string of the registered consumers list.
   *  @throws             Throws an error if the SMC is not found in the ledger.
   */
  @Transaction(intent = Transaction.TYPE.EVALUATE)
  public String getRegisteredConsumers(Context ctx, final String channelName) {
    ChaincodeStub stub = ctx.getStub();
    // Retrieve the serialized SmartContractData from ledger state
    String smcString = stub.getStringState(ChaincodeConstants.SMC);
    // Handle missing or empty SMC state
    if (smcString == null || smcString.isEmpty()) {
      ContractSMC.handleError("No smc in getRegisteredConsumers ");
    }
    // Deserialize the SmartContractData object from JSON string
    SmartContractData smc = ContractSMC.genson.deserialize(smcString, SmartContractData.class);
    // Log the full SmartContractData JSON for debugging/audit
    ContractSMC.logger.info(smcString);
    // Extract and return the JSON string of registered consumers
    String regConsString = smc.getRegisteredConsumers();
    return regConsString;
  }
  /**
   *  getRegisteredConsumersSize - Return/Get the size of the registered consumer list
   *  getRegisteredConsumersSize - Retrieves the number of registered consumers. 
   *  This method fetches the SmartContractData (SMC) object from the ledger, 
   *  deserializes it, extracts the list of registered consumers, and returns 
   *  the size of that list as a string. 
   *  @param ctx          The transaction context provided by Hyperledger Fabric. 
   *  @param channelName  The channel name (not used in this method). 
   *  @return             String representation of the number of registered consumers.
   *  @throws             Throws an error if the SMC is not found in the ledger.
   */
  @Transaction(intent = Transaction.TYPE.EVALUATE)
  public String getRegisteredConsumersSize(Context ctx, final String channelName) {
    ChaincodeStub stub = ctx.getStub();
    // Retrieve the serialized SmartContractData (SMC) from the ledger
    String smcString = stub.getStringState(ChaincodeConstants.SMC);
    // If the SMC is missing or empty, handle the error
    if (smcString == null || smcString.isEmpty()) {
      ContractSMC.handleError("No asset in getRegisteredConsumersSize");
    }
    // Deserialize the SmartContractData from its JSON representation
    SmartContractData smc = ContractSMC.genson.deserialize(smcString, SmartContractData.class);
    ContractSMC.logger.info(smcString);
    // Get the serialized list of registered consumers from the SMC
    String regConsString = smc.getRegisteredConsumers();
    // Deserialize the consumer list into an ArrayList
    ArrayList<ConsumerData> regCons = ContractSMC.genson.deserialize(regConsString, new GenericType<ArrayList<ConsumerData>>() {});
    // Return the size of the registered consumers list as a string
    return String.valueOf(regCons.size());
  }
  /**
   *  getRegisteredProsumers - Returns registered prosumers list
   *  getRegisteredProsumers - Retrieves the list of registered prosumers.
   *  This method accesses the ledger to retrieve the serialized SmartContractData (SMC),
   *  deserializes it to extract the registered prosumers list, and returns it as a JSON string.
   *  @param ctx          The transaction context provided by the Hyperledger Fabric framework.
   *  @param channelName  The name of the channel (not used in this method, but may be relevant in others).
   *  @return             A JSON string representing the list of registered prosumers.
   *  @throws             Throws an error if the SMC is not found or is empty.
   */
  @Transaction(intent = Transaction.TYPE.EVALUATE)
  public String getRegisteredProsumers(Context ctx, final String channelName) {
    ChaincodeStub stub = ctx.getStub();
    // Retrieve the serialized SmartContractData (SMC) from the ledger
    String smcString = stub.getStringState(ChaincodeConstants.SMC);
    // Log the retrieved SMC for debugging purposes
    ContractSMC.logger.info(smcString);
    // If no SMC is found or it's empty, handle the error
    if (smcString == null || smcString.isEmpty()) {
      ContractSMC.handleError("No smc in getRegisteredProsumers");
    }
    // Deserialize the SMC JSON into a SmartContractData objec

    SmartContractData smc = ContractSMC.genson.deserialize(smcString, SmartContractData.class);
    // Log again after deserialization (optional, can be removed to avoid redundancy
    ContractSMC.logger.info(smcString);
    // Retrieve the serialized list of registered prosumers
    String regProsString = smc.getRegisteredProsumers();
    // Return the raw JSON string representing the registered prosumers list
    return regProsString;
  }
  /**
   *  getRegisteredProsumersSize - Return/Get the size of the registered prosumer list
   *  getRegisteredProsumersSize - Returns the number of registered prosumers.
   *  This read-only method retrieves the current state of the smart contract (SMC) from the ledger, 
   *  deserializes the list of registered prosumers, and returns its size.
   *  @param ctx          The Fabric transaction context.
   *  @param channelName  The name of the channel (not used in logic, but retained for compatibility).
   *  @return             A string representing the number of registered prosumers.
   *  @throws             An error if the smart contract state (SMC) is not found or is empty.
   */
  @Transaction(intent = Transaction.TYPE.EVALUATE)
  public String getRegisteredProsumersSize(Context ctx, final String channelName) {
    ChaincodeStub stub = ctx.getStub();
    // Retrieve the smart contract data from ledger
    String smcString = stub.getStringState(ChaincodeConstants.SMC);
    ContractSMC.logger.info(smcString);
    // If no smart contract data found, throw error
    if (smcString == null || smcString.isEmpty()) {
      ContractSMC.handleError("No asset in getRegisteredProsumersSize");
    }
    // Deserialize the smart contract data
    SmartContractData smc = ContractSMC.genson.deserialize(smcString, SmartContractData.class);
    ContractSMC.logger.info(smcString);
    // Deserialize the list of registered prosumers
    String regProsString = smc.getRegisteredProsumers();
    GenericType<ArrayList<ProsumerData>> mapType = new GenericType<ArrayList<ProsumerData>>() {};
    ArrayList<ProsumerData> regPros = ContractSMC.genson.deserialize(regProsString, mapType);
    // Return the size of the registered prosumer list
    return String.valueOf(regPros.size());
  }
  /**
   *  registeredConsumerSet - Depending if the consumer exists in the list of registered consumers, it replaces
   *  the existing consumers or adds consumer to the list of registered consumers
   *  Registers or updates a consumer in the list of registered consumers in the SmartContractData (SMC). 
   *  If the consumer with the given identifier (index `ic`) already exists in the list, 
   *  their data is updated (replaced). Otherwise, the new consumer is added to the list. 
   *  @param ctx           The Fabric transaction context 
   *  @param arg           Parameters passed as serialized strings 
   *  @param channelName   The channel name (not directly used in the logic) 
   *  @return              Updated SMC object as a JSON string
   */
  @Transaction(intent = Transaction.TYPE.SUBMIT)
  public String registeredConsumerSet(Context ctx, final String asset, final String channelName) {
    // Get the chaincode stub
    ChaincodeStub stub = ctx.getStub();
    // Variable to hold the incoming serialized consumer data
    String conn = "";
    conn = asset;
    // Fetch the current SmartContractData from ledger
    String smcString = stub.getStringState(ChaincodeConstants.SMC);
    ContractSMC.logger.info(smcString);
    // Handle missing SMC data
    if (smcString == null || smcString.isEmpty()) {
      ContractSMC.handleError("No smc in RegisteredConsumerSet");
    }
    // Deserialize SMC data
    SmartContractData smc = ContractSMC.genson.deserialize(smcString, SmartContractData.class);
    String conString = conn;
    // Deserialize incoming consumer
    ConsumerData con = ContractSMC.genson.deserialize(conString, ConsumerData.class);
    // Get existing registered consumers from SMC
    String cons = smc.getRegisteredConsumers();
    ArrayList<ConsumerData> regcons = ContractSMC.genson.deserialize(cons, new GenericType<ArrayList<ConsumerData>>() {});
    // Extract identifier (ic) of the new consumer
    String ij = con.getIc();
    Boolean flag = false;
    // Check if consumer already exists in list
    for (ConsumerData cd : regcons) {
      if (ij.equals(cd.getIc())) {
        flag = true;
        break;
      }
    }
    // Replace or add consumer
    if (flag) {
      regcons.set(ContractSMC.parseInteger(ij, ChaincodeConstants.asset_index), con);
    } else {
      regcons.add(con);
    }
    // Update consumer list in SMC
    conString = ContractSMC.genson.serialize(regcons);
    smc.setRegisteredConsumers(conString);
    // Serialize and store updated SMC
    smcString = ContractSMC.genson.serialize(smc);
    stub.putStringState(ChaincodeConstants.SMC, smcString);
    // Return updated SMC JSON string
    return smcString;
  }
  /**
   *  registeredProsumerSet - Depending if the prosumer exists in the list of registsered prosumers,
   *  it replaces the existing prosumers or adds consumer to the list of registered prosumers 
   *  Registers or updates a prosumer in the list of registered prosumers in the SmartContractData (SMC). 
   *  If a prosumer with the same identifier (`ip`) already exists, their data is updated. 
   *  Otherwise, the new prosumer is added to the list. 
   *  @param ctx           The Fabric transaction context. 
   *  @param arg           Parameters passed (e.g. JSON serialized ProsumerData). 
   *  @param channelName   The name of the Fabric channel (not used in logic). 
   *  @return              Updated SMC object as a JSON string.
   */
  @Transaction(intent = Transaction.TYPE.SUBMIT)
  public String registeredProsumerSet(Context ctx, final String asset, final String channelName) {
    // Get the stub for chaincode operations
    ChaincodeStub stub = ctx.getStub();
    // Variable to hold serialized prosumer JSON string
    String pross = "";
    pross = asset;
    // Get current SmartContractData state from ledger
    String smcString = stub.getStringState(ChaincodeConstants.SMC);
    ContractSMC.logger.info(smcString);
    // Handle missing SmartContractData
    if (smcString == null || smcString.isEmpty()) {
      ContractSMC.handleError("No smc in setRegisteredProsumer");
    }
    // Deserialize the SMC JSON into an object
    SmartContractData smc = ContractSMC.genson.deserialize(smcString, SmartContractData.class);
    // Deserialize the incoming prosumer string into an objec
    String prostring = pross;
    ProsumerData pro = ContractSMC.genson.deserialize(prostring, ProsumerData.class);
    // Deserialize the existing list of registered prosumers
    ArrayList<ProsumerData> regpros = ContractSMC.genson.deserialize(smc.getRegisteredProsumers(), new GenericType<ArrayList<ProsumerData>>() {});
    // Check if prosumer with same index (ip) exists
    String ij = pro.getIp();
    Boolean flag = false;
    for (ProsumerData pd : regpros) {
      if (ij.equals(pd.getIp())) {
        flag = true;
        break;
      }
    }
    // Replace or add prosumer
    if (flag) {
      regpros.set(ContractSMC.parseInteger(ij, ChaincodeConstants.asset_index), pro);
    } else {
      regpros.add(pro);
    }
    // Serialize updated list and update and save SMC
    prostring = ContractSMC.genson.serialize(regpros);
    smc.setRegisteredProsumers(prostring);
    smcString = ContractSMC.genson.serialize(smc);
    stub.putStringState(ChaincodeConstants.SMC, smcString);
    // Return updated SMC as JSON string
    return smcString;
  }
  /**
   *  validConsumersGet - Get/Receive registered consumers 
   *  validConsumersGet - Retrieves the list of currently registered consumers.
   *  This method accesses the smart contract state (SMC) stored on the ledger, deserializes it, 
   *  and returns the JSON-formatted string of registered consumers. It is used for evaluation 
   *  (read-only) purposes and does not modify the ledger.
   *  @param ctx          The transaction context provided by Hyperledger Fabric.
   *  @param arg          List of arguments.
   *  @param channelName  The name of the Fabric channel (included for compatibility, not used directly).
   *  @return             A JSON string representing the list of registered consumers.
   *  @throws             An error is thrown if the SMC is missing or empty.
   */
  @Transaction(intent = Transaction.TYPE.EVALUATE)
  public String validConsumersGet(Context ctx, final String channelName) {
    ChaincodeStub stub = ctx.getStub();
    // Retrieve the SmartContractData (SMC) from the ledger
    String smcString = stub.getStringState(ChaincodeConstants.SMC);
    ContractSMC.logger.info(smcString);
    // Check if the SMC data exists
    if (smcString == null || smcString.isEmpty()) {
      ContractSMC.handleError("No smc in validConsumersGet");
    }
    // Deserialize the SMC JSON string into a SmartContractData object
    SmartContractData smc = ContractSMC.genson.deserialize(smcString, SmartContractData.class);
    ContractSMC.logger.info(smcString);
    // Return the serialized list of registered consumers
    String valConsString = smc.getRegisteredConsumers();
    return valConsString;
  }
  /**
   *  event - Adds element to the ownership structure of prosumer/consumer. Order of the elements is arbitrary
   *  Adds a new energy ownership event to the ownership structure of a prosumer or consumer. 
   *  This method handles both insertion and modification of ownership records based on the 
   *  provided state and modify flag. If the `modifyN` flag is "true", an existing ownership 
   *  entry will be updated. Otherwise, a new entry will be added to the structure. 
   *  @param ctx          The transaction context 
   *  @param $arg         List of arguments (timestamp, value, actor name, state, index, contract state, modify flag) 
   *  @param channelName  The name of the channel to interact with other chaincodes 
   *  @return Updated smart contract state as a JSON string
   */
  @Transaction(intent = Transaction.TYPE.SUBMIT)
  public String event(Context ctx, final String name, final String timestamp, final String value, final String state, final String ij, final String modify, final String smcstring, final String channelName) {
    // Extract stub for blockchain access
    ChaincodeStub stub = ctx.getStub();
    Long tsN = 0L;
    String valueN = ChaincodeConstants.ZERO_DOUBLE;
    Integer ijN = 0;
    String stateN = "";
    Double pN = 0.0;
    String nameN = "";
    String smcStringN = null;
    String modifyN = ChaincodeConstants.FALSE_STRING;
    nameN = String.valueOf(name);
    tsN = Long.valueOf(timestamp);
    valueN = value;
    stateN = String.valueOf(state);
    ijN = Integer.valueOf(ij);
    modifyN = modify;
    smcStringN = smcstring;
    // Ensure smart contract data is present
    if (smcStringN == null || smcStringN.isEmpty()) {
      ContractSMC.handleError("No smc in event");
    }
    // Deserialize smart contract state
    SmartContractData smc = ContractSMC.genson.deserialize(smcStringN, SmartContractData.class);
    ContractSMC.logger.info(smcStringN);
    ContractSMC.logger.info("------In event------");
    // Handle events for prosumers
    if (nameN.equalsIgnoreCase(ChaincodeConstants.PROSUMER)) {
      ArrayList<ProsumerData> pros = ContractSMC.genson.deserialize(smc.getRegisteredProsumers(), new GenericType<ArrayList<ProsumerData>>() {});
      // Deserialize ownership structure for the specific prosumer
      String OpiString = pros.get(ijN).getOpiOwnershipStructure();
      ArrayList<EnergyOwnership> Opi = ContractSMC.genson.deserialize(OpiString, new GenericType<ArrayList<EnergyOwnership>>() {});
      // Handle energy injection case
      if (stateN.startsWith(ChaincodeConstants.inject)) {
        ContractSMC.logger.info("------In event inject Ei------" + valueN);

        if (modifyN.equalsIgnoreCase(ChaincodeConstants.TRUE_STRING)) {
          // Replace current injected energy with new value
          pros.get(ijN).setEi(valueN);
        } else {
          // Accumulate injected energy 
          pros.get(ijN).setEi(String.valueOf(ContractSMC.parseDouble(pros.get(ijN).getEi(), ChaincodeConstants.Ei) + ContractSMC.parseDouble(valueN, ChaincodeConstants.valueN)));
        }
      }
      // Create new ownership entry 
      EnergyOwnership opi = new EnergyOwnership(pros.get(ijN).getIp(), valueN, stateN, String.valueOf(tsN));
      // Modify or append the ownership entry
      if (modifyN.equalsIgnoreCase(ChaincodeConstants.TRUE_STRING)) {
        if (stateN.startsWith(ChaincodeConstants.inject)) {
          Opi.set(1, opi);
        }
      } else {
        boolean flag = true;
        if (stateN.startsWith(ChaincodeConstants.register)) {
          for (EnergyOwnership op : Opi) {
            if (op.getState().equals(ChaincodeConstants.register)) {
              flag = false;
              break;
            }
          }
        }
        if (flag) {
          Opi.add(opi);
        }
      }
      // Serialize updated ownership and update prosumer
      String assetSerial = ContractSMC.genson.serialize(Opi);
      pros.get(ijN).setOpiOwnershipStructure(assetSerial);
      // Update smart contract state
      String assetSerialized = ContractSMC.genson.serialize(pros);
      smc.setRegisteredProsumers(assetSerialized);
      smcStringN = ContractSMC.genson.serialize(smc);
      // Save state on ledger
      stub.putStringState(ChaincodeConstants.SMC, smcStringN);
      ContractSMC.logger.info("smc in event pros smc");
      ContractSMC.logger.info(smcStringN);
      return smcStringN;

    } else if (nameN.equalsIgnoreCase(ChaincodeConstants.CONSUMER)) {
      // Handle events for consumers
      ArrayList<ConsumerData> cons = ContractSMC.genson.deserialize(smc.getRegisteredConsumers(), new GenericType<ArrayList<ConsumerData>>() {});
      // Deserialize ownership structure
      String OcjString = cons.get(ijN).getOcjOwnershipStructure();
      ArrayList<EnergyOwnership> Ocj = ContractSMC.genson.deserialize(OcjString, new GenericType<ArrayList<EnergyOwnership>>() {});
      // Create new ownership entry
      EnergyOwnership ocj = new EnergyOwnership(cons.get(ijN).getIc(), valueN, stateN, String.valueOf(tsN));
      // Modify or append the entry
      if (modifyN.equalsIgnoreCase(ChaincodeConstants.TRUE_STRING)) {
        if (stateN.startsWith(ChaincodeConstants.purchased)) {
          for (int i = 1; i < Ocj.size(); i++) {
            if (Ocj.get(i).getState().equalsIgnoreCase(ChaincodeConstants.purchased)) {
              Ocj.set(i, ocj);
              break;
            }
          }
        }

      } else {
        Ocj.add(ocj);
      }
      String assetSerial = ContractSMC.genson.serialize(Ocj);
      cons.get(ijN).setOcjOwnershipStructure(assetSerial);
      // Update smart contract state
      String assetSerialized = ContractSMC.genson.serialize(cons);
      smc.setRegisteredConsumers(assetSerialized);
      smcStringN = ContractSMC.genson.serialize(smc);
      // Save to ledger
      stub.putStringState(ChaincodeConstants.SMC, smcStringN);
      ContractSMC.logger.info("smc in event cons smc");
      ContractSMC.logger.info(smcStringN);
      return smcStringN;
    }
    // Fallback if nameN is neither PROSUMER nor CONSUMER
    return null;
  }
  /**
   *  balancesConsumerSet - sets the balance of the ith consumer 
   *  Updates the balance of the specified (i-th) consumer and transfers the specified amount\n 
   *  to the SmartContractData’s balances array. 
   *  This function simulates a transfer of funds from a consumer to the central system 
   *  deducting from the consumer's balance and increasing the corresponding system balance. 
   *  @param ctx          Hyperledger Fabric transaction context 
   *  @param $arg         Loop-based input parameters: 
   *                      - numN: amount to be transferred from the consumer to the system 
   *                      - icN: index of the consumer in the list 
   *                      - smcStringN: serialized SmartContractData containing balances and consumers 
   *  @param channelName  Fabric channel name (not used in logic) 
   *  @return             Updated serialized SmartContractData (smcStringN)
   */
  @Transaction(intent = Transaction.TYPE.SUBMIT)
  public String balancesConsumerSet(Context ctx, final String num, final String ic, final String smcstring, final String channelName) {
    // Access Fabric chaincode stub
    ChaincodeStub stub = ctx.getStub();
    // Initialize input values
    String numN = ChaincodeConstants.ZERO_INT;
    String icN = ChaincodeConstants.ZERO_INT;
    String smcStringN = "";
    numN = num;
    icN = ic;
    smcStringN = smcstring;
    // Validate input SmartContractData
    if (smcStringN == null || smcStringN.isEmpty()) {
      ContractSMC.handleError("No smc in balancesConsumerSet");
    }
    // Deserialize SmartContractData, then balances and registered consumers
    SmartContractData smcc = ContractSMC.genson.deserialize(smcStringN, SmartContractData.class);
    ArrayList<Double> balances = ContractSMC.genson.deserialize(smcc.getBalances(), new GenericType<ArrayList<Double>>() {});
    String consString = smcc.getRegisteredConsumers();
    ArrayList<ConsumerData> cons = ContractSMC.genson.deserialize(consString, new GenericType<ArrayList<ConsumerData>>() {});
    // Takes amount of funds from consumer and transfer to SM
    cons.get(ContractSMC.parseInteger(icN, ChaincodeConstants.asset_index)).setBalancesC(String.valueOf(ContractSMC.parseDouble(cons.get(ContractSMC.parseInteger(icN, ChaincodeConstants.asset_index)).getBalancesC(), ChaincodeConstants.balance) - ContractSMC.parseDouble(numN, ChaincodeConstants.num)));
    if (balances.size() > ContractSMC.parseInteger(icN, ChaincodeConstants.asset_index)) {

      Double bal = ContractSMC.parseDouble(numN, ChaincodeConstants.num) + balances.get(ContractSMC.parseInteger(icN, ChaincodeConstants.asset_index));
      balances.set(ContractSMC.parseInteger(icN, ChaincodeConstants.asset_index), bal);

    } else {
      Double bal = ContractSMC.parseDouble(numN, ChaincodeConstants.num);
      balances.add(bal);
    }
    // Serialize updated consumers and balances
    smcc.setRegisteredConsumers(ContractSMC.genson.serialize(cons));
    smcc.setBalances(ContractSMC.genson.serialize(balances));
    // Serialize updated SMC and store back on the ledger
    smcStringN = ContractSMC.genson.serialize(smcc);
    stub.putStringState(ChaincodeConstants.SMC, smcStringN);
    // Return updated SmartContractData
    return smcStringN;
  }
  /**
   *  orderElements - Compress all items of ownership structure list which state is "injected" to only one
   *  entry that has combined all the injected energy of registered prosumers
   *  orderElements - Consolidates multiple 'injected' entries in the energy ownership structure of each registered prosumer. 
   *  This function loops through all registered prosumers and: 
   *  - Merges all ownership records with state "injected" into a single entry at index 1 
   *  - Accumulates the total amount of injected energy into this single entry 
   *  - Sets the timestamp of this entry to the provided timestamp 
   *  - Removes all other 'injected' entries from the structure 
   *  @param ctx         The Fabric transaction context. 
   *  @param $arg        Template input containing timestamp and SmartContractData string. 
   *  @param channelName The channel name (not used in this method but kept for template compatibility). 
   *  @return            Serialized updated SmartContractData object. 
   */
  @Transaction(intent = Transaction.TYPE.SUBMIT)
  public String orderElements(Context ctx, final String timestamp, final String smcstring, final String channelName) {
    // order elements
    ChaincodeStub stub = ctx.getStub();
    // Initialize timestamp and smart contract data string


    String ts = ChaincodeConstants.ZERO_INT;
    String smcString;
    ts = timestamp;
    smcString = smcstring;
    // Deserialize the SmartContractData
    SmartContractData smc = ContractSMC.genson.deserialize(smcString, SmartContractData.class);
    // Get registered prosumers
    String prosString = smc.getRegisteredProsumers();
    if (prosString == null || prosString.isEmpty()) {
      ContractSMC.handleError("No registered prosumers in orderElements");
    }
    ContractSMC.logger.info("----in order elements pros:--");
    ContractSMC.logger.info(prosString);
    ArrayList<ProsumerData> pros = ContractSMC.genson.deserialize(prosString, new GenericType<ArrayList<ProsumerData>>() {});
    ArrayList<EnergyOwnership> del = new ArrayList<EnergyOwnership>();
    // Process each prosumer
    int size = pros.size();
    for (int ii = 0; ii < size; ii++) {
      ProsumerData pro = pros.get(ii);
      String OpiString = pro.getOpiOwnershipStructure();
      ArrayList<EnergyOwnership> Opi = ContractSMC.genson.deserialize(OpiString, new GenericType<ArrayList<EnergyOwnership>>() {});
      // Compress all "injected" entries into the one at index 1
      for (int i = Opi.size() - 1; i > 1; i--) {
        if (Opi.get(i).getState().toLowerCase(Locale.ROOT).startsWith(ChaincodeConstants.inject)) {
          Opi.get(1).setAmount(String.valueOf(ContractSMC.parseDouble(Opi.get(1).getAmount(), ChaincodeConstants.Op) + ContractSMC.parseDouble(Opi.get(i).getAmount(), ChaincodeConstants.Op)));
          Opi.get(1).setTimestamp(ts);
          del.add(Opi.get(i));
          ContractSMC.logger.info("----in order elements del--");
          ContractSMC.logger.info(prosString);
        }
      }
      // Remove old injected entries
      Opi.removeAll(del);
      del = new ArrayList<EnergyOwnership>();
      String assetSerial = ContractSMC.genson.serialize(Opi);
      pro.setOpiOwnershipStructure(assetSerial);
    }
    // Do serializations and finally same new smc asset
    String assetSerialized = ContractSMC.genson.serialize(pros);
    smc.setRegisteredProsumers(assetSerialized);
    assetSerialized = ContractSMC.genson.serialize(smc);
    stub.putStringState(ChaincodeConstants.SMC, assetSerialized);
    return assetSerialized;
  }

}
