package EnergyDSLModels.EnergyTradingAlgorithmFabric;

/*Generated by MPS */

import org.hyperledger.fabric.contract.annotation.Contract;
import org.hyperledger.fabric.contract.annotation.Default;
import org.hyperledger.fabric.contract.ContractInterface;
import com.owlike.genson.Genson;
import org.hyperledger.fabric.Logger;
import java.util.Map;
import java.util.function.Function;
import EnergyDSL.runtime.ProsumerData;
import EnergyDSL.runtime.ConsumerData;
import EnergyDSL.runtime.DSOData;
import EnergyDSL.runtime.ContractAsset;
import org.hyperledger.fabric.shim.ChaincodeException;
import EnergyDSL.runtime.ChaincodeConstants;
import java.util.Locale;
import java.util.ArrayList;
import org.hyperledger.fabric.contract.annotation.Transaction;
import org.hyperledger.fabric.contract.Context;
import org.hyperledger.fabric.shim.ChaincodeStub;
import com.owlike.genson.GenericType;
import org.hyperledger.fabric.shim.Chaincode;
import EnergyDSL.runtime.SmartContractData;
import java.util.Date;
import java.util.HashMap;
import EnergyDSL.runtime.EnergyOwnership;

@Contract(name = "energytrading")
@Default
public class ContractEnergyTrading implements ContractInterface {

  private static final Genson genson = new Genson();
  private static final Logger logger = Logger.getLogger("contractLogger");
  public static final Map<String, Function<ProsumerData, String>> PROSUMER_PROPERTIES = Map.ofEntries(Map.entry("balancesp", ProsumerData::getBalancesP), Map.entry("ip", ProsumerData::getIp), Map.entry("opiownershipstructure", ProsumerData::getOpiOwnershipStructure), Map.entry("smi", ProsumerData::getSmi), Map.entry("sit", ProsumerData::getSit), Map.entry("ei", ProsumerData::getEi));
  public static final Map<String, Function<ConsumerData, String>> CONSUMER_PROPERTIES = Map.ofEntries(Map.entry("balancesc", ConsumerData::getBalancesC), Map.entry("ic", ConsumerData::getIc), Map.entry("ocjownershipstructure", ConsumerData::getOcjOwnershipStructure), Map.entry("djt", ConsumerData::getDjt), Map.entry("dmj", ConsumerData::getDmj));
  public static final Map<String, Function<DSOData, String>> DSO_PROPERTIES = Map.ofEntries(Map.entry("est", DSOData::getESt), Map.entry("dsoid", DSOData::getDsoId), Map.entry("edt", DSOData::getEDt), Map.entry("rt", DSOData::getRt), Map.entry("dt", DSOData::getDt), Map.entry("q", DSOData::getQ), Map.entry("pcon", DSOData::getPcon), Map.entry("k", DSOData::getK), Map.entry("pt", DSOData::getPt), Map.entry("deltat", DSOData::getDeltat), Map.entry("pbalance", DSOData::getPbalance));
  /**
   *  Retrieves a specific property value from a asset object based on the given property name. 
   *  The property name matching is case-insensitive. 
   *  Returns null if the asset object is null or the property name is unrecognized. 
   *  @param assetObject the object from which to retrieve the property 
   *  @param propName the name of the property to retrieve (e.g., "smi", "est", "balancep") 
   *  @return the value of the specified property as a String, or null if the property is unknown or asset is null
   * 
   */
  public static String getAssetProperty(final ContractAsset asset, final String propName) {
    if (asset == null || propName == null) {
      return null;
    }
    String prop = propName.toLowerCase();
    if (asset instanceof ProsumerData) {
      ProsumerData prosumer = (ProsumerData) asset;
      Function<ProsumerData, String> fn = PROSUMER_PROPERTIES.get(prop);
      return (fn != null ? fn.apply(prosumer) : null);
    } else
    if (asset instanceof ConsumerData) {
      ConsumerData consumer = (ConsumerData) asset;
      Function<ConsumerData, String> fn = CONSUMER_PROPERTIES.get(prop);
      return (fn != null ? fn.apply(consumer) : null);
    } else
    if (asset instanceof DSOData) {
      DSOData dso = (DSOData) asset;
      Function<DSOData, String> fn = DSO_PROPERTIES.get(prop);
      return (fn != null ? fn.apply(dso) : null);
    }
    return null;
  }
  /**
   * Represents safe checked type cast
   * 
   * @param asset Contract asset to be cast
   * @param expectedType Type of the asset class
   * @param <T> generic type parameter
   * @throws ChaincodeException if asset is null or not of the expected type
   * @return Casted asset
   */
  public static <T extends ContractAsset> T castAsset(ContractAsset asset, Class<T> expectedType) {
    if (asset == null || !(expectedType.isInstance(asset))) {
      if (asset == null) {
        handleError("Asset is null", ChaincodeConstants.TYPE_MISMATCH);
      }

      handleError("Asset is of type " + asset.getClass().getSimpleName() + ", expected " + expectedType.getSimpleName(), ChaincodeConstants.TYPE_MISMATCH);
    }
    return expectedType.cast(asset);
  }
  /**
   * Represents safe parsing integer numbers
   * 
   * @param value String value that needs to be parsed into Integer
   * @param fieldName Name of the field
   * @throws ChaincodeException if value is null or not a valid 
   * @return Parsed Integer value 
   */
  public static Integer parseInteger(String value, String fieldName) {
    try {
      return Integer.parseInt(value);
    } catch (NumberFormatException e) {
      handleError("Invalid integer for " + fieldName + ": " + value, ChaincodeConstants.PARSE_ERROR);
      return null;
    }
  }
  /**
   * Represents safe parsing double numbers
   * 
   * @param value String value that needs to be parsed into Double
   * @param fieldName Name of the field
   * @throws ChaincodeException if value is null or not a valid 
   * @return Parsed Double value 
   */
  public static Double parseDouble(String value, String fieldName) {
    try {

      return Double.parseDouble(value);
    } catch (NumberFormatException e) {
      handleError("Invalid double for " + fieldName + ": " + value, ChaincodeConstants.PARSE_ERROR);
      return null;
    }
  }
  /**
   * Represents safe parsing long numbers
   * 
   * @param value String value that needs to be parsed into Long
   * @param fieldName Name of the field
   * @throws ChaincodeException if value is null or not a valid 
   * @return Parsed Long Integer value 
   */
  public static Long parseLong(String value, String fieldName) {
    try {
      return Long.parseLong(value);
    } catch (NumberFormatException e) {
      handleError("Invalid Long integer for " + fieldName + ": " + value, ChaincodeConstants.PARSE_ERROR);
      return null;
    }
  }
  /**
   *  Validates that the provided value is a non-negative number. 
   *  This utility method ensures that a given numeric value (provided as a String, Double, or Integer) 
   *  is not negative. It throws a chaincode exception if the value is negative or of an unsupported type. 
   *  @param value      the value to be validated; can be a String, Double, or Integer (mostly String) 
   *  @param fieldName  the name of the field associated with the value (used in error messages). 
   *  @throws ChaincodeException if the value is negative or of an unsupported type.
   */
  public static void validatePositiveNumber(Object value, String fieldName) {
    double number = 0.0;
    // Convert the value to a double based on its type
    if (value instanceof String) {
      number = parseDouble((String) value, ChaincodeConstants.num);
    } else if (value instanceof Double) {
      number = ((Double) value);
    } else if (value instanceof Integer) {
      number = ((Integer) value).doubleValue();
    } else {
      // Unsupported type provided
      handleError("Unsupported type for " + fieldName);
    }
    // Validate the number is not negative
    if (number < 0) {
      handleError(fieldName + "must not be negative. Value is: " + value);
    }
  }
  /**
   *  Rounds down a given timestamp (in milliseconds) to the nearest 15-minute interval. 
   *  This method is useful for aligning timestamps to discrete intervals, such as those used in  
   *  energy trading or time-series aggregation, where data needs to be grouped into uniform time slots. 
   *  @param timeInMillis the original timestamp in milliseconds (e.g., System.currentTimeMillis()). 
   *  @return the timestamp (in milliseconds) rounded down to the previous 15-minute boundary. 
   *  Example: If the input is 10:17 AM, the result will be 10:15 AM.
   * 
   */
  public static Long roundDownTo15Minutes(Long timeInMillis) {
    // Convert milliseconds to total minutes
    Long mins = timeInMillis / (ChaincodeConstants.MILLISECONDS_IN_MINUTE);
    // Round down to the nearest 15-minute interval and convert back to milliseconds
    return (mins / ChaincodeConstants.FIFTEEN_MINUTES) * ChaincodeConstants.FIFTEEN_MINUTES * ChaincodeConstants.MILLISECONDS_IN_MINUTE;
  }
  /**
   *  Rounds up a given timestamp (in milliseconds) to the nearest 15-minute interval. 
   *  This function is used to ensure that time values align with the next quarter-hour mark, while leaving 
   * timestamps that are already aligned unchanged.
   *  This  is particularly useful in scheduling, forecasting, and aggregating data into uniform time windows. 
   *  @param timeInMillis the original timestamp in milliseconds (e.g., System.currentTimeMillis()). 
   *  @return the timestamp (in milliseconds) rounded up to the next 15-minute boundary. 
   *  Example: If the input is 10:17 AM, the result will be 10:30 AM. 
   *  If the input is exactly on a 15-minute boundary (e.g., 10:15 AM), it will remain unchanged
   */
  public static Long roundUpTo15Minutes(Long timeInMillis) {
    // Convert milliseconds to total minutes
    Long mins = timeInMillis / (ChaincodeConstants.MILLISECONDS_IN_MINUTE);
    // If already on a 15-minute boundary, keep it; otherwise round up to the next one
    return (((mins % ChaincodeConstants.FIFTEEN_MINUTES) == 0 ? mins : mins + (ChaincodeConstants.FIFTEEN_MINUTES - (mins % ChaincodeConstants.FIFTEEN_MINUTES)))) * ChaincodeConstants.MILLISECONDS_IN_MINUTE;
  }
  /**
   *  Handles an error by logging it and throwing a ChaincodeException. 
   *  This utility method is used to handle errors in a consistent way across the smart contract. 
   *  It prints the error message to the standard error stream and throws a code ChaincodeException 
   *  to halt execution and signal failure to the Hyperledger Fabric runtime.
   *  This method is a convenience overload that uses a default error code. 
   *  @param message the error message to be logged and included in the thrown exception. 
   *  @throws ChaincodeException always thrown with the provided message and default code.
   */
  public static void handleError(String message) {
    // Call the overload method
    handleError(message, ChaincodeConstants.GENERAL_ERROR);

  }
  /**
   *  Handles errors by logging the message with a specific error code and throwing a ChaincodeException.
   *  This method allows for more granular error categorization, which is useful for debugging and client-side handling.
   *  @param message The error message to log and include in the exception.
   *  @param code    A string representing the error category or code (e.g., "VALIDATION_ERROR", "CHAINCODE_INVOKE_ERROR")
   *  @throws ChaincodeException always thrown with the provided message and code. 
   */
  public static void handleError(String message, String code) {
    // Log the error message and code
    logger.error("[" + code + "] " + message);
    // Throw a chaincode exception with the message and code
    throw new ChaincodeException(message, code);

  }
  /**
   *  Deserializes a JSON string into a specific type of ContractAsset based on the asset type. 
   *  This method is used to convert a JSON representation of an asset into its corresponding 
   *  Java object subclass (ProsumerData, ConsumerData, or DSOData), which implements the ContractAsset interface. 
   *  If the asset type is unknown, a  ChaincodeException is thrown. 
   *  @param assetType the type of the asset (e.g., "prosumer", "consumer", or "dso"); case-insensitive. 
   *  @param assetJSON the JSON string representing the asset.
   *  @return a deserialized object of type ContractAsset corresponding to the asset type. 
   *  @throws ChaincodeException if the asset type is not recognized.
   */
  private static ContractAsset deserializeAsset(String assetType, String assetJSON) {
    // Normalize the asset type string to lowercase and determine the correct class for deserialization
    switch (assetType.toLowerCase(Locale.ROOT)) {
      case ChaincodeConstants.PROSUMER:
        return genson.deserialize(assetJSON, ProsumerData.class);
      case ChaincodeConstants.CONSUMER:
        return genson.deserialize(assetJSON, ConsumerData.class);
      case ChaincodeConstants.DSO:
        return genson.deserialize(assetJSON, DSOData.class);
      default:
        // If the type is unrecognized, throw an error to stop execution
        throw new ChaincodeException("Unknown asset type: " + assetType);
    }
  }
  /**
   *  Updates the properties of a given ContractAsset using key-value pairs from a list of arguments. 
   *  The method expects the argument list to contain pairs in the format:  
   *  [value1, setKey1, value2, setKey2, ...], where each `setKey` should start with "set". 
   *  <p>If the list has two or fewer elements, no updates are performed. Each key is normalized by  
   *  removing the "set" prefix and lowercasing the remainder before passing it to the asset's  
   *  updateProperty} method. 
   *  @param asset the asset whose properties are to be updated 
   *  @param args  a list of alternating values and setter keys (e.g., "100", "setBalance")
   */
  private static void updateAssetProperties(ContractAsset asset, ArrayList<String> args) {
    // If the list doesn't contain enough pairs to update, exit early
    int size = args.size();
    if (size <= 2) {
      return;
    }
    // Iterate over the list in steps of two (value and key)
    for (int i = 0; i < size - 1; i = i + 2) {
      String value = args.get(i);
      String setKey = args.get(i + 1).toLowerCase(Locale.ROOT);
      // Check if the key starts with "set"
      if (setKey.startsWith(ChaincodeConstants.SETTER_PREFIX)) {
        // Remove the "set" prefix to extract the actual property name
        setKey = setKey.substring(3);
        // Update the property on the asset with the given value
        asset.updateProperty(setKey, value);
      }
    }
  }
  /**
   *  Creates or updates an asset on the ledger based on its type and provided JSON and arguments. 
   *  <p>This method:
   *  <ul> 
   *    <li>Deserializes a JSON string into an asset object based on the provided asset type.</li> 
   *    <li>Updates the asset’s properties using a list of key-value pairs.</li> 
   *    <li>Determines a unique asset name (key) based on the asset type and identifier field.</li> 
   *    <li>Stores the updated asset back to the ledger using  ChaincodeStub#putStringState}.</li> 
   *  </ul> 
   *  If assetString  is null, the method returns null without making any changes.</p> 
   *  @param ctx         the transaction context, providing access to the chaincode stub 
   *  @param assetType   the type of asset ("prosumer", "consumer", or "dso") 
   *  @param assetString the JSON string representing the asset object\n 
   *  @param args        a JSON-formatted list of alternating values and setter keys to update the asset 
   *  @return            the updated and serialized asset as a JSON string 
   *  @throws ChaincodeException if asset type is unknown or if any internal logic fails
   */
  @Transaction(intent = Transaction.TYPE.SUBMIT)
  public static String setAsset(Context ctx, final String assetType, final String assetString, final String args) {
    // Obtain stub to interact with ledger state
    ChaincodeStub stub = ctx.getStub();
    // Deserialize arguments from JSON into a list of strings
    ArrayList<String> argsList = genson.deserialize(args, new GenericType<ArrayList<String>>() {});
    String assetSerialized;
    String name;
    // If the asset string is null, skip processing, throw error
    if (assetString == null) {
      handleError("No asset", ChaincodeConstants.INVALID_ASSET_INPUT);
    }
    // Deserialize the JSON string based on its type into specific asset object
    ContractAsset asset = deserializeAsset(assetType, assetString);
    // Update the asset's fields based on the key-value argument pairs
    updateAssetProperties(asset, argsList);

    // Generate a unique name (key) for storing in the ledger
    if (assetType.toLowerCase(Locale.ROOT).contains(ChaincodeConstants.PROSUMER)) {
      name = ChaincodeConstants.PREFIX_PROSUMER + ((ProsumerData) asset).getIp();
    } else if (assetType.toLowerCase(Locale.ROOT).contains(ChaincodeConstants.CONSUMER)) {
      name = ChaincodeConstants.PREFIX_CONSUMER + ((ConsumerData) asset).getIc();
    } else {
      name = ChaincodeConstants.DSO;
    }
    // Serialize the updated asset back into JSON format
    assetSerialized = genson.serialize(asset);
    // Store the asset state on the ledger using the determined key
    stub.putStringState(name, assetSerialized);
    // Return the serialized string
    return assetSerialized;
  }
  /**
   * * Validates that specific index is within the valid range
   * 
   * @param index the index to validate
   * @param size the size of the collection
   */
  public static void validateIndex(int index, int size) {
    if (index < 0 || index >= size) {
      handleError("Invalid index: " + index, ChaincodeConstants.INDEX_ERROR);
    }
  }

  /**
   *  oneSet - Sets or updates the value of an asset in the ledger. 
   *  This method stores the provided string value under the specified asset name key. 
   *  If the key already exists, its value is overwritten.\n *\n 
   *  @param ctx         The transaction context provided by Hyperledger Fabric. 
   *  @param name        The key (asset name) to be created or updated in the ledger. 
   *  @param value       The new string value to associate with the given key. 
   *  @param channelName The name of the channel on which the transaction is submitted (not used in this method).
   *  @return            A confirmation string in the format "name: value".
   */
  @Transaction(intent = Transaction.TYPE.SUBMIT)
  public String oneSet(Context ctx, final String name, final String value, final String channelName) {
    // Get the stub for accessing ledger state
    ChaincodeStub stub = ctx.getStub();
    // Write the new value to the ledger under the given key
    stub.putStringState(name, value);
    // Log the update operation
    ContractEnergyTrading.logger.info(name + ": " + value);
    // Return a confirmation message
    return name + ": " + value;
  }
  /**
   *  oneGet - Retrieves the value of a specific asset stored in the ledger
   *  If the asset is not found (i.e., no value exists for the given key), an error is handled
   *  through a custom error handler defined in the contrac 
   *  @param ctx         The transaction context provided by Hyperledger Fabric.
   *  @param name        The key (asset name) whose value is to be retrieved. 
   *  @param channelName The name of the channel on which the transaction is evaluated (not used in this method). 
   *  @return            The string value associated with the given key.
   */
  @Transaction(intent = Transaction.TYPE.EVALUATE)
  public String oneGet(Context ctx, final String name, final String channelName) {
    // Get the stub to access ledger state
    ChaincodeStub stub = ctx.getStub();
    // Retrieve the value for the given key
    String value = stub.getStringState(name);
    // If the asset doesn't exist or is empty, handle the error
    if (value == null || value.isEmpty()) {
      ContractEnergyTrading.handleError("No asset: " + name);
    }
    // Return the asset value
    return value;
  }
  /**
   *  deleteAsset - Deletes the asset
   *  Deletes a specific asset from the world state by its key. 
   *  This transaction is used to remove an asset from the ledger permanently.
   *  It performs a simple deletion operation using the provided asset name. 
   *  @param ctx         The transaction context from Hyperledger Fabric.
   *  @param name        The name (key) of the asset to be deleted.
   *  @param channelName The channel name (currently unused, but preserved for interface consistency) 
   *  @return            A confirmation message indicating the asset has been deleted. 
   *  
   */
  @Transaction(intent = Transaction.TYPE.SUBMIT)
  public String deleteAsset(Context ctx, String name, final String channelName) {
    // Retrieve the stub for interacting with the ledger
    ChaincodeStub stub = ctx.getStub();
    // Delete the state associated with the given asset name
    stub.delState(name);
    // Log the deletion
    ContractEnergyTrading.logger.info(name + " is deleted");
    // Return confirmation message
    return name + " is deleted";
  }
  /**
   *  energyTrading - Initializes all the participant in the energy trading and all necessary parameters
   *  Initializes participants (consumers, prosumers, DSO) and parameters for energy trading.
   *  This function prepares the energy trading environment by:
   *  - Parsing and validating parameters such as number of participants, their balances, and trading constants.
   *  - Calling external smart contracts to retrieve and update state (e.g., DSO and SMC).
   *  - Creating consumer and prosumer assets, and storing them on the ledger.
   *  - Updating the DSO and SMC objects with initial state.
   *  The result contains the timestamp, startDate, and endDate for the trading session.
   *  @param ctx          the transaction context
   *  @param arg         the dynamic argument list containing initialization values
   *  @param channelName  the name of the Fabric channel where contracts are invoked
   *  @return a JSON string containing the timestamp, start date, and end date of the initialized trading session
   */
  @Transaction(intent = Transaction.TYPE.SUBMIT)
  public String energyTrading(Context ctx, final String ic, final String ip, final String balancesC, final String balancesP, final String pmax, final String dsoID, final String pBalance, final String pcon, final String k, final String channelName) {
    ChaincodeStub stub = ctx.getStub();
    // Initialize variables
    Integer icN = 0;
    Integer ipN = 0;
    String smcString = null;
    String dsoString = null;
    String dsoIdN = ChaincodeConstants.DSO_ID;
    String pmaxN = ChaincodeConstants.PMAX;
    ArrayList<Double> balancesCN = new ArrayList<Double>();
    ArrayList<Double> balancesPN = new ArrayList<Double>();
    String PbalanceN = ChaincodeConstants.PBALANCE;
    String pconN = ChaincodeConstants.PCON;
    String kN = ChaincodeConstants.K;
    icN = Integer.valueOf(ic);
    ipN = Integer.valueOf(ip);
    balancesCN = ContractEnergyTrading.genson.deserialize(balancesC, new GenericType<ArrayList<Double>>() {});
    balancesPN = ContractEnergyTrading.genson.deserialize(balancesP, new GenericType<ArrayList<Double>>() {});
    pmaxN = pmax;
    dsoIdN = dsoID;
    PbalanceN = pBalance;
    pconN = pcon;
    kN = k;
    // Validate numeric inputs
    ContractEnergyTrading.validatePositiveNumber(pmaxN, ChaincodeConstants.Pmax);
    ContractEnergyTrading.validatePositiveNumber(PbalanceN, ChaincodeConstants.Pbalance);
    ContractEnergyTrading.validatePositiveNumber(pconN, ChaincodeConstants.Pcon);
    ContractEnergyTrading.validatePositiveNumber(kN, ChaincodeConstants.K);
    ContractEnergyTrading.validatePositiveNumber(icN, ChaincodeConstants.num);
    ContractEnergyTrading.validatePositiveNumber(ipN, ChaincodeConstants.num);

    // Validate each consumer balance
    for (int i = 0; i < balancesCN.size(); i++) {
      ContractEnergyTrading.validatePositiveNumber(balancesCN.get(i), "Balance for Consumers at index " + i);
    }
    for (int i = 0; i < balancesPN.size(); i++) {
      ContractEnergyTrading.validatePositiveNumber(balancesPN.get(i), "Balance for Prosumers at index " + i);
    }

    Chaincode.Response response = null;
    // Call the smart contract to retrieve current SmartContractData (SMC)
    response = stub.invokeChaincodeWithStringArgs(ChaincodeConstants.smcContract, ChaincodeConstants.smcGet, channelName);
    if (response.getStatusCode() != ChaincodeConstants.SUCCESS_STATUS) {
      ContractEnergyTrading.handleError("Error invoking smcGet: " + response.getMessage());
    }
    smcString = response.getStringPayload();
    if (smcString == null || smcString.isEmpty()) {
      smcString = ChaincodeConstants.empty_json_string;
    }
    SmartContractData smc = ContractEnergyTrading.genson.deserialize(smcString, SmartContractData.class);
    // Retrieve DSO asset from DSO contract
    response = stub.invokeChaincodeWithStringArgs(ChaincodeConstants.dsoContract, ChaincodeConstants.dsoGet, channelName);
    if (response.getStatusCode() != ChaincodeConstants.SUCCESS_STATUS) {
      ContractEnergyTrading.handleError("Error invoking dsoGet: " + response.getMessage());
    }
    dsoString = response.getStringPayload();
    if (dsoString == null || dsoString.isEmpty()) {
      dsoString = ChaincodeConstants.empty_json_string;
    }
    DSOData dso = ContractEnergyTrading.genson.deserialize(dsoString, DSOData.class);
    ArrayList<ConsumerData> cons = new ArrayList<ConsumerData>();
    ArrayList<ProsumerData> pros = new ArrayList<ProsumerData>();
    Long timestamp = ((new Date().getTime() + ChaincodeConstants.MILLISECONDS_IN_MINUTE - 1) / (ChaincodeConstants.MILLISECONDS_IN_MINUTE)) * ChaincodeConstants.MILLISECONDS_IN_MINUTE;
    Long startDateN = ContractEnergyTrading.roundDownTo15Minutes(timestamp);
    Long endDateN = ContractEnergyTrading.roundUpTo15Minutes(timestamp);
    // Create and register consumers
    for (int i = 0; i < icN; i++) {
      ConsumerData cd = new ConsumerData();
      cd.setIc(String.valueOf(i));
      cd.setBalancesC(String.valueOf(balancesCN.get(i)));
      cons.add(cd);
      ArrayList<String> args = new ArrayList<String>();
      ContractEnergyTrading.logger.info(ContractEnergyTrading.genson.serialize(cd));
      ContractEnergyTrading.logger.info("cd");
      response = stub.invokeChaincodeWithStringArgs(ChaincodeConstants.consumerContract, ChaincodeConstants.setAsset, ChaincodeConstants.CONSUMER, ContractEnergyTrading.genson.serialize(cd), ContractEnergyTrading.genson.serialize(args), channelName);
      if (response.getStatusCode() != ChaincodeConstants.SUCCESS_STATUS) {
        ContractEnergyTrading.handleError("Error invoking consumer setAsset " + response.getMessage());
      }
    }
    // Create and register prosumers
    for (int j = 0; j < ipN; j++) {
      ProsumerData pd = new ProsumerData();
      pd.setIp(String.valueOf(j));
      pd.setBalancesP(ContractEnergyTrading.genson.serialize(balancesPN.get(j)));
      pros.add(pd);
      ArrayList<String> args = new ArrayList<String>();
      ContractEnergyTrading.logger.info(ContractEnergyTrading.genson.serialize(pd));
      ContractEnergyTrading.logger.info("pd");
      response = stub.invokeChaincodeWithStringArgs(ChaincodeConstants.prosumerContract, ChaincodeConstants.setAsset, ChaincodeConstants.PROSUMER, ContractEnergyTrading.genson.serialize(pd), ContractEnergyTrading.genson.serialize(args), channelName);
      if (response.getStatusCode() != ChaincodeConstants.SUCCESS_STATUS) {
        ContractEnergyTrading.handleError("Error invoking prosumer setAsset " + response.getMessage());
      }

    }
    // Log and serialize consumer and prosumer collections
    String consS = ContractEnergyTrading.genson.serialize(cons);
    String prosS = ContractEnergyTrading.genson.serialize(pros);
    ContractEnergyTrading.logger.info(consS);
    // Update and serialize DSO object
    dso.setDsoId(dsoIdN);
    dso.setPbalance(PbalanceN);
    dso.setPcon(pconN);
    dso.setK(kN);
    dsoString = ContractEnergyTrading.genson.serialize(dso);
    ContractEnergyTrading.logger.info(dsoString);
    if (dsoString == null || dsoString.isEmpty()) {
      ContractEnergyTrading.handleError("No dso");

    } else {
      response = stub.invokeChaincodeWithStringArgs(ChaincodeConstants.dsoContract, ChaincodeConstants.dsoSet, dsoString, channelName);
    }
    // Update SMC with the new setup and write it back
    smc.setInitCons(consS);
    smc.setInitPros(prosS);
    smc.setDsoId(dsoIdN);
    smc.setBalances(ChaincodeConstants.empty_array_string);
    smc.setPmax(pmaxN);
    smcString = ContractEnergyTrading.genson.serialize(smc);
    ContractEnergyTrading.logger.info(smcString);
    try {
      response = stub.invokeChaincodeWithStringArgs(ChaincodeConstants.smcContract, ChaincodeConstants.smcSet, smcString, channelName);
    } catch (Exception e) {
      ContractEnergyTrading.handleError("Error in writing smc in energytrading: " + e.getMessage());
    }
    // Return trading session metadata (timestamp, start and end date)
    Map<String, Object> resultMap = new HashMap<>();
    resultMap.put(ChaincodeConstants.timestamp, timestamp);
    resultMap.put(ChaincodeConstants.startDate, startDateN);
    resultMap.put(ChaincodeConstants.endDate, endDateN);
    return ContractEnergyTrading.genson.serialize(resultMap);
  }
  /**
   *  register - Registers consumers and prosumers in the network
   *  Registers a specified number of consumers and prosumers into the network.
   *  <p>
   *  This method:
   *  <ul>
   *    <li>Fetches the current SmartContractData state.</li>
   *    <li>Iterates over the specified number of consumers and prosumers, invoking their respective contracts.</li>
   *    <li>Updates their ownership structure and triggers related events.</li>
   *    <li>Updates the SmartContractData and persists it.</li> 
   *  </ul>
   *  @param ctx The transaction context.
   *  @param arg Encoded strings representing the number of consumers, prosumers and timestamps.
   *  @param channelName The name of the Fabric channel used to invoke other contracts.
   *  @return Updated SmartContractData JSON string after registration.
   */
  @Transaction(intent = Transaction.TYPE.SUBMIT)
  public String register(Context ctx, final String ic, final String ip, final String timestamp, final String startDate, final String endDate, final String channelName) {
    ChaincodeStub stub = ctx.getStub();
    Chaincode.Response response = null;
    Integer icN = 0;
    Integer ipN = 0;
    String consString = ChaincodeConstants.empty_json_string;
    String prosString = ChaincodeConstants.empty_json_string;
    String smcString;
    // Invoke the SMC contract to get the current SmartContractData
    response = stub.invokeChaincodeWithStringArgs(ChaincodeConstants.smcContract, ChaincodeConstants.smcGet, "energy");
    if (response.getStatusCode() != ChaincodeConstants.SUCCESS_STATUS) {
      ContractEnergyTrading.handleError("Error invoking smcGet in register" + response.getMessage());
    }
    smcString = response.getStringPayload();
    // Generate and get aligned timestamps
    Long nowDate = ((new Date().getTime() + ChaincodeConstants.MILLISECONDS_IN_MINUTE - 1) / (ChaincodeConstants.MILLISECONDS_IN_MINUTE)) * ChaincodeConstants.MILLISECONDS_IN_MINUTE;
    String timestampN = String.valueOf(nowDate);
    String startDateN = String.valueOf(ContractEnergyTrading.roundDownTo15Minutes(nowDate));
    String endDateN = String.valueOf(ContractEnergyTrading.roundUpTo15Minutes(nowDate));
    icN = Integer.valueOf(ic);
    ipN = Integer.valueOf(ip);
    timestampN = timestamp;
    startDateN = startDate;
    endDateN = endDate;
    // Validate that all numeric inputs are not negative
    ContractEnergyTrading.validatePositiveNumber(icN, ChaincodeConstants.num);
    ContractEnergyTrading.validatePositiveNumber(ipN, ChaincodeConstants.num);
    ContractEnergyTrading.validatePositiveNumber(timestampN, ChaincodeConstants.timestamp);
    ContractEnergyTrading.validatePositiveNumber(endDateN, ChaincodeConstants.endDate);
    ContractEnergyTrading.validatePositiveNumber(startDateN, ChaincodeConstants.startDate);


    if (smcString == null || smcString.isEmpty()) {
      ContractEnergyTrading.handleError("In register smc is null");
    }
    // Deserialize the smart contract data
    SmartContractData smc = ContractEnergyTrading.genson.deserialize(smcString, SmartContractData.class);
    consString = smc.getInitCons();
    prosString = smc.getInitPros();
    // Deserialize initial consumers
    ArrayList<ConsumerData> cons = ContractEnergyTrading.genson.deserialize(consString, new GenericType<ArrayList<ConsumerData>>() {});
    ArrayList<ConsumerData> delCons = new ArrayList<ConsumerData>();
    // Register each consumer
    for (int i = 0; i < icN; i++) {
      response = stub.invokeChaincodeWithStringArgs(ChaincodeConstants.consumerContract, ChaincodeConstants.sendTx, ChaincodeConstants.register, timestampN.toString(), ChaincodeConstants.ZERO_DOUBLE, smc.getPmax(), String.valueOf(i), startDateN, endDateN, smcString, channelName);
      if (response.getStatusCode() != ChaincodeConstants.SUCCESS_STATUS) {
        ContractEnergyTrading.handleError("Error invoking consumer sendTx: " + response.getMessage());
      }
      // Update SMC with payload returned from consumer registration
      smcString = response.getStringPayload();
      smc = ContractEnergyTrading.genson.deserialize(smcString, SmartContractData.class);

      ArrayList<String> argAsset = new ArrayList<String>();
      argAsset.add(String.valueOf(i));
      argAsset.add("setic");
      // Deserialize and update ownership structure
      String stringOwnership = "";
      stringOwnership = cons.get(i).getOcjOwnershipStructure();
      ArrayList<EnergyOwnership> ownershipStructure = ContractEnergyTrading.genson.deserialize(stringOwnership, new GenericType<ArrayList<EnergyOwnership>>() {});
      ownershipStructure.add(new EnergyOwnership(String.valueOf(i), ChaincodeConstants.ZERO_DOUBLE, ChaincodeConstants.register, timestampN));
      String stateJson = ContractEnergyTrading.genson.serialize(ownershipStructure);
      argAsset.add(stateJson);
      argAsset.add(ChaincodeConstants.setOcjOwnershipStructure);
      // Set asset on consumer contract
      response = stub.invokeChaincodeWithStringArgs(ChaincodeConstants.consumerContract, ChaincodeConstants.setAsset, ChaincodeConstants.CONSUMER, ContractEnergyTrading.genson.serialize(cons.get(i)), ContractEnergyTrading.genson.serialize(argAsset), channelName);
      if (response.getStatusCode() != ChaincodeConstants.SUCCESS_STATUS) {
        ContractEnergyTrading.handleError("Error invoking consumer setAsset " + response.getMessage());
      }
      // Fire event for consumer registration
      response = stub.invokeChaincodeWithStringArgs(ChaincodeConstants.smcContract, ChaincodeConstants.event, ChaincodeConstants.CONSUMER, timestampN, ChaincodeConstants.ZERO_INT, ChaincodeConstants.register, String.valueOf(i), ChaincodeConstants.FALSE_STRING, smcString, channelName);
      if (response.getStatusCode() != ChaincodeConstants.SUCCESS_STATUS) {
        ContractEnergyTrading.handleError("Error invoking consumer event: " + response.getMessage());
      }
      smcString = response.getStringPayload();
      smc = ContractEnergyTrading.genson.deserialize(smcString, SmartContractData.class);

      delCons.add(cons.get(i));
    }
    // Remove registered consumers from list
    cons.removeAll(delCons);

    smc.setInitCons(ContractEnergyTrading.genson.serialize(cons));
    smcString = ContractEnergyTrading.genson.serialize(smc);
    ContractEnergyTrading.logger.info("=======reg cons======");

    ArrayList<ProsumerData> pros = ContractEnergyTrading.genson.deserialize(prosString, new GenericType<ArrayList<ProsumerData>>() {});
    ArrayList<ProsumerData> delPros = new ArrayList<ProsumerData>();
    // Register each prosumer
    for (int j = 0; j < ipN; j++) {
      ArrayList<String> argAsset = new ArrayList<String>();
      argAsset.add(String.valueOf(j));
      argAsset.add(ChaincodeConstants.setIp);
      String stringOwnership = "";
      stringOwnership = pros.get(j).getOpiOwnershipStructure();
      ArrayList<EnergyOwnership> ownershipStructure = ContractEnergyTrading.genson.deserialize(stringOwnership, new GenericType<ArrayList<EnergyOwnership>>() {});
      ownershipStructure.add(new EnergyOwnership(String.valueOf(j), ChaincodeConstants.ZERO_DOUBLE, ChaincodeConstants.register, timestampN));
      String stateJson = ContractEnergyTrading.genson.serialize(ownershipStructure);
      argAsset.add(stateJson);
      argAsset.add(ChaincodeConstants.setOpiOwnershipStructure);
      // Update prosumer asset
      response = stub.invokeChaincodeWithStringArgs(ChaincodeConstants.prosumerContract, ChaincodeConstants.setAsset, ChaincodeConstants.PROSUMER, ContractEnergyTrading.genson.serialize(pros.get(j)), ContractEnergyTrading.genson.serialize(argAsset), channelName);
      if (response.getStatusCode() != ChaincodeConstants.SUCCESS_STATUS) {
        ContractEnergyTrading.handleError("Error invoking prosumer setAsset " + response.getMessage());
      }
      // Trigger prosumer registration
      response = stub.invokeChaincodeWithStringArgs(ChaincodeConstants.prosumerContract, ChaincodeConstants.sendTx, ChaincodeConstants.register, timestampN, ChaincodeConstants.ZERO_INT, smc.getPmax(), String.valueOf(j), startDateN, endDateN, smcString, channelName);
      if (response.getStatusCode() != ChaincodeConstants.SUCCESS_STATUS) {
        ContractEnergyTrading.handleError("Error invoking prosumer sendTx:" + response.getMessage());
      }
      // Trigger SMC event
      smcString = response.getStringPayload();
      response = stub.invokeChaincodeWithStringArgs(ChaincodeConstants.smcContract, ChaincodeConstants.event, ChaincodeConstants.PROSUMER, timestampN, ChaincodeConstants.ZERO_INT, ChaincodeConstants.register, String.valueOf(j), ChaincodeConstants.FALSE_STRING, smcString, channelName);
      if (response.getStatusCode() != ChaincodeConstants.SUCCESS_STATUS) {
        ContractEnergyTrading.handleError("Error invoking smc event:" + response.getMessage());
      }
      ContractEnergyTrading.logger.info("=======reg pros======");
      ContractEnergyTrading.logger.info(String.valueOf(j));
      smcString = response.getStringPayload();
      ContractEnergyTrading.logger.info(smcString);
      smc = ContractEnergyTrading.genson.deserialize(smcString, SmartContractData.class);
      delPros.add(pros.get(j));
    }
    // Remove registered prosumers from list
    pros.removeAll(delPros);
    smc.setInitPros(ContractEnergyTrading.genson.serialize(pros));
    // Final update to SMC with new state
    smcString = ContractEnergyTrading.genson.serialize(smc);
    response = stub.invokeChaincodeWithStringArgs(ChaincodeConstants.smcContract, ChaincodeConstants.smcSet, smcString, channelName);
    smcString = response.getStringPayload();
    return smcString;
  }
  /**
   *  injectEnergy - Prosumer injects the energy that it has available
   *  injectEnergy - Prosumer injects the energy that it has available into the system.
   *  This method:
   *  <ul>
   *      <li>Parses and validates input arguments like timestamp, start and end date, energy to inject (EiN).</li>
   *      <li>Retrieves current SmartContractData (smc).</li>
   *      <li>Finds the prosumer by ID and updates their scheduled injection table (Sit).</li>
   *      <li>Sends a message to the Prosumer contract to log the injection.</li>
   *      <li>Updates the Prosumer and SMC state in their respective ledgers.</li>
   *  </ul>
   *  @param ctx The transaction context
   *  @param arg placeholder for input parameters (IP, startDate, endDate, timestamp, EiN)
   *  @param channelName The name of the Fabric channel for cross-chaincode communication
   *  @return Updated SmartContractData as a JSON string
   */
  @Transaction(intent = Transaction.TYPE.SUBMIT)
  public String injectEnergy(Context ctx, final String ip, final String ei, final String timestamp, final String startDate, final String endDate, final String channelName) {
    // Initialize the chaincode stub
    ChaincodeStub stub = ctx.getStub();
    // Initialize input parameters
    Integer ipN = 0;
    Chaincode.Response response = null;
    String smcString;
    String timestampN = ChaincodeConstants.ZERO_INT;
    String startDateN = ChaincodeConstants.ZERO_INT;
    String endDateN = ChaincodeConstants.ZERO_INT;
    String EiN = ChaincodeConstants.ZERO_DOUBLE;
    ipN = Integer.valueOf(ip);
    EiN = ei;
    timestampN = timestamp;
    startDateN = startDate;
    endDateN = endDate;
    // Validate numerical inputs
    ContractEnergyTrading.validatePositiveNumber(ipN, ChaincodeConstants.num);
    ContractEnergyTrading.validatePositiveNumber(timestampN, ChaincodeConstants.timestamp);
    ContractEnergyTrading.validatePositiveNumber(endDateN, ChaincodeConstants.endDate);
    ContractEnergyTrading.validatePositiveNumber(startDateN, ChaincodeConstants.startDate);
    ContractEnergyTrading.logger.info(EiN + " EiN");
    ContractEnergyTrading.validatePositiveNumber(EiN, ChaincodeConstants.injected);
    // Retrieve the SmartContractData
    response = stub.invokeChaincodeWithStringArgs(ChaincodeConstants.smcContract, ChaincodeConstants.smcGet, channelName);
    if (response.getStatusCode() != ChaincodeConstants.SUCCESS_STATUS) {
      ContractEnergyTrading.handleError("Error invoking smcGet in injectenergy: " + response.getMessage());
    }
    // Deserialize SMC data
    smcString = response.getStringPayload();
    if (smcString == null || smcString.isEmpty()) {
      ContractEnergyTrading.handleError("No smc in injectenergy: " + response.getMessage());
    }
    SmartContractData smc = ContractEnergyTrading.genson.deserialize(smcString, SmartContractData.class);
    ContractEnergyTrading.logger.info(smcString);
    // Get registered prosumers
    String regProsString = smc.getRegisteredProsumers();
    ArrayList<ProsumerData> regPros = ContractEnergyTrading.genson.deserialize(regProsString, new GenericType<ArrayList<ProsumerData>>() {});
    // Get current prosumer and their (Sit)
    ProsumerData pro = regPros.get(ipN);
    HashMap<Long, Double> sintent = ContractEnergyTrading.genson.deserialize(pro.getSit(), new GenericType<HashMap<Long, Double>>() {});
    // Update SMC with serialized prosumer list
    smc.setRegisteredProsumers(ContractEnergyTrading.genson.serialize(regPros));
    smcString = ContractEnergyTrading.genson.serialize(smc);
    // Send injection message to Prosumer contract
    response = stub.invokeChaincodeWithStringArgs(ChaincodeConstants.prosumerContract, ChaincodeConstants.msg, ChaincodeConstants.inject, EiN, pro.getIp(), pro.getSmi(), String.valueOf(sintent.get(ContractEnergyTrading.parseLong(timestampN, ChaincodeConstants.timestamp))), timestampN, startDateN, endDateN, smcString, channelName);
    if (response.getStatusCode() != ChaincodeConstants.SUCCESS_STATUS) {
      ContractEnergyTrading.handleError("Error invoking prosumer msg: " + response.getMessage());
    }
    // Update SMC with response from Prosumer
    smcString = response.getStringPayload();
    if (smcString == null || smcString.isEmpty()) {
      ContractEnergyTrading.handleError("No smc in injectenergy after msg: " + response.getMessage());
    }
    smc = ContractEnergyTrading.genson.deserialize(smcString, SmartContractData.class);
    regProsString = smc.getRegisteredProsumers();
    regPros = ContractEnergyTrading.genson.deserialize(regProsString, new GenericType<ArrayList<ProsumerData>>() {});
    // Persist updated prosumer in ledger
    response = stub.invokeChaincodeWithStringArgs(ChaincodeConstants.prosumerContract, ChaincodeConstants.setAsset, ChaincodeConstants.PROSUMER, ContractEnergyTrading.genson.serialize(regPros.get(ipN)), ChaincodeConstants.empty_array_string, channelName);
    if (response.getStatusCode() != ChaincodeConstants.SUCCESS_STATUS) {
      ContractEnergyTrading.handleError("Error invoking prosumer setAsset " + response.getMessage());
    }
    // Save updated SMC
    response = stub.invokeChaincodeWithStringArgs(ChaincodeConstants.smcContract, ChaincodeConstants.smcSet, smcString, channelName);
    return response.getStringPayload();
  }
  /**
   *  aggregation - Collects and organizes energy supply and demand data from prosumers and 
   *  consumers during a specific time period
   *  This function performs a market round, where registered prosumers 
   *  express their intent to sell energy and registered consumers express 
   *  their intent to buy energy. All transactions and state updates are 
   *  handled via chaincode calls.
   *  @param ctx          the transaction context provided by the Hyperledger Fabric runtime
   *  @param arg         the list of input arguments; expected order:
   *                      <ul>
   *                          <li>Prosumer ID (int)</li>
   *                          <li>Start date (long)</li>
   *                          <li>End date (long)</li>
   *                          <li>Timestamp (long)</li>
   *                          <li>Injected energy Ei (double)</li>
   *                      </ul>
   *  @param channelName  the name of the channel where cross-contract invocations happen
   *  @return the updated SmartContractData in JSON format, as returned from the SMC
   *  @throws ChaincodeException if any required data is missing or invalid, or if a cross-contract
   *  invocation fails
   */
  @Transaction(intent = Transaction.TYPE.SUBMIT)
  public String aggregation(Context ctx, final String timestamp, final String startDate, final String endDate, final String sit, final String djt, final String channelName) {
    ChaincodeStub stub = ctx.getStub();
    // Capture the current timestamp and calculate time bounds aligned to 15-minute slots
    String ts = String.valueOf(new Date().getTime());
    String startDateN = String.valueOf(ContractEnergyTrading.roundDownTo15Minutes(new Date().getTime()));
    String endDateN = String.valueOf(ContractEnergyTrading.roundUpTo15Minutes(new Date().getTime()));
    // Initialize strings and data containers
    String prosString = "";
    String consString = "";
    Chaincode.Response response = null;
    String smcString = null;
    ArrayList<String> argReceive = new ArrayList<String>();
    HashMap<Long, Double> Sit = new HashMap<Long, Double>();
    ArrayList<Double> sitt = new ArrayList<Double>();
    HashMap<Long, Double> Djt = new HashMap<Long, Double>();
    ArrayList<Double> djtt = new ArrayList<Double>();
    ts = timestamp;
    startDateN = startDate;
    endDateN = endDate;
    sitt = ContractEnergyTrading.genson.deserialize(sit, new GenericType<ArrayList<Double>>() {});
    djtt = ContractEnergyTrading.genson.deserialize(djt, new GenericType<ArrayList<Double>>() {});
    // Validate timestamps and numeric inputs
    ContractEnergyTrading.validatePositiveNumber(ts, ChaincodeConstants.timestamp);
    ContractEnergyTrading.validatePositiveNumber(endDateN, ChaincodeConstants.endDate);
    ContractEnergyTrading.validatePositiveNumber(startDateN, ChaincodeConstants.startDate);
    // Validate each energy quantity to sell
    for (int i = 0; i < sitt.size(); i++) {
      ContractEnergyTrading.validatePositiveNumber(sitt.get(i), "Amount of intent to sell at index " + i);
    }
    // Validate each energy quantity to buy
    for (int i = 0; i < djtt.size(); i++) {
      ContractEnergyTrading.validatePositiveNumber(djtt.get(i), "Amount of intent to buy at index " + i);
    }
    // Retrieve the current SmartContractData (SMC)
    response = stub.invokeChaincodeWithStringArgs(ChaincodeConstants.smcContract, ChaincodeConstants.smcGet, channelName);
    if (response.getStatusCode() != ChaincodeConstants.SUCCESS_STATUS) {
      ContractEnergyTrading.handleError("Error invoking smcGet in aggregation: " + response.getMessage());
    }
    smcString = response.getStringPayload();
    if (smcString == null || smcString.isEmpty()) {
      ContractEnergyTrading.handleError("No SMC.", ChaincodeConstants.INVALID_ASSET_INPUT);
    }
    SmartContractData smc = ContractEnergyTrading.genson.deserialize(smcString, SmartContractData.class);
    consString = smc.getRegisteredConsumers();
    prosString = smc.getRegisteredProsumers();
    // Notify DSO that a new market round is starting
    response = stub.invokeChaincodeWithStringArgs(ChaincodeConstants.dsoContract, ChaincodeConstants.sendTx, ChaincodeConstants.roundstart, ts, startDateN, endDateN, "", "", "", "", smcString, channelName);
    if (response.getStatusCode() != ChaincodeConstants.SUCCESS_STATUS) {
      ContractEnergyTrading.handleError("Error invoking dso sendTx" + response.getMessage());
    }
    smcString = response.getStringPayload();
    if (smcString == null || smcString.isEmpty()) {
      ContractEnergyTrading.handleError("No smc after roundstart");
    }
    smc = ContractEnergyTrading.genson.deserialize(smcString, SmartContractData.class);
    consString = smc.getRegisteredConsumers();
    prosString = smc.getRegisteredProsumers();
    ArrayList<ProsumerData> pros = ContractEnergyTrading.genson.deserialize(prosString, new GenericType<ArrayList<ProsumerData>>() {});
    boolean prosEnergy = false;
    // Loop through all prosumers to process their intent to sell energy
    for (int i = 0; i < pros.size(); i++) {
      smc = ContractEnergyTrading.genson.deserialize(smcString, SmartContractData.class);
      prosString = smc.getRegisteredProsumers();
      pros = ContractEnergyTrading.genson.deserialize(prosString, new GenericType<ArrayList<ProsumerData>>() {});
      HashMap<Long, Double> sintent = ContractEnergyTrading.genson.deserialize(pros.get(i).getSit(), new GenericType<HashMap<Long, Double>>() {});
      response = stub.invokeChaincodeWithStringArgs(ChaincodeConstants.prosumerContract, ChaincodeConstants.sendTx, ChaincodeConstants.requestsell, String.valueOf(ts), String.valueOf(sitt.get(i)), smc.getPmax(), String.valueOf(i), startDateN, endDateN, smcString, channelName);
      if (response.getStatusCode() != ChaincodeConstants.SUCCESS_STATUS) {
        ContractEnergyTrading.handleError("Error invoking prosumer sendTx in aggregation" + response.getMessage());
      }
      ContractEnergyTrading.logger.info("-----------aggregate prosumer sendTx---------");
      ContractEnergyTrading.logger.info(response.getStringPayload());
      if (response.getStringPayload().equalsIgnoreCase(ChaincodeConstants.TRUE_STRING)) {
        prosEnergy = true;
        ContractEnergyTrading.logger.info("----In smc event prosumer -----");
        sintent.put(ContractEnergyTrading.parseLong(ts, ChaincodeConstants.timestamp), sintent.getOrDefault(ContractEnergyTrading.parseLong(ts, ChaincodeConstants.timestamp), 0.0) + sitt.get(i));
        pros.get(i).setSit(ContractEnergyTrading.genson.serialize(sintent));
        // Deduct sold energy from prosumer's balance
        Double num = ContractEnergyTrading.parseDouble(pros.get(i).getEi(), ChaincodeConstants.Ei) - sitt.get(i);
        final String Dmj;
        pros.get(i).setEi(String.valueOf(num));
        // Update SMC with new prosumer data
        smc.setRegisteredProsumers(ContractEnergyTrading.genson.serialize(pros));
        smcString = ContractEnergyTrading.genson.serialize(smc);
        // Emit 'injected' event
        response = stub.invokeChaincodeWithStringArgs(ChaincodeConstants.smcContract, ChaincodeConstants.event, ChaincodeConstants.PROSUMER, ts, String.valueOf(num), ChaincodeConstants.injected, String.valueOf(i), ChaincodeConstants.TRUE_STRING, smcString, channelName);
        if (response.getStatusCode() != ChaincodeConstants.SUCCESS_STATUS) {
          ContractEnergyTrading.handleError("Error invoking smc event injected: " + response.getMessage());
        }
        smcString = response.getStringPayload();
        // Emit 'board' event
        response = stub.invokeChaincodeWithStringArgs(ChaincodeConstants.smcContract, ChaincodeConstants.event, ChaincodeConstants.PROSUMER, String.valueOf(ts), String.valueOf(sitt.get(i)), ChaincodeConstants.board, String.valueOf(i), ChaincodeConstants.FALSE_STRING, smcString, channelName);
        if (response.getStatusCode() != ChaincodeConstants.SUCCESS_STATUS) {
          ContractEnergyTrading.handleError("Error invoking smc event board" + response.getMessage());
        }
        smcString = response.getStringPayload();
      } else {
        ContractEnergyTrading.logger.error("Prosumer " + i + " does not have enough injected energy");
      }
      for (Map.Entry<Long, Double> siT : sintent.entrySet()) {
        Long siTimestamp = siT.getKey();
        if (siTimestamp <= ContractEnergyTrading.parseLong(endDateN, ChaincodeConstants.timestamp) && siTimestamp >= ContractEnergyTrading.parseLong(startDateN, ChaincodeConstants.timestamp) && siT.getValue() != 0) {
          prosEnergy = true;
        }
      }
      // Update prosumer asset on ledger
      smc = ContractEnergyTrading.genson.deserialize(smcString, SmartContractData.class);
      prosString = smc.getRegisteredProsumers();
      pros = ContractEnergyTrading.genson.deserialize(prosString, new GenericType<ArrayList<ProsumerData>>() {});
      response = stub.invokeChaincodeWithStringArgs(ChaincodeConstants.prosumerContract, ChaincodeConstants.setAsset, ChaincodeConstants.PROSUMER, ContractEnergyTrading.genson.serialize(pros.get(i)), ChaincodeConstants.empty_array_string, channelName);
      if (response.getStatusCode() != ChaincodeConstants.SUCCESS_STATUS) {
        ContractEnergyTrading.handleError("Error invoking prosumer setAsset " + response.getMessage());
      }
    }
    // Write updated SMC to the ledger
    try {
      response = stub.invokeChaincodeWithStringArgs(ChaincodeConstants.smcContract, ChaincodeConstants.smcSet, smcString, channelName);
    } catch (Exception e) {
      ContractEnergyTrading.handleError("Error in writing smc in aggregation: " + e.getMessage());
    }
    // If no energy was offered by prosumers, abort
    if (!(prosEnergy)) {
      ContractEnergyTrading.handleError("There is no energy to sell ");
    }
    // Deserialize registered consumers
    ArrayList<ConsumerData> cons = ContractEnergyTrading.genson.deserialize(consString, new GenericType<ArrayList<ConsumerData>>() {});
    // Process each consumer’s buy request
    for (int j = 0; j < cons.size(); j++) {
      smc = ContractEnergyTrading.genson.deserialize(smcString, SmartContractData.class);
      consString = smc.getRegisteredConsumers();
      cons = ContractEnergyTrading.genson.deserialize(consString, new GenericType<ArrayList<ConsumerData>>() {});
      HashMap<Long, Double> demand = ContractEnergyTrading.genson.deserialize(cons.get(j).getDjt(), new GenericType<HashMap<Long, Double>>() {});
      // Send buy request to the consumer
      response = stub.invokeChaincodeWithStringArgs(ChaincodeConstants.consumerContract, ChaincodeConstants.sendTx, ChaincodeConstants.requestbuy, ts, String.valueOf(String.valueOf(djtt.get(j))), smc.getPmax(), String.valueOf(cons.get(j).getIc()), startDateN, endDateN, smcString, channelName);
      if (response.getStatusCode() != ChaincodeConstants.SUCCESS_STATUS) {
        ContractEnergyTrading.handleError("Error invoking consumer sendTx requestbuy " + response.getMessage());
      }
      ContractEnergyTrading.logger.info("-----------aggregate consumer sendTx---------");
      ContractEnergyTrading.logger.info(response.getStringPayload());
      if (response.getStringPayload().equalsIgnoreCase(ChaincodeConstants.TRUE_STRING)) {
        ContractEnergyTrading.logger.info("-----cons true smc----");
        ContractEnergyTrading.logger.info(response.getStringPayload());
        // Update consumer demand intent
        demand.put(ContractEnergyTrading.parseLong(ts, ChaincodeConstants.timestamp), demand.getOrDefault(ContractEnergyTrading.parseLong(ts, ChaincodeConstants.timestamp), 0.) + djtt.get(j));
        cons.get(j).setDjt(ContractEnergyTrading.genson.serialize(demand));
        smc.setRegisteredConsumers(ContractEnergyTrading.genson.serialize(cons));
        smcString = ContractEnergyTrading.genson.serialize(smc);
        // Persist updated SMC
        try {
          response = stub.invokeChaincodeWithStringArgs(ChaincodeConstants.smcContract, ChaincodeConstants.smcSet, smcString, channelName);
        } catch (Exception e) {
          ContractEnergyTrading.handleError("Error in writing smc in aggregation pros " + e.getMessage());
        }
        // Initiate transfer from consumer to prosumer
        response = stub.invokeChaincodeWithStringArgs(ChaincodeConstants.consumerContract, ChaincodeConstants.sendTx, ChaincodeConstants.transfer, ts, String.valueOf(djtt.get(j) * ContractEnergyTrading.parseDouble(smc.getPmax(), ChaincodeConstants.Pmax)), smc.getPmax(), cons.get(j).getIc(), startDateN, endDateN, smcString, channelName);
        ContractEnergyTrading.logger.info("----In true consumer sendTx transfer-----");
        ContractEnergyTrading.logger.info(response.getStringPayload());

        if (response.getStatusCode() != ChaincodeConstants.SUCCESS_STATUS) {
          ContractEnergyTrading.handleError("Error invoking consumer sendTx transfer " + response.getMessage());
        }
        // Update consumer asset
        smcString = response.getStringPayload();
        smc = ContractEnergyTrading.genson.deserialize(smcString, SmartContractData.class);
        consString = smc.getRegisteredConsumers();
        cons = ContractEnergyTrading.genson.deserialize(consString, new GenericType<ArrayList<ConsumerData>>() {});
        response = stub.invokeChaincodeWithStringArgs(ChaincodeConstants.consumerContract, ChaincodeConstants.setAsset, ChaincodeConstants.CONSUMER, ContractEnergyTrading.genson.serialize(cons.get(j)), ChaincodeConstants.empty_array_string, channelName);
        if (response.getStatusCode() != ChaincodeConstants.SUCCESS_STATUS) {
          ContractEnergyTrading.handleError("Error invoking consumer setAsset " + response.getMessage());
        }

      } else {
        ContractEnergyTrading.logger.error("Consumer " + j + " does not have enough funds");
      }
    }
    // Final update to SMC data
    response = stub.invokeChaincodeWithStringArgs(ChaincodeConstants.smcContract, ChaincodeConstants.smcSet, smcString, channelName);
    if (response.getStatusCode() != ChaincodeConstants.SUCCESS_STATUS) {
      ContractEnergyTrading.handleError("Error invoking smc smcSet: " + response.getMessage());
    }
    return response.getStringPayload();
  }
  /**
   *  matching - Responsible for pairing energy supply (Si) from prosumers with energy demand (Dj) from 
   *  consumers in an optimal and fair manner.
   *  Performs the energy matching process between prosumers and consumers.
   *  This method retrieves the latest SmartContractData, validates and updates
   *  time intervals, invokes the DSO matching process, and updates consumer data accordingly.
   *  @param ctx          the transaction context from Hyperledger Fabric
   *  @param arg         optional override parameters (startDate, endDate, timestamp),
   *                      supplied in order depending on $LOOP logic
   *  @param channelName  the name of the channel used for cross-contract invocations
   *  @return updated SmartContractData as a JSON string after matching has been performed
   *  @throws ChaincodeException if any inter-chaincode call fails, inputs are invalid, or serialization/deserialization errors occur
   */
  @Transaction(intent = Transaction.TYPE.SUBMIT)
  public String matching(Context ctx, final String timestamp, final String startDate, final String endDate, final String channelName) {
    ChaincodeStub stub = ctx.getStub();
    // Get current timestamp
    Long ts = new Date().getTime();
    // Round to nearest 15-minute window for scheduling
    String startDateN = String.valueOf(ContractEnergyTrading.roundDownTo15Minutes(ts));
    String endDateN = String.valueOf(ContractEnergyTrading.roundUpTo15Minutes(ts));
    String timestampN = String.valueOf(ts);
    String smcString = "";
    SmartContractData smc;
    Chaincode.Response response = null;
    Chaincode.Response request = null;

    timestampN = timestamp;
    startDateN = startDate;
    endDateN = endDate;
    // Validate the date and timestamp values
    ContractEnergyTrading.validatePositiveNumber(timestampN, ChaincodeConstants.timestamp);
    ContractEnergyTrading.validatePositiveNumber(endDateN, ChaincodeConstants.endDate);
    ContractEnergyTrading.validatePositiveNumber(startDateN, ChaincodeConstants.startDate);
    // Get SmartContractData from smc contract
    response = stub.invokeChaincodeWithStringArgs(ChaincodeConstants.smcContract, ChaincodeConstants.smcGet, channelName);
    if (response.getStatusCode() != ChaincodeConstants.SUCCESS_STATUS) {
      ContractEnergyTrading.handleError("Error invoking smc smcGet: " + response.getMessage());
    }
    smcString = response.getStringPayload();
    // Call DSO contract to perform the actual matching with timestamp and window
    response = stub.invokeChaincodeWithStringArgs(ChaincodeConstants.dsoContract, ChaincodeConstants.sendTx, ChaincodeConstants.matching, timestampN, startDateN, endDateN, "", "", "", "", smcString, channelName);
    if (response.getStatusCode() != ChaincodeConstants.SUCCESS_STATUS) {
      ContractEnergyTrading.handleError("Error invoking dso sendTx matching " + response.getMessage());
    }
    // Get updated SmartContractData with matched results
    smcString = response.getStringPayload();
    // Deserialize SmartContractData
    smc = ContractEnergyTrading.genson.deserialize(smcString, SmartContractData.class);
    // Deserialize list of updated consumers
    String consString = smc.getRegisteredConsumers();
    ArrayList<ConsumerData> cons = ContractEnergyTrading.genson.deserialize(consString, new GenericType<ArrayList<ConsumerData>>() {});
    // Save updated consumer asset
    for (int i = 0; i < cons.size(); i++) {
      response = stub.invokeChaincodeWithStringArgs(ChaincodeConstants.consumerContract, ChaincodeConstants.setAsset, ChaincodeConstants.CONSUMER, ContractEnergyTrading.genson.serialize(cons.get(i)), ChaincodeConstants.empty_array_string, channelName);
      if (response.getStatusCode() != ChaincodeConstants.SUCCESS_STATUS) {
        ContractEnergyTrading.handleError("Error invoking consumer setAsset " + response.getMessage());
      }
    }
    // Save the updated SmartContractData
    request = stub.invokeChaincodeWithStringArgs(ChaincodeConstants.smcContract, ChaincodeConstants.smcSet, smcString, channelName);
    // Return the final SmartContractData string
    return request.getStringPayload();
  }
  /**
   *  tradeEnergy - Executes the final energy transactions by transferring payments and updating 
   *  balances based on the previously matched supply (Smi) and demand (Dmj). 
   *  tradeEnergy - Executes the energy trading transaction. 
   *  It performs the final matching of energy supply and demand by:
   *  <ul>
   *    <li>Transferring payments from consumers to prosumers based on matched energy amounts</li>
   *    <li>Updating the energy balances of all participants</li>
   *    <li>Resetting temporary trading data (Smi, Dmj, etc.)</li>
   *    <li>Updating the global state (SmartContractData)</li> 
   *  </ul> 
   *  Inputs:
   *  <ul>
   *    <li>ctx - Transaction context provided by Fabric</li>
   *    <li>arg - Arguments such as startDate, endDate, and timestamp</li>
   *    <li>channelName - The name of the channel for cross-chaincode invocation</li> 
   *  </ul>
   *  @return The updated SmartContractData in serialized JSON form
   *  @throws ChaincodeException. This method performs multiple cross-chaincode invocations and can throw exceptions 
   *  using a centralized handleError method ( throwing ChaincodeException).
   */
  @Transaction(intent = Transaction.TYPE.SUBMIT)
  public String tradeEnergy(Context ctx, final String timestamp, final String startDate, final String endDate, final String channelName) {
    ChaincodeStub stub = ctx.getStub();
    // Compute aligned 15-minute timestamps
    Long ts = ((new Date().getTime() + ChaincodeConstants.MILLISECONDS_IN_MINUTE - 1) / (ChaincodeConstants.MILLISECONDS_IN_MINUTE)) * ChaincodeConstants.MILLISECONDS_IN_MINUTE;
    String startDateN = String.valueOf(ContractEnergyTrading.roundDownTo15Minutes(ts));
    String endDateN = String.valueOf(ContractEnergyTrading.roundUpTo15Minutes(ts));
    String timestampN = String.valueOf(ts);
    Double pmaxN = 0.0;
    String prosString = "";
    String consString = "";
    String smcString = "";
    Chaincode.Response response = null;
    timestampN = timestamp;
    startDateN = startDate;
    endDateN = endDate;
    // Validate time parameters
    ContractEnergyTrading.validatePositiveNumber(timestampN, ChaincodeConstants.timestamp);
    ContractEnergyTrading.validatePositiveNumber(endDateN, ChaincodeConstants.endDate);
    ContractEnergyTrading.validatePositiveNumber(startDateN, ChaincodeConstants.startDate);
    // Recalculate times to ensure 15-minute alignment
    startDateN = String.valueOf(ContractEnergyTrading.roundDownTo15Minutes(ContractEnergyTrading.parseLong(timestampN, ChaincodeConstants.timestamp)));
    endDateN = String.valueOf(ContractEnergyTrading.roundUpTo15Minutes(ContractEnergyTrading.parseLong(timestampN, ChaincodeConstants.timestamp)));
    // Fetch global SmartContractData (SMC)
    response = stub.invokeChaincodeWithStringArgs(ChaincodeConstants.smcContract, ChaincodeConstants.smcGet, channelName);
    if (response.getStatusCode() != ChaincodeConstants.SUCCESS_STATUS) {
      ContractEnergyTrading.handleError("Error invoking smc smcGet: " + response.getMessage());
    }
    smcString = response.getStringPayload();
    if (smcString == null || smcString.isEmpty()) {
      ContractEnergyTrading.handleError("No smc tradingenergy");
    }
    SmartContractData smc = ContractEnergyTrading.genson.deserialize(smcString, SmartContractData.class);
    consString = smc.getRegisteredConsumers();
    if (consString == null || consString.isEmpty()) {
      ContractEnergyTrading.handleError("No registered consumers tradeenergy");
    }
    prosString = smc.getRegisteredProsumers();
    if (prosString == null || prosString.isEmpty()) {
      ContractEnergyTrading.handleError("No registered prosumers tradeenergy");
    }

    pmaxN = ContractEnergyTrading.parseDouble(smc.getPmax(), ChaincodeConstants.Pmax);
    // Deserialize prosumers and consumers
    ArrayList<ProsumerData> pros = ContractEnergyTrading.genson.deserialize(prosString, new GenericType<ArrayList<ProsumerData>>() {});
    ArrayList<ConsumerData> cons = ContractEnergyTrading.genson.deserialize(consString, new GenericType<ArrayList<ConsumerData>>() {});
    // Get the price from DSO after performing trading logic
    response = stub.invokeChaincodeWithStringArgs(ChaincodeConstants.dsoContract, ChaincodeConstants.sendTx, ChaincodeConstants.trade, timestampN, startDateN, endDateN, "", "", "", "", smcString, channelName);
    if (response.getStatusCode() != ChaincodeConstants.SUCCESS_STATUS || response.getStringPayload() == null || response.getStringPayload().isEmpty()) {
      ContractEnergyTrading.handleError("Error invoking dso sendTx trade tradeenergy" + response.getMessage());
    }
    Double p = ContractEnergyTrading.parseDouble(response.getStringPayload(), "Payload");
    ContractEnergyTrading.logger.info("------p------- " + response.getStringPayload());
    // Handle prosumer payouts and delete match entries
    for (int ik = 0; ik < pros.size(); ik++) {
      pros.get(ik).setBalancesP(String.valueOf(ContractEnergyTrading.parseDouble(pros.get(ik).getBalancesP(), ChaincodeConstants.balance) + ContractEnergyTrading.parseDouble(pros.get(ik).getSmi(), ChaincodeConstants.Smi) * p));
      response = stub.invokeChaincodeWithStringArgs(ChaincodeConstants.smcContract, ChaincodeConstants.sendTx, ChaincodeConstants.PROSUMER, ChaincodeConstants.transfer, pros.get(ik).getIp(), String.valueOf(ContractEnergyTrading.parseDouble(pros.get(ik).getSmi(), ChaincodeConstants.Smi) * p), smcString, channelName);
      if (response.getStatusCode() != ChaincodeConstants.SUCCESS_STATUS) {
        ContractEnergyTrading.handleError("Error invoking smc sendTx for pros: " + response.getMessage());
      }
      smcString = response.getStringPayload();
      response = stub.invokeChaincodeWithStringArgs(ChaincodeConstants.smcContract, ChaincodeConstants.delete, ChaincodeConstants.PROSUMER, timestampN, pros.get(ik).getSmi(), ChaincodeConstants.match, pros.get(ik).getIp(), smcString, channelName);
      if (response.getStatusCode() != ChaincodeConstants.SUCCESS_STATUS) {
        ContractEnergyTrading.handleError("Error invoking smc delete: " + response.getMessage());
      }
      smcString = response.getStringPayload();
      if (smcString == null || smcString.isEmpty()) {
        ContractEnergyTrading.handleError("No smc after the del pros match");
      }
    }
    Double val = 0.0;
    // Handle consumer payments
    for (int j = 0; j < cons.size(); j++) {
      GenericType<HashMap<Long, Double>> mapType = new GenericType<HashMap<Long, Double>>() {};
      HashMap<Long, Double> DjtN = ContractEnergyTrading.genson.deserialize(cons.get(j).getDjt(), mapType);
      for (Long tss : DjtN.keySet()) {
        if (tss >= ContractEnergyTrading.parseLong(startDateN, ChaincodeConstants.timestamp) && tss <= ContractEnergyTrading.parseLong(endDateN, ChaincodeConstants.timestamp)) {
          val = (DjtN.get(tss) == null ? 0.0 : DjtN.get(tss));
          break;
        }
      }
      response = stub.invokeChaincodeWithStringArgs(ChaincodeConstants.smcContract, ChaincodeConstants.sendTx, ChaincodeConstants.CONSUMER, ChaincodeConstants.transfer, cons.get(j).getIc(), String.valueOf(val * pmaxN - ContractEnergyTrading.parseDouble(cons.get(j).getDmj(), ChaincodeConstants.Dmj) * p), smcString, channelName);
      if (response.getStatusCode() != ChaincodeConstants.SUCCESS_STATUS) {
        ContractEnergyTrading.logger.error("Error invoking smc sendTx consumer transfer: " + response.getMessage());
      }
      smcString = response.getStringPayload();
      if (smcString == null || smcString.isEmpty()) {
        ContractEnergyTrading.handleError("No smc te after sendTx cons transfer");
      }
      // Delete matched demand
      response = stub.invokeChaincodeWithStringArgs(ChaincodeConstants.smcContract, ChaincodeConstants.delete, ChaincodeConstants.CONSUMER, timestampN, cons.get(j).getDmj(), ChaincodeConstants.match, cons.get(j).getIc(), smcString, channelName);
      if (response.getStatusCode() != ChaincodeConstants.SUCCESS_STATUS) {
        ContractEnergyTrading.handleError("Error invoking smc delete consumer: " + response.getMessage());
      }
      smcString = response.getStringPayload();
      if (smcString == null || smcString.isEmpty()) {
        ContractEnergyTrading.handleError("No smc te after delete cons match");
      }
      // Emit event for completed purchase
      response = stub.invokeChaincodeWithStringArgs(ChaincodeConstants.smcContract, ChaincodeConstants.event, ChaincodeConstants.CONSUMER, timestampN, cons.get(j).getDmj(), ChaincodeConstants.purchased, cons.get(j).getIc(), ChaincodeConstants.TRUE_STRING, smcString, channelName);
      if (response.getStatusCode() != ChaincodeConstants.SUCCESS_STATUS) {
        ContractEnergyTrading.handleError("Error invoking smc event consumer: " + response.getMessage());
      }
      smcString = response.getStringPayload();
    }
    // Reset all prosumers and consumers nercessary values to default state
    SmartContractData smcN = ContractEnergyTrading.genson.deserialize(smcString, SmartContractData.class);
    consString = smcN.getRegisteredConsumers();
    if (consString == null || consString.isEmpty()) {
      ContractEnergyTrading.handleError("No registered consumers tradeenergy");
    }
    prosString = smcN.getRegisteredProsumers();
    if (prosString == null || prosString.isEmpty()) {
      ContractEnergyTrading.handleError("No registered prosumers");
    }
    pros = ContractEnergyTrading.genson.deserialize(prosString, new GenericType<ArrayList<ProsumerData>>() {});
    for (int ji = 0; ji < pros.size(); ji++) {
      pros.get(ji).setSmi(ChaincodeConstants.ZERO_DOUBLE);
      pros.get(ji).setSit(ChaincodeConstants.empty_json_string);
      response = stub.invokeChaincodeWithStringArgs(ChaincodeConstants.prosumerContract, ChaincodeConstants.setAsset, ChaincodeConstants.PROSUMER, ContractEnergyTrading.genson.serialize(pros.get(ji)), ChaincodeConstants.empty_array_string, channelName);
      if (response.getStatusCode() != ChaincodeConstants.SUCCESS_STATUS) {
        ContractEnergyTrading.handleError("Error invoking prosumer setAsset " + response.getMessage());
      }

    }

    cons = ContractEnergyTrading.genson.deserialize(consString, new GenericType<ArrayList<ConsumerData>>() {});
    for (int ji = 0; ji < cons.size(); ji++) {
      cons.get(ji).setDmj(ChaincodeConstants.ZERO_DOUBLE);
      cons.get(ji).setDjt(ChaincodeConstants.empty_json_string);
      response = stub.invokeChaincodeWithStringArgs(ChaincodeConstants.consumerContract, ChaincodeConstants.setAsset, ChaincodeConstants.CONSUMER, ContractEnergyTrading.genson.serialize(cons.get(ji)), ChaincodeConstants.empty_array_string, channelName);
      if (response.getStatusCode() != ChaincodeConstants.SUCCESS_STATUS) {
        ContractEnergyTrading.handleError("Error invoking consumer setAsset " + response.getMessage());
      }

    }
    // Reset system balances to zero
    ArrayList<Double> balances = ContractEnergyTrading.genson.deserialize(smcN.getBalances(), new GenericType<ArrayList<Double>>() {});
    for (int k = 0; k < balances.size(); k++) {
      balances.set(k, 0.0);
    }
    smcN.setBalances(ContractEnergyTrading.genson.serialize(balances));
    smcN.setRegisteredProsumers(ContractEnergyTrading.genson.serialize(pros));
    smcN.setRegisteredConsumers(ContractEnergyTrading.genson.serialize(cons));

    // Persist final state
    smcString = ContractEnergyTrading.genson.serialize(smcN);
    response = stub.invokeChaincodeWithStringArgs(ChaincodeConstants.smcContract, ChaincodeConstants.smcSet, smcString, channelName);
    return response.getStringPayload();
  }

}
