package EnergyDSL.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.ConceptPresentationAspectBase;
import jetbrains.mps.smodel.runtime.ConceptPresentation;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.ConceptPresentationBuilder;

public class ConceptPresentationAspectImpl extends ConceptPresentationAspectBase {
  private ConceptPresentation props_Asset;
  private ConceptPresentation props_Consumer;
  private ConceptPresentation props_ConsumerTransaction;
  private ConceptPresentation props_Contract;
  private ConceptPresentation props_CoreConcept;
  private ConceptPresentation props_CoreConceptRef;
  private ConceptPresentation props_DSO;
  private ConceptPresentation props_DSOTransaction;
  private ConceptPresentation props_EnergyTrading;
  private ConceptPresentation props_EnergyTradingTransaction;
  private ConceptPresentation props_Enumeration;
  private ConceptPresentation props_Event;
  private ConceptPresentation props_EventArg;
  private ConceptPresentation props_EventArgRef;
  private ConceptPresentation props_EventRef;
  private ConceptPresentation props_ExpressionEnergy;
  private ConceptPresentation props_ExpressionEnergyRef;
  private ConceptPresentation props_FunctionRef;
  private ConceptPresentation props_Global;
  private ConceptPresentation props_Prosumer;
  private ConceptPresentation props_ProsumerTransaction;
  private ConceptPresentation props_SMC;
  private ConceptPresentation props_SmcTransaction;
  private ConceptPresentation props_State;
  private ConceptPresentation props_StateMachine;
  private ConceptPresentation props_Transaction;
  private ConceptPresentation props_TransactionArg;
  private ConceptPresentation props_TransactionArgRef;
  private ConceptPresentation props_TransactionRef;
  private ConceptPresentation props_Transition;
  private ConceptPresentation props_Type;
  private ConceptPresentation props_TypesRef;
  private ConceptPresentation props_VarRef;
  private ConceptPresentation props_Variable;

  @Override
  @Nullable
  public ConceptPresentation getDescriptor(SAbstractConcept c) {
    StructureAspectDescriptor structureDescriptor = (StructureAspectDescriptor) myLanguageRuntime.getAspect(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.class);
    switch (structureDescriptor.internalIndex(c)) {
      case LanguageConceptSwitch.Asset:
        if (props_Asset == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.shortDesc("Asset");
          cpb.presentationByName();
          props_Asset = cpb.create();
        }
        return props_Asset;
      case LanguageConceptSwitch.Consumer:
        if (props_Consumer == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.shortDesc("Consumer or Buyer");
          cpb.presentationByName();
          props_Consumer = cpb.create();
        }
        return props_Consumer;
      case LanguageConceptSwitch.ConsumerTransaction:
        if (props_ConsumerTransaction == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.shortDesc("Consumer Transaction");
          cpb.presentationByName();
          props_ConsumerTransaction = cpb.create();
        }
        return props_ConsumerTransaction;
      case LanguageConceptSwitch.Contract:
        if (props_Contract == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.shortDesc("Concept that will be transfered to Smart Contract/Chaincode");
          cpb.presentationByName();
          props_Contract = cpb.create();
        }
        return props_Contract;
      case LanguageConceptSwitch.CoreConcept:
        if (props_CoreConcept == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_CoreConcept = cpb.create();
        }
        return props_CoreConcept;
      case LanguageConceptSwitch.CoreConceptRef:
        if (props_CoreConceptRef == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.shortDesc("CoreConcept reference");
          cpb.presentationByReference(0xbde2436d1f60406fL, 0xa6ddb2e955d43687L, 0x1cafdff73dafa54cL, 0x1cafdff73dc0479aL, "core", "", "");
          props_CoreConceptRef = cpb.create();
        }
        return props_CoreConceptRef;
      case LanguageConceptSwitch.DSO:
        if (props_DSO == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.shortDesc("Distribution System Operator");
          cpb.presentationByName();
          props_DSO = cpb.create();
        }
        return props_DSO;
      case LanguageConceptSwitch.DSOTransaction:
        if (props_DSOTransaction == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.shortDesc("DSO Transaction");
          cpb.presentationByName();
          props_DSOTransaction = cpb.create();
        }
        return props_DSOTransaction;
      case LanguageConceptSwitch.EnergyTrading:
        if (props_EnergyTrading == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_EnergyTrading = cpb.create();
        }
        return props_EnergyTrading;
      case LanguageConceptSwitch.EnergyTradingTransaction:
        if (props_EnergyTradingTransaction == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.shortDesc("Energy Trading Transaction");
          cpb.presentationByName();
          props_EnergyTradingTransaction = cpb.create();
        }
        return props_EnergyTradingTransaction;
      case LanguageConceptSwitch.Enumeration:
        if (props_Enumeration == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.shortDesc("Enumeration");
          cpb.presentationByName();
          props_Enumeration = cpb.create();
        }
        return props_Enumeration;
      case LanguageConceptSwitch.Event:
        if (props_Event == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_Event = cpb.create();
        }
        return props_Event;
      case LanguageConceptSwitch.EventArg:
        if (props_EventArg == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_EventArg = cpb.create();
        }
        return props_EventArg;
      case LanguageConceptSwitch.EventArgRef:
        if (props_EventArgRef == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByReference(0xbde2436d1f60406fL, 0xa6ddb2e955d43687L, 0x3f05b6ba906c8ee7L, 0x3f05b6ba906c94e8L, "arg", "", "");
          props_EventArgRef = cpb.create();
        }
        return props_EventArgRef;
      case LanguageConceptSwitch.EventRef:
        if (props_EventRef == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByReference(0xbde2436d1f60406fL, 0xa6ddb2e955d43687L, 0x3f05b6ba906c968aL, 0x3f05b6ba906c9f4bL, "event", "", "");
          props_EventRef = cpb.create();
        }
        return props_EventRef;
      case LanguageConceptSwitch.ExpressionEnergy:
        if (props_ExpressionEnergy == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_ExpressionEnergy = cpb.create();
        }
        return props_ExpressionEnergy;
      case LanguageConceptSwitch.ExpressionEnergyRef:
        if (props_ExpressionEnergyRef == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_ExpressionEnergyRef = cpb.create();
        }
        return props_ExpressionEnergyRef;
      case LanguageConceptSwitch.FunctionRef:
        if (props_FunctionRef == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_FunctionRef = cpb.create();
        }
        return props_FunctionRef;
      case LanguageConceptSwitch.Global:
        if (props_Global == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          props_Global = cpb.create();
        }
        return props_Global;
      case LanguageConceptSwitch.Prosumer:
        if (props_Prosumer == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_Prosumer = cpb.create();
        }
        return props_Prosumer;
      case LanguageConceptSwitch.ProsumerTransaction:
        if (props_ProsumerTransaction == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_ProsumerTransaction = cpb.create();
        }
        return props_ProsumerTransaction;
      case LanguageConceptSwitch.SMC:
        if (props_SMC == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_SMC = cpb.create();
        }
        return props_SMC;
      case LanguageConceptSwitch.SmcTransaction:
        if (props_SmcTransaction == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_SmcTransaction = cpb.create();
        }
        return props_SmcTransaction;
      case LanguageConceptSwitch.State:
        if (props_State == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_State = cpb.create();
        }
        return props_State;
      case LanguageConceptSwitch.StateMachine:
        if (props_StateMachine == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.shortDesc("State Machine");
          cpb.presentationByName();
          props_StateMachine = cpb.create();
        }
        return props_StateMachine;
      case LanguageConceptSwitch.Transaction:
        if (props_Transaction == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_Transaction = cpb.create();
        }
        return props_Transaction;
      case LanguageConceptSwitch.TransactionArg:
        if (props_TransactionArg == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_TransactionArg = cpb.create();
        }
        return props_TransactionArg;
      case LanguageConceptSwitch.TransactionArgRef:
        if (props_TransactionArgRef == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByReference(0xbde2436d1f60406fL, 0xa6ddb2e955d43687L, 0x77666e84444ab17aL, 0x77666e84444ab960L, "arg", "", "");
          props_TransactionArgRef = cpb.create();
        }
        return props_TransactionArgRef;
      case LanguageConceptSwitch.TransactionRef:
        if (props_TransactionRef == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByReference(0xbde2436d1f60406fL, 0xa6ddb2e955d43687L, 0x363c0888b3eec542L, 0x363c0888b3eecc9dL, "transaction", "", "");
          props_TransactionRef = cpb.create();
        }
        return props_TransactionRef;
      case LanguageConceptSwitch.Transition:
        if (props_Transition == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("transition");
          props_Transition = cpb.create();
        }
        return props_Transition;
      case LanguageConceptSwitch.Type:
        if (props_Type == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.shortDesc("Type");
          cpb.presentationByName();
          props_Type = cpb.create();
        }
        return props_Type;
      case LanguageConceptSwitch.TypesRef:
        if (props_TypesRef == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByReference(0xbde2436d1f60406fL, 0xa6ddb2e955d43687L, 0x664947cbee81146bL, 0x664947cbee811880L, "typeref", "", "");
          props_TypesRef = cpb.create();
        }
        return props_TypesRef;
      case LanguageConceptSwitch.VarRef:
        if (props_VarRef == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByReference(0xbde2436d1f60406fL, 0xa6ddb2e955d43687L, 0x3f05b6ba906ce1caL, 0x3f05b6ba906ce7afL, "varref", "", "");
          props_VarRef = cpb.create();
        }
        return props_VarRef;
      case LanguageConceptSwitch.Variable:
        if (props_Variable == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_Variable = cpb.create();
        }
        return props_Variable;
    }
    return null;
  }
}
